### ISSUE TITLE
error with installed file(s)...

### ISSUE THREAD

**Issue by Gr8sag3** [easydiffusion/easydiffusion#1042]
Install dir: C:\EasyDiffusion\
C:\Program Files\Git\cmd\git.exe
git version 2.40.0.windows.1
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 700bfc1 Merge pull request #1025 from cmdr2/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
497 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.

Hotfixed broken JSON file from OpenAI
"torch and torchvision have already been installed."
"sdkit is already installed."
sdkit version: 1.0.48
stable-diffusion version: 2.1.4
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Users\Lenovo\AppData\Local\Programs\Python\Python38\python.exe
Python 3.8.5
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\Scripts\uvicorn-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\EasyDiffusion\installer_files\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\EasyDiffusion\ui\main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 3, in <module>
    from easydiffusion import app
  File "C:\EasyDiffusion\ui\easydiffusion\app.py", line 11, in <module>
    from sdkit.utils import log as sdkit_log  # hack, so we can overwrite the log config
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\__init__.py", line 8, in <module>
    from .file_utils import load_tensor_file, save_dicts, save_images, save_tensor_file
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\file_utils.py", line 6, in <module>
    import safetensors.torch
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\safetensors\torch.py", line 5, in <module>
    import torch
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\lib\cusolverMg64_11.dll" or one of its dependencies.
Press any key to continue . . .

the error which I got.

**Comment by JeLuF** [comment]
> OSError: [WinError 1455] The paging file is too small for this operation to complete.
Please [add more paging space](https://www.ibm.com/docs/en/opw/8.2.0?topic=tuning-optional-increasing-paging-file-size-windows-computers)

**Comment by JeLuF** [comment]
closed due to inactivity
