### ISSUE TITLE
On MacOS, the PYTHONPATH is not unset although it should

### ISSUE THREAD

**Issue by duraki** [easydiffusion/easydiffusion#1128]
**Describe the bug**
The bug is experienced during initial provision and setup of this repo. I already have all the common dev tools on my Host OS (MacOS Ventra on M1 Pro). Albeit, I prefer to use `brew`'s Python3.11 for System-wide/XCode and also personal preference/clones. This, as you can guess requires fiddling within ENVs (environment variables) and one of this is `PYTHONPATH`.

This `PYTHONPATH` is set automatically on my zshell provision as seen below:

```sh
% grep -i "PYTHONPATH" -E \.[a-z]* -s
.zprofile:export PYTHONPATH="/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/":$PYTHONPATH

# whereas also seen at (default location):
# .bash_profile:PYTHONPATH=$PYTHONPATH:/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python

#       ... or ...
# .bashrc:PYTHONPATH=$ ...
# .zshrc:PYTHONP.PATH=$ ...
#       ... and so on
```

If the PYTHONPATH is manually set, as in my case, this results in error during `start.sh` script execution:

```sh
% ./start.sh             # => or sh start.sh
/opt/homebrew/opt/curl/bin/curl
/usr/bin/tar
/usr/bin/bzip2
/opt/homebrew/bin/git
git version 2.40.0
/Users/$USER/utils/easy-diffusion/installer_files/env/bin/conda

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

#     Traceback (most recent call last):
#       File "/Users/$USER/utils/easy-diffusion/installer_files/env/lib/python3.8/site-packages/conda/exceptions.py", line 1132, in __call__
#         return func(*args, **kwargs)
#       File "/Users/$USER/utils/easy-diffusion/installer_files/env/lib/python3.8/site-packages/conda/cli/main.py", line 57, in main_subshell
#         p = generate_parser()
#       File "/Users/$USER/utils/easy-diffusion/installer_files/env/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in generate_parser
#         sub_parsers = p.add_subparsers(
       File "/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/argparse.py", line 1698, in add_subparsers
#         action = parsers_class(option_strings=[], **kwargs)
#     TypeError: __init__() got an unexpected keyword argument 'required'

`$ /Users/$USER/utils/easy-diffusion/installer_files/env/bin/conda --version`

#  environment variables:
#                 CIO_TEST=<not set>
#               CONDA_ROOT=/Users/$USER/utils/easy-diffusion/installer_files/env
# [REDACTED]
                 PYTHONPATH=/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.1
              #            1/lib/python3.11/site-packages/::/Applications/Xcode.app/Contents/Shar
              #            edFrameworks/LLDB.framework/Resources/Python:/Applications/Xcode.app/C
              #            ontents/SharedFrameworks/LLDB.framework/Resources/Python
```

As seen above, at some point during the script, the installation script uses argumentation of the `PYTHONPATH` path pointing to Python 3.11, and therefore fails during early py modules provision.

**Failed Workaround**:
- Did `vim start.sh` and goto `:2` second line
- Insert (`i`) `export PYTHONPATH=""`
- Write or save (`:w`) buffer to file
- Reexecute the script `% ./start.sh`

```bash
# % cat start.sh
#!/bin/bash
export PYTHONPATH=""

cd "$(dirname "${BASH_SOURCE[0]}")"
...
```

This solution almost worked, the py modules started installing but then it failed again:

```sh
% ./start.sh
# ...
# Cloning into 'sd-ui-files'...
# ...
# Collecting mdurl~=0.1
#   Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)

  >>> module uvicorn not found

# Downloading packages necessary for Easy Diffusion..
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
#     ... REDACTED ...
#     TypeError: __init__() got an unexpected keyword argument 'required'

`$ /Users/$USER/utils/easy-diffusion/installer_files/env/bin/conda install -c conda-forge -y uvicorn fastapi`
``` 

**Working Solution:** (TODO: **PR** 😻)

Edit the `start.sh` script:

```sh
# cat start.sh
#!/bin/bash

unalias python              # some of you might have python aliased
unset PYTHONPATH   # unset previous pypath var

cd "$(dirname "${BASH_SOURCE[0]}")"
...
```

Install dependencies manually prior to running the script, otherwise it will still fail during startup:

```sh
% unset PYTHONPATH
% unalias python
% easy-diffusion/installer_files/env/bin/conda install -c conda-forge -y uvicorn fastapi
# ...
```

Finally start the script again and voi'la 🥳

```sh
% ./start.sh
# ...
# stable-diffusion version: 2.1.4
# ...
# Downloading data files (weights) for the default VAE (sd-vae-ft-mse-original)..
#   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
# Easy Diffusion installation complete, starting the server!
# 06:56:33.516 INFO MainThread started in /Users/$USER/utils/easy-diffusion/stable-diffusion
# 06:56:33.518 INFO MainThread started at 04/07/23 06:56:33                                                               
```

**To Reproduce**

Don't really know. Perhaps start by setting `PYTHONPATH` to unusual place in you shell cfg.

**Expected behavior**

Should use bundled Python version and modules.

**Screenshots** (post-solution)

<img width="1472" alt="Screenshot 2023-04-07 at 07 02 29" src="https://user-images.githubusercontent.com/5892610/230544545-a642f285-b28b-4366-93a7-c0c9bbf2e7fd.png">

**Desktop:**
 - OS: MacOS Ventura on ARM/M1
 - Browser: Safari

---

A possible solution is hiding in `developer_console.sh` but I have not tried it myself.

**Comment by JeLuF** [comment]
We install our own Python environment on purpose. We need to control the versions of the installed python packages because there are dependencies beyond what `pip` knows about. Our code has only been tested on Python 3.8.5

**Comment by duraki** [comment]
Hooray 🙌
