### ISSUE TITLE
не могу запустить stableDiffusion на Windows 11

### ISSUE THREAD

**Issue by Nikitaaleks** [easydiffusion/easydiffusion#1136]
не могу запустить stable Diffusion на Windows 11

Выдает ошибку:

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
C:\Users\Media Expert\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\Media Expert\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\Scripts\uvicorn-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\EasyDiffusion\installer_files\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\EasyDiffusion\ui\main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 3, in <module>
    from easydiffusion import app
  File "C:\EasyDiffusion\ui\easydiffusion\app.py", line 11, in <module>
    from sdkit.utils import log as sdkit_log  # hack, so we can overwrite the log config
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\__init__.py", line 8, in <module>
    from .file_utils import load_tensor_file, save_dicts, save_images, save_tensor_file
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\file_utils.py", line 6, in <module>
    import safetensors.torch
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\safetensors\torch.py", line 5, in <module>
    import torch
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 1455] Файл подкачки слишком мал для завершения операции. Error loading "C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\lib\cudnn_adv_train64_8.dll" or one of its dependencies.
Press any key to continue . . .

**Comment by JeLuF** [comment]
> "The paging file is too small to complete the operation"
Please increase your paging file.
https://www.ibm.com/docs/en/opw/8.2.0?topic=tuning-optional-increasing-paging-file-size-windows-computers

It should be at least 8GB in size, better 12GB.

**Comment by iamhumanipromise** [comment]
I've been having friends follow the same tips I followed for mining like 3-8 years ago. Borrowing from a few webpages as I can't find my old mining guides. 

From [AwesomeMiner](https://support.awesomeminer.com/support/solutions/articles/35000085973-environment-setup-setup-windows-environment-for-mining) we have Increase virtual memory

_Most mining software requires at least 16 GB virtual memory. In systems with many GPU's, even more virtual memory is required to be able to work well with all mining software and algorithms. A good rule of thumb is to allocate 8 GB plus the total amount of memory on all GPU's. When using 5 GPU's with 6 GB of memory each, the virtual memory to allocate should be 8 GB + 5 * 6 GB = 68 GB._

-     Open Control Panel and go to System
-     Select Advanced system settings
-     Click the Settings button in the Performance section
-     Select the Advanced tab
-     Click the Change button in the Virtual memory section
-     Define at least 16 GB virtual memory size

**Change power plan**

_Windows must be configured to not put the mining computer to sleep_

-     Open Control Panel and go to Power Options
-     In the Additional plans section, select High performance and then Change plan settings.
-     Set all options to Never
-    Go to Advanced Options - Set Link State Power Management to "Off" 
-     Save the changes

-----
-----

From my notes: 

- Create a .bat file with the following (optional, choose it for startup. Otherwise manually run when diffusioning: 

```
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100 
```

Or on Linux, configure your /etc/environment with: 

```
GPU_FORCE_64BIT_PTR 0
GPU_MAX_HEAP_SIZE 100
GPU_USE_SYNC_OBJECTS 1
GPU_MAX_ALLOC_PERCENT 100
GPU_SINGLE_ALLOC_PERCENT 100
```

**Comment by JeLuF** [comment]
Those environment settings are used by your mining software, but have no meaning for EasyDiffusion.

**Comment by iamhumanipromise** [comment]
> Those environment settings are used by your mining software, but have no meaning for EasyDiffusion.

I received a VRAM out of memory/memory allocation error when running a larger sized image. I added those flags, rebooted, and the memory error was resolved. 

Placebo effect?

**Comment by JeLuF** [comment]
closed due to OP inactivity
