### ISSUE TITLE
ImportError: cannot import name 'diffusers_latent_samples_to_images' from 'sdkit.utils' (C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\__init__.py)

### ISSUE THREAD

**Issue by laiziki486** [easydiffusion/easydiffusion#1152]
Hotfixed broken JSON file from OpenAI
"torch and torchvision have already been installed."
"sdkit is already installed."
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/sdkit/
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000207D0EBFF10>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/87/f0/2a152ed10ab8601431e87a606d397f7473c5fa4f8162f4ec5bda6ddb2df4/transformers-4.27.4-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000207D0ECD0D0>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/87/f0/2a152ed10ab8601431e87a606d397f7473c5fa4f8162f4ec5bda6ddb2df4/transformers-4.27.4-py3-none-any.whl
ERROR: Exception:
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\EasyDiffusion\installer_files\env\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\EasyDiffusion\installer_files\env\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\EasyDiffusion\installer_files\env\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\commands\install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\EasyDiffusion\installer_files\env\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
"Error updating sdkit"
sdkit version: 1.0.35
ERROR: Exception:
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\EasyDiffusion\installer_files\env\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\EasyDiffusion\installer_files\env\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\EasyDiffusion\installer_files\env\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\commands\install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 373, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 213, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 204, in _get_updated_criteria
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\EasyDiffusion\installer_files\env\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
"Error updating stable-diffusion-sdkit"
stable-diffusion version: 2.1.1
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
C:\Users\Administrator\anaconda3\python.exe
C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
10:57:49.179 INFO MainThread started in C:\EasyDiffusion\stable-diffusion                                   server.py:21
10:57:49.184 INFO MainThread started at 04/13/23 10:57:49                                                   server.py:22
10:57:49.304 INFO MainThread Scanned 3 models. Nothing infected                                     model_manager.py:254
10:57:49.369 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:457
Exception in thread cuda:0:
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\EasyDiffusion\installer_files\env\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 267, in thread_render
    from easydiffusion import renderer, model_manager
  File "C:\EasyDiffusion\ui\easydiffusion\renderer.py", line 13, in <module>
    from sdkit.utils import img_to_buffer, img_to_base64_str, latent_samples_to_images, diffusers_latent_samples_to_images
ImportError: cannot import name 'diffusers_latent_samples_to_images' from 'sdkit.utils' (C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\__init__.py)
10:58:49.916 WARNING MainThread cuda:0 failed to start.                                              task_manager.py:526
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\Scripts\uvicorn-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\EasyDiffusion\installer_files\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\EasyDiffusion\ui\main.py", line 6, in <module>
    app.init()
  File "C:\EasyDiffusion\ui\easydiffusion\app.py", line 69, in init
    update_render_threads()
  File "C:\EasyDiffusion\ui\easydiffusion\app.py", line 174, in update_render_threads
    task_manager.update_render_threads(render_devices, active_devices)
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 529, in update_render_threads
    raise EnvironmentError(
OSError: ERROR: No active render devices! Please verify the "render_devices" value in config.json

**Comment by JeLuF** [comment]
> 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443)

EasyDiffusion can't connect to one of its update servers. Please check your network settings. Are there any firewalls active that restrict Internet access?

**Comment by JeLuF** [comment]
closed due to inactivity
