### ISSUE TITLE
"Error updating sdkit" "Error updating stable-diffusion-sdkit"

### ISSUE THREAD

**Issue by GitZifeng** [easydiffusion/easydiffusion#1175]
Install dir: G:\EasyDiffusion\
C:\Program Files\Git\cmd\git.exe
git version 2.40.0.windows.1
G:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
G:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 11517b0 Merge pull request #1168 from cmdr2/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
复制了 499 个文件
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
已复制         1 个文件。
子目录或文件 tmp 已经存在。
"torch and torchvision have already been installed."
"sdkit is already installed."
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
ERROR: Could not find a version that satisfies the requirement sdkit==1.0.70 (from versions: none)
ERROR: No matching distribution found for sdkit==1.0.70
"Error updating sdkit"
sdkit version: 1.0.35
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
ERROR: Could not find a version that satisfies the requirement stable-diffusion-sdkit==2.1.4 (from versions: none)
ERROR: No matching distribution found for stable-diffusion-sdkit==2.1.4
"Error updating stable-diffusion-sdkit"
stable-diffusion version: 2.1.1
"rich has already been installed."
"Packages necessary for Easy Diffusion were already installed"
"Data files (weights) necessary for Stable Diffusion were already downloaded. Using the HuggingFace 4 GB Model."
"Data files (weights) necessary for GFPGAN (Face Correction) were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus were already downloaded"
"Data files (weights) necessary for ESRGAN (Resolution Upscaling) x4plus_anime were already downloaded"
"Data files (weights) necessary for the default VAE (sd-vae-ft-mse-original) were already downloaded"

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=G:\EasyDiffusion\installer_files\env\lib\site-packages
G:\EasyDiffusion\installer_files\env\python.exe
C:\Program Files\Python310\python.exe
C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
No module 'xformers'. Proceeding without it.
19:58:25.203 INFO MainThread started in G:\EasyDiffusion\stable-diffusion                                   server.py:21
19:58:25.207 INFO MainThread started at 04/18/23 19:58:25                                                   server.py:22
19:58:25.330 INFO MainThread Scanned 3 models. Nothing infected                                     model_manager.py:256
19:58:25.404 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:457
Exception in thread cuda:0:
Traceback (most recent call last):
  File "G:\EasyDiffusion\installer_files\env\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "G:\EasyDiffusion\installer_files\env\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "G:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 267, in thread_render
    from easydiffusion import renderer, model_manager
  File "G:\EasyDiffusion\ui\easydiffusion\renderer.py", line 13, in <module>
    from sdkit.utils import (
ImportError: cannot import name 'diffusers_latent_samples_to_images' from 'sdkit.utils' (G:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\__init__.py)
19:59:25.987 WARNING MainThread cuda:0 failed to start.                                              task_manager.py:526
Traceback (most recent call last):
  File "G:\EasyDiffusion\installer_files\env\Scripts\uvicorn-script.py", line 10, in <module>
    sys.exit(main())
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "G:\EasyDiffusion\installer_files\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "G:\EasyDiffusion\installer_files\env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "G:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "G:\EasyDiffusion\installer_files\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "G:\EasyDiffusion\ui\main.py", line 6, in <module>
    app.init()
  File "G:\EasyDiffusion\ui\easydiffusion\app.py", line 69, in init
    update_render_threads()
  File "G:\EasyDiffusion\ui\easydiffusion\app.py", line 174, in update_render_threads
    task_manager.update_render_threads(render_devices, active_devices)
  File "G:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 529, in update_render_threads
    raise EnvironmentError(
OSError: ERROR: No active render devices! Please verify the "render_devices" value in config.json

**Comment by LarryBug** [comment]
关闭代理，关闭防火墙，再试下就好了

**Comment by cmdr2** [comment]
Please try the latest version of Easy Diffusion, if this is still relevant: https://github.com/easydiffusion/easydiffusion/releases/tag/v3.0.2
