### ISSUE TITLE
img2img always produces out-of-bounds error

### ISSUE THREAD

**Issue by tom7** [easydiffusion/easydiffusion#1194]
Yesterday this workflow was working OK, but after today's update it is not. I see the same issue on both beta and main channels. Perhaps related to the sdkit update (I appear to have 1.0.81 but it seems from fea77e9 like there was some recent issue)?

**To Reproduce**
* Generate images with any model.
* Select "Use as input" for one of the images.
* Generate again.

This produces an error like
```
Error: Unexpected Read Error:
Error:undefined
EventInfo: {
    "reader": {}
}

Error: index 1000 is out of bounds for dimension 0 with size 1000
```

From the command window:

```
15:20:59.781 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:349  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 339, in thread_render
    task.response = renderer.make_images(
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 51, in make_images
    images, seeds = make_images_internal(req, task_data, data_queue, task_temp_images,
step_callback)
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 71, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "D:\EasyDiffusion\ui\easydiffusion\renderer.py", line 118, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py",
line 107, in generate_images
    images += generate_fn(common_sampler_params.copy(), **req_args)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py",
line 156, in img2img
    samples = make_samples(**params)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\sampler\sampler_main.py",
line 55, in make_samples
    return sampler_module.sample(
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\sampler\default_samplers.py",
line 44, in sample
    samples, _ = sample_fn(model, sampler_name, noise, steps, batch_size, common_params.copy(),
**kwargs)
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\sampler\default_samplers.py",
line 66, in _sample_img2img
    sampler.make_schedule(ddim_num_steps=steps, ddim_eta=0.0, verbose=False)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\models\diffusion\ddim.py", line
42, in make_schedule
    ddim_sigmas, ddim_alphas, ddim_alphas_prev =
make_ddim_sampling_parameters(alphacums=alphas_cumprod.cpu(),
  File
"D:\EasyDiffusion\installer_files\env\lib\site-packages\ldm\modules\diffusionmodules\util.py", line
65, in make_ddim_sampling_parameters
    alphas = alphacums
IndexError: index 1000 is out of bounds for dimension 0 with size 1000

15:20:59.970 INFO cuda:0 Session 1682191231942 task 2242244437184 failed!                            task_manager.py:358
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v2.5.34 (beta). Same happens for "main".
 - NVIDIA RTX 3080 Ti

**Comment by JeLuF** [comment]
How many inference steps did you use in your request? Some numbers don't work. It'll be fixed in an upcoming release.
