### ISSUE TITLE
Installation fails, "ERROR MainThread Invalid URL 'configs/v1-inference.yaml'", starting a second time reveals "No module named 'click'"

### ISSUE THREAD

**Issue by noahsmindfuck** [easydiffusion/easydiffusion#1229]
**Describe the bug**
Stable diffusion produces only colored blobs as images on first start. On second try it fails to start completely.

***First Error***
Installer (on fresh install) complains with: 

```
download stable-diffusion 1.4
13:53:44.583 INFO MainThread Downloading https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt to /home/noah/easy-diffusion/models/stable-diffusion/sd-v1-4.ckpt
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.97G/3.97G [00:46<00:00, 92.3MB/s]
13:54:30.818 ERROR MainThread Invalid URL 'configs/v1-inference.yaml': No scheme supplied. Perhaps you meant https://configs/v1-inference.yaml?
Traceback (most recent call last):
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model_downloader.py", line 60, in download_model
    download_file(config_url, out_path)
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/http_utils.py", line 20, in download_file
    res = requests.get(url, stream=True)
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'configs/v1-inference.yaml': No scheme supplied. Perhaps you meant https://configs/v1-inference.yaml?
stable-diffusion model(s) found.

```
It still manages to start though and works and produces something (see section Screenshots)

***Second Error***
Trying to run it a second time it doesn't even start anymode
```
~/easy-diffusion » /home/noah/easy-diffusion/start.sh                                                                                                                                                                            noah@noah
/usr/bin/curl
/usr/bin/tar
/usr/bin/bzip2
/usr/bin/git
git version 2.34.1
/home/noah/easy-diffusion/installer_files/env/bin/conda
conda 23.3.1


Easy Diffusion

Easy Diffusion's git repository was already installed. Updating from main..
HEAD is now at 228a5c4 Merge pull request #1217 from cmdr2/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 2.0.0
torchvision: 0.15.1
sdkit: 1.0.81
stable-diffusion-sdkit: 2.1.4
rich: 12.6.0
uvicorn: 0.19.0
fastapi: 0.85.1
Traceback (most recent call last):
  File "../scripts/check_models.py", line 3, in <module>
    from sdkit.models import download_model, get_model_info_from_db
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/__init__.py", line 1, in <module>
    from .model_downloader import (
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model_downloader.py", line 4, in <module>
    from sdkit.utils import download_file, log
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/__init__.py", line 20, in <module>
    from .latent_utils import (
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/latent_utils.py", line 9, in <module>
    from diffusers import StableDiffusionImg2ImgPipeline
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/accelerate_utils.py", line 24, in <module>
    import accelerate
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/tracking.py", line 49, in <module>
    import wandb
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/wandb/__init__.py", line 24, in <module>
    from wandb.errors.term import termsetup, termlog, termerror, termwarn
  File "/home/noah/easy-diffusion/installer_files/env/lib/python3.8/site-packages/wandb/errors/term.py", line 5, in <module>
    import click
ModuleNotFoundError: No module named 'click'

```

**To Reproduce**
1. download und unzip Easy-Diffusion-Linux.zip
2. run ./start.sh
3. observe first error
4. Ctrl+C
5. run ./start.sh
6. observe second error

**Screenshots produced after first and only successful start**
![image](https://user-images.githubusercontent.com/24893086/235351849-571ef113-b430-4eaf-ba11-3a24816a43c1.png)

**Desktop:**
 - OS: Kubuntu 22.04
 - Browser: Firefox 110.0.1 (64-bit)

**Comment by cmdr2** [comment]
Hi @noahsmindfuck If you're still interested, those colored blobs are because the image size needs to be atleast 512 pixels (because that's what the AI is trained on).

Regarding the second problem, is this still happening?

**Comment by noahsmindfuck** [comment]
Thanks for the feedback. I switched to a new machine with a new installation and cant reproduce the effect. I will close the issue.
