### ISSUE TITLE
Install error: no module named 'absl'

### ISSUE THREAD

**Issue by M0ebiu5** [easydiffusion/easydiffusion#1232]
Ubuntu 22.04
I'm using the start.sh script and get following error
How can i fix it?

```
/usr/bin/curl
/usr/bin/tar
/usr/bin/bzip2
/usr/bin/git
git version 2.34.1
/home/m00n/Downloads/easy-diffusion/installer_files/env/bin/conda
conda 23.3.1


Easy Diffusion

Easy Diffusion's git repository was already installed. Updating from main..
HEAD is now at 228a5c4 Merge pull request #1217 from cmdr2/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 2.0.0
torchvision: 0.15.1
sdkit: 1.0.81
stable-diffusion-sdkit: 2.1.4
rich: 12.6.0
uvicorn: 0.19.0
fastapi: 0.85.1
Traceback (most recent call last):
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 13, in <module>
    from tensorboard.summary.writer.event_file_writer import EventFileWriter
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/tensorboard/summary/__init__.py", line 33, in <module>
    from tensorboard.summary._output import DirectoryOutput  # noqa: F401
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/tensorboard/summary/_output.py", line 20, in <module>
    from tensorboard.util import tensor_util
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/__init__.py", line 25, in <module>
    from . import app  # noqa
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/app.py", line 21, in <module>
    from . import flags
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/flags.py", line 25, in <module>
    from absl.flags import *  # pylint: disable=wildcard-import
ModuleNotFoundError: No module named 'absl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../scripts/check_models.py", line 3, in <module>
    from sdkit.models import download_model, get_model_info_from_db
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/__init__.py", line 1, in <module>
    from .model_downloader import (
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model_downloader.py", line 4, in <module>
    from sdkit.utils import download_file, log
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/__init__.py", line 20, in <module>
    from .latent_utils import (
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/latent_utils.py", line 9, in <module>
    from diffusers import StableDiffusionImg2ImgPipeline
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/__init__.py", line 21, in <module>
    from .accelerate_utils import apply_forward_hook
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/diffusers/utils/accelerate_utils.py", line 24, in <module>
    import accelerate
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/home/m00n/Downloads/easy-diffusion/installer_files/env/lib/python3.8/site-packages/accelerate/tracking.py", line 44, in <module>
    import tensorboardX as tensorboard
ModuleNotFoundError: No module named 'tensorboardX'
```
Press any key to continue

**Comment by JeLuF** [comment]
A  user on discord reported a similar issue. Do you have the PYTHONHOME environment variable set?

**Comment by JeLuF** [comment]
Closed due to inactivity
