### ISSUE TITLE
Error launching start sh

### ISSUE THREAD

**Issue by mihaicatalind** [easydiffusion/easydiffusion#1249]
uvicorn main:server_api --app-dir "$sd_ui_path" --port "$
Killed on line 89

Here it is the error if I run it second time 
Traceback (most recent call last):
  File "../scripts/check_models.py", line 3, in <module>
    from sdkit.models import download_model, get_model_info_from_db
  File "/home/mihaicatalind/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/__init__.py", line 1, in <module>
    from .model_downloader import (
  File "/home/mihaicatalind/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model_downloader.py", line 4, in <module>
    from sdkit.utils import download_file, log
  File "/home/mihaicatalind/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/__init__.py", line 8, in <module>
    from .file_utils import load_tensor_file, save_dicts, save_images, save_tensor_file
  File "/home/mihaicatalind/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/file_utils.py", line 4, in <module>
    import piexif
ModuleNotFoundError: No module named 'piexif'

I did the pip install piexif and also conda install piexif and they are satisfied allready.

**Comment by JeLuF** [comment]
Ticket closed for inactivity
