### ISSUE TITLE
OSError: [WinError 127] The specified procedure could not be found

### ISSUE THREAD

**Issue by y0himba** [easydiffusion/easydiffusion#1251]
**Describe the bug**

```
"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\Tools\easydiffusion\installer_files\env\lib\site-packages
C:\Tools\easydiffusion\installer_files\env\python.exe
C:\Python310\python.exe
C:\Users\y0himba\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
Traceback (most recent call last):
  File "C:\Tools\easydiffusion\installer_files\env\Scripts\uvicorn-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Tools\easydiffusion\installer_files\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Tools\easydiffusion\installer_files\env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\uvicorn\config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Tools\easydiffusion\installer_files\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Tools\easydiffusion\ui\main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server
  File "C:\Tools\easydiffusion\ui\easydiffusion\model_manager.py", line 3, in <module>
    from easydiffusion import app
  File "C:\Tools\easydiffusion\ui\easydiffusion\app.py", line 10, in <module>
    from sdkit.utils import log as sdkit_log  # hack, so we can overwrite the log config
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\sdkit\utils\__init__.py", line 8, in <module>
    from .file_utils import load_tensor_file, save_dicts, save_images, save_tensor_file
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\sdkit\utils\file_utils.py", line 6, in <module>
    import safetensors.torch
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\safetensors\torch.py", line 5, in <module>
    import torch
  File "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Tools\easydiffusion\installer_files\env\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
Press any key to continue . . .
```

**To Reproduce**
1. Go to '`Easy Diffusion Folder`'
2. Click on '`Start Stable Diffusion UI.cmd`'
3. See error above

**Expected behavior**
I am unable to run Easy Diffusion at all. I would like to be able to use it again. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11462603/236361691-baa30f79-bf60-4dd8-86ce-fc4660ad175b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 (22621.1635)
 - Browser: Chrome
 - Version: 112.0.5615.138

**Additional context**
I have tried removing the directory, and reinstalling Easy Diffusion. I have tried installing it directly to the root of C:

**Comment by avelengaming** [comment]
did you find a fix?
