### ISSUE TITLE
[Linux] start.sh error after initially working fine for the first launch

### ISSUE THREAD

**Issue by BenCat07** [easydiffusion/easydiffusion#1253]
Upon install, ./start.sh starts the web UI just fine...

But the instant i try to launch it again, it just breaks by doing the following:
Even though it just installed, it updates torch via `python -m pip install --upgrade torch==2.0.0`

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
accelerate 0.18.0 requires numpy>=1.17, which is not installed.
accelerate 0.18.0 requires psutil, which is not installed.
accelerate 0.18.0 requires pyyaml, which is not installed.
basicsr 1.4.2 requires numpy>=1.17, which is not installed.
basicsr 1.4.2 requires Pillow, which is not installed.
basicsr 1.4.2 requires pyyaml, which is not installed.
clean-fid 0.1.35 requires numpy>=1.14.3, which is not installed.
clean-fid 0.1.35 requires pillow>=8.1, which is not installed.
clip-anytorch 2.5.2 requires regex, which is not installed.
compel 1.0.5 requires pyparsing~=3.0, which is not installed.
diffusers 0.15.1 requires importlib-metadata, which is not installed.
diffusers 0.15.1 requires numpy, which is not installed.
diffusers 0.15.1 requires Pillow, which is not installed.
diffusers 0.15.1 requires regex!=2019.12.17, which is not installed.
facexlib 0.3.0 requires numba, which is not installed.
facexlib 0.3.0 requires numpy, which is not installed.
facexlib 0.3.0 requires Pillow, which is not installed.
gfpgan 1.3.8 requires numpy, which is not installed.
gfpgan 1.3.8 requires pyyaml, which is not installed.
huggingface-hub 0.14.1 requires fsspec, which is not installed.
huggingface-hub 0.14.1 requires pyyaml>=5.1, which is not installed.
k-diffusion 0.0.14 requires Pillow, which is not installed.
open-clip-torch 2.0.2 requires regex, which is not installed.
pytorch-lightning 1.4.2 requires fsspec[http]!=2021.06.0,>=2021.05.0, which is not installed.
pytorch-lightning 1.4.2 requires numpy>=1.17.2, which is not installed.
pytorch-lightning 1.4.2 requires PyYAML>=5.1, which is not installed.
qudida 0.0.4 requires numpy>=0.18.0, which is not installed.
qudida 0.0.4 requires scikit-learn>=0.19.1, which is not installed.
realesrgan 0.3.0 requires numpy, which is not installed.
realesrgan 0.3.0 requires Pillow, which is not installed.
scikit-image 0.20.0 requires numpy>=1.21.1, which is not installed.
scikit-image 0.20.0 requires pillow>=9.0.1, which is not installed.
test-tube 0.7.5 requires numpy>=1.13.3, which is not installed.
test-tube 0.7.5 requires pandas>=0.20.3, which is not installed.
torchmetrics 0.6.0 requires numpy>=1.17.2, which is not installed.
torchsde 0.2.5 requires numpy>=1.19.*; python_version >= "3.7", which is not installed.
torchvision 0.15.1 requires numpy, which is not installed.
torchvision 0.15.1 requires pillow!=8.3.*,>=5.3.0, which is not installed.
transformers 4.26.1 requires numpy>=1.17, which is not installed.
transformers 4.26.1 requires pyyaml>=5.1, which is not installed.
transformers 4.26.1 requires regex!=2019.12.17, which is not installed.
wandb 0.15.2 requires Click!=8.0.0,>=7.0, which is not installed.
wandb 0.15.2 requires protobuf!=4.21.0,<5,>=3.12.0; python_version < "3.9" and sys_platform == "linux", which is not installed.
wandb 0.15.2 requires psutil>=5.0.0, which is not installed.
wandb 0.15.2 requires PyYAML, which is not installed.
```

Is the resulting mess of errors that come from it, and afterwards it refuses to start saying that it is missing PIL...

Reinstalling the entire thing works, but that's not really a solution...

Also of note. When i try to launch it once again after that:

```
Traceback (most recent call last):
  File "../scripts/check_models.py", line 3, in <module>
    from sdkit.models import download_model, get_model_info_from_db
  File "/home/lightcat/stable_diff/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/__init__.py", line 1, in <module>
    from .model_downloader import (
  File "/home/lightcat/stable_diff/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model_downloader.py", line 4, in <module>
    from sdkit.utils import download_file, log
  File "/home/lightcat/stable_diff/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/__init__.py", line 8, in <module>
    from .file_utils import load_tensor_file, save_dicts, save_images, save_tensor_file
  File "/home/lightcat/stable_diff/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/file_utils.py", line 8, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

Using the developer console to install Pillow results in it just saying 
``` 
python -m pip install Pillow
Requirement already satisfied: Pillow in /home/lightcat/.local/lib/python3.8/site-packages (9.5.0)
```

I have no idea what could be going wrong, maybe the info i provided will help.

Thanks for your time.

**Comment by JeLuF** [comment]
It's quite hard to see what's going on from excerpts of the logs. Can you please share the logs of an entire startup attempt?

**Comment by AVert** [comment]
$ ./start.sh 
/usr/bin/curl
/usr/bin/tar
/home/linuxbrew/.linuxbrew/bin/bzip2
/usr/bin/git
git version 2.34.1
/rpool/dev/AI/stable-diffusion/easy-diffusion/installer_files/env/bin/conda
conda 23.5.0


Easy Diffusion

Easy Diffusion's git repository was already installed. Updating from main..
HEAD is now at 41ecc82 Merge pull request #1305 from JeLuF/patch-27
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 2.0.0
torchvision: 0.15.1
sdkit: 1.0.97
stable-diffusion-sdkit: 2.1.4
rich: 12.6.0
uvicorn: 0.19.0
fastapi: 0.85.1
Traceback (most recent call last):
  File "../scripts/check_models.py", line 3, in <module>
    from sdkit.models import download_model, get_model_info_from_db
  File "/rpool/dev/AI/stable-diffusion/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/__init__.py", line 1, in <module>
    from .model_downloader import (
  File "/rpool/dev/AI/stable-diffusion/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model_downloader.py", line 4, in <module>
    from sdkit.utils import download_file, log
  File "/rpool/dev/AI/stable-diffusion/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/__init__.py", line 8, in <module>
    from .file_utils import load_tensor_file, save_dicts, save_images, save_tensor_file
  File "/rpool/dev/AI/stable-diffusion/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/file_utils.py", line 8, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by JeLuF** [comment]
```sh
bash developer_console.sh
export PYTHONNOUSERSITE=1
python -m pip install Pillow
exit
```

**Comment by JeLuF** [comment]
No update within 4 weeks => closed for inactivity
