### ISSUE TITLE
start.sh only works the first time

### ISSUE THREAD

**Issue by andresi** [easydiffusion/easydiffusion#1337]
If I unzip the release and run `start.sh`, it downloads everything and the server starts without any problem.
When I close it, and run `start.sh` again, it fails to start with this error. (If I remove the folder and unzip again, it works again)

```
$ ./start.sh
/usr/bin/curl
/usr/bin/tar
/usr/bin/bzip2
/usr/bin/git
git version 2.25.1
/home/ubuntu/easy-diffusion/installer_files/env/bin/conda
conda 23.5.0


Easy Diffusion

Easy Diffusion's git repository was already installed. Updating from main..
HEAD is now at a2856b2b Update README.md
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 2.0.0
torchvision: 0.15.1
sdkit: 1.0.98
stable-diffusion-sdkit: 2.1.4
rich: 12.6.0
uvicorn: 0.19.0
fastapi: 0.85.1
Traceback (most recent call last):
  File "../scripts/check_models.py", line 3, in <module>
    from sdkit.models import download_model, get_model_info_from_db
  File "/home/ubuntu/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/__init__.py", line 1, in <module>
    from .model_downloader import (
  File "/home/ubuntu/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/models/model_downloader.py", line 4, in <module>
    from sdkit.utils import download_file, log
  File "/home/ubuntu/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/__init__.py", line 8, in <module>
    from .file_utils import load_tensor_file, save_dicts, save_images, save_tensor_file
  File "/home/ubuntu/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/utils/file_utils.py", line 6, in <module>
    import safetensors.torch
ModuleNotFoundError: No module named 'safetensors'
Press any key to continue
```

I tried `pip install safetensors`, but it says `Requirement already satisfied: safetensors`

**Comment by sedwards2009** [comment]
I've hit something very similar, but it appears to be missing `filelock` package. Also on the second run of ED.

```
return _bootstrap._gcd_import(name[level:], package, level)
File "/home/sbe/easy-diffusion/installer_files/env/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 21, in <module>
from filelock import FileLock
ModuleNotFoundError: No module named 'filelock'
```

(Running Linux here)

**Comment by cmdr2** [comment]
Hi @andresi Closing this in favor of the thread that you've opened on our Discord server, to avoid duplicate investigation.

**Comment by cmdr2** [comment]
Discord support post - https://discord.com/channels/1014774730907209781/1116853979041767569

@andresi JeLuf and I have replied to your post there, and have asked a few questions that'll help with the investigation. Could you please take a look whenever you get a chance? Thanks
