### ISSUE TITLE
How i manage to work powerful AMD card with Easy Diffusion on Windows? Is this possible?

### ISSUE THREAD

**Issue by dilat1** [easydiffusion/easydiffusion#1392]
Hi. I'm not so good with coding - it is possible to generate pics at the same speed like nVidia cards? Or how to generate with AMD on Windows? It is also possible? Or for me - only CPU (slow)?

**Comment by fdwr** [comment]
Not yet. EasyDiffusion uses [SD Kit](https://github.com/easydiffusion/sdkit/) for generation, and SD Kit's readme states:

> We're looking to add support for textual inversion embeddings, AMD support, ControlNet, Pix2Pix, and outpainting. We'd love code contributions for these!

(disclaimer: I'm not a developer on this project, just a user)

**Comment by dilat1** [comment]
> > how to generate with AMD on Windows?
> 
> Not yet. EasyDiffusion uses [SD Kit](https://github.com/easydiffusion/sdkit/) for generation, and SD Kit's readme states:
> 
> > We're looking to add support for textual inversion embeddings, AMD support, ControlNet, Pix2Pix, and outpainting. We'd love code contributions for these!
> 
> (disclaimer: I'm not a developer on this project, just a user)

I'm hope, thats will be soon. I kinda sad, that purchase AMD card in some way, completely forgetting about supporting GPU's

**Comment by cmdr2** [comment]
Hi, @dilat1 I have the changes for AMD-on-Windows working in a branch, and will be merging it to beta soon. https://github.com/easydiffusion/sdkit/tree/nvidia

Will update this thread, so that you can test it and let me know if it works okay :) Thanks

**Comment by fdwr** [comment]
> haven't figured out how to support LoRA with the AMD version, but might be worth releasing to beta anyway.

So you got custom unet weights working though? If so, I'm really interested to hear how, because I tried adding them to my own little C++/ORT/DML app, but because the huggingface .onnx model ([1.4](https://huggingface.co/CompVis/stable-diffusion-v1-4) or [1.5](https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/onnx)) uses completely different names than the base PyTorch weights (and all the names inside the .safetensor's out there on civit.ai and huggingface), none of them mapped correctly to the base .onnx file 😭.

Yeah, for `add_free_dimension_override_by_name`, I also noticed it caused ONNX model load time to *greatly* increase 🤔.

**Comment by dilat1** [comment]
> Hi, @dilat1 I have the changes for AMD-on-Windows working in a branch, and will be merging it to beta soon. https://github.com/easydiffusion/sdkit/tree/nvidia
> 
> I haven't figured out how to support LoRA with the AMD version, but might be worth releasing to beta anyway.
> 
> Will update this thread, so that you can test it and let me know if it works okay :) Thanks

Sorry, but i'm a kinda noob. How i can test this? I have only Easy DIffusion. I don't like Stable Diffusion

**Comment by fdwr** [comment]
> How i can test this? 

Once merged to the beta branch, it can be enabled in Settings (easier than messing with config.yaml `update_branch` and typing `git` commands):

![image](https://github.com/easydiffusion/easydiffusion/assets/1809166/dde68866-22aa-4aef-ad32-e6c3ce873aa3)

> I have only Easy DIffusion. I don't like Stable Diffusion.

Note Easy Diffusion *is* Stable Diffusion. Stable Diffusion is not an app but rather it is the underlying neural network model that the various web UI's (Easy Diffusion, ComfyUI, A1111...) use to generate images.

**Comment by cmdr2** [comment]
@fdwr My current implementation converts the ckpt/safetensors model into ONNX, so I get to choose the labels. It doesn't use ONNX models created by others (including base). To be honest, I didn't think about it, so yeah I think it'll be good to add support for pre-created ONNX models as well :)

Here's where we trigger the ONNX creation (the first time a ckpt/safetensors is being loaded on AMD/Windows) - https://github.com/easydiffusion/sdkit/blob/main/sdkit/models/model_loader/stable_diffusion/__init__.py#L181

This performs the actual conversion, giving me control over the label names - https://github.com/easydiffusion/sdkit/blob/main/sdkit/utils/convert_model_utils.py#L7

And this is where I monkey-patch the pipeline `unet.forward` to use the ONNX instead - https://github.com/easydiffusion/sdkit/blob/main/sdkit/models/model_loader/stable_diffusion/__init__.py#L236

And finally, this is where the ONNX actually runs on DirectML - https://github.com/easydiffusion/sdkit/blob/main/sdkit/models/model_loader/stable_diffusion/accelerators.py#L22

I'm very new to this (DirectML, ONNX etc), so please feel free to suggest or submit any improvements :) I'm learning by the seat of my pants here.

**Comment by cmdr2** [comment]
@fdwr Regarding `add_free_dimension_override_by_name`, I was told that my label isn't matching the target, which is why it wasn't any faster. Will change that and try.

But I was also told that if we change the dimension of the image, we'd have to recreate the session (which means reloading the model), so that's a no-go for me.

**Comment by dilat1** [comment]
> Note Easy Diffusion _is_ Stable Diffusion

I know, but it's more "user-friendly"

Thanks, i will try "Beta channel"

**Comment by dilat1** [comment]
> > How i can test this?
> 
> Once merged to the beta branch, it can be enabled in Settings (easier than messing with config.yaml `update_branch` and typing `git` commands):
> 
> ![image](https://user-images.githubusercontent.com/1809166/251882075-dde68866-22aa-4aef-ad32-e6c3ce873aa3.png)
> 
> > I have only Easy DIffusion. I don't like Stable Diffusion.
> 
> Note Easy Diffusion _is_ Stable Diffusion. Stable Diffusion is not an app but rather it is the underlying neural network model that the various SD UI's (Easy Diffusion, ComfyUI, A1111...) share to generate images.

With "Beta Channel" it became a lot more longer, than before

**Comment by dilat1** [comment]
So, on nVidia ED generating in seconds. On AMD it takes 3 min. or above (technically, ED using CPU). It is possible to reduce this gap, who knows?

**Comment by fdwr** [comment]
@cmdr2 : Thanks for the links - I'll have to peruse the commit. I'm intimately familiar with DirectML, ONNX, and ONNX Runtime, given I've contributed hundreds of code changes to them the past few years. So, I'm happy to answer questions and give recommendations (but first to read what you've already got...).

**Comment by cmdr2** [comment]
@fdwr Thanks for your help! :) Wow, that's really cool what you've been working on, just went through your commit history. Thanks for your interest! Given how new I am to DirectML (and this field in general), I'll certainly pick your brain.

If you get a chance, I'd appreciate it if you could please take a look at the DirectML implementation. And let me know if anything stands out as a red flag. Please ignore the messy code style, we'll be refactoring the hacky diffusers implementation very shortly, as it's moving closer to becoming our mainstream engine. :)

The current intent is to atleast get AMD working on Windows, instead of running on the CPU. And optimize and build on that foundation in further releases.

The code I linked to will be moving to ED beta in a few hours, unless something goes horribly wrong.

**Comment by cmdr2** [comment]
@fdwr The specific commit (that might be less-cluttered to read) - https://github.com/easydiffusion/sdkit/commit/173e790277c8362fc46759188209765a6edcbf6b

**Comment by dilat1** [comment]
How to generate pics on AMD? If no one answer, i close this topic

**Comment by dilat1** [comment]
> @dilat1: _After_ the new change is merged to the beta branch, the feature can be enabled in Settings.

Changes merged automatically when i turn "Beta channel" on? Save and restart. And i don't see any differences

**Comment by cmdr2** [comment]
@dilat1 It's still being tested, which is why we haven't announced it to everyone.

If you want to try it, please follow these steps:
1. Enable "Beta" in Settings, press Save.
2. Refresh the browser.
3. Enable "Test Diffusers" in Settings, press Save.
4. Close the black-and-white command prompt window.

5. Run `Developer Console.bat` by double-clicking on it
6. Type this and press enter: `python -m pip install --upgrade protobuf==3.20.3 polygraphy==0.47.1 onnx==1.14.0 onnxruntime-directml==1.15.1 --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com`

7. Start Easy Diffusion, and try to generate an image.

It will take upto 5 minutes for the first image, since it'll convert the Stable Diffusion model to a special format (ONNX). After that, the images should be faster.

Please let me know if you face any problems. Thanks!

**Comment by cmdr2** [comment]
@fdwr I was wondering if you have any ideas for achieving LoRA support with ONNX? Like hot-loading the LoRA weight changes to a loaded ONNX model, instead of having to re-generate the entire ONNX model (like someone suggested to me).

If you're interested, we'd love to hear from you at our #development channel in the server - https://discord.gg/JK6GdScfqm

Otherwise I'm happy to continue chatting here. Thanks! :)

**Comment by dilat1** [comment]
> @dilat1 It's still being tested, which is why we haven't announced it to everyone.
> 
> If you want to try it, please follow these steps:
> 
>     1. Enable "Beta" in Settings, press Save.
> 
>     2. Refresh the browser.
> 
>     3. Enable "Test Diffusers" in Settings, press Save.
> 
>     4. Close the black-and-white command prompt window.
> 
>     5. Run `Developer Console.bat` by double-clicking on it
> 
>     6. Type this and press enter: `python -m pip install --upgrade protobuf==3.20.3 polygraphy==0.47.1 onnx==1.14.0 onnxruntime-directml==1.15.1 --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com`
> 
>     7. Start Easy Diffusion, and try to generate an image.
> 
> 
> It will take upto 5 minutes for the first image, since it'll convert the Stable Diffusion model to a special format (ONNX). After that, the images should be faster.
> 
> Please let me know if you face any problems. Thanks!

Nice answer, i defenitely try it. Thanks

**Comment by dilat1** [comment]
> @dilat1 It's still being tested, which is why we haven't announced it to everyone.
> 
> If you want to try it, please follow these steps:
> 
>     1. Enable "Beta" in Settings, press Save.
> 
>     2. Refresh the browser.
> 
>     3. Enable "Test Diffusers" in Settings, press Save.
> 
>     4. Close the black-and-white command prompt window.
> 
>     5. Run `Developer Console.bat` by double-clicking on it
> 
>     6. Type this and press enter: `python -m pip install --upgrade protobuf==3.20.3 polygraphy==0.47.1 onnx==1.14.0 onnxruntime-directml==1.15.1 --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com`
> 
>     7. Start Easy Diffusion, and try to generate an image.
> 
> 
> It will take upto 5 minutes for the first image, since it'll convert the Stable Diffusion model to a special format (ONNX). After that, the images should be faster.
> 
> Please let me know if you face any problems. Thanks!

Error: Could not load the stable-diffusion model! Reason: No module named 'wmi'

**Comment by ICC68208** [comment]
@dilat1 I also encountered the same error.
In my situation, this error was resolved by following:
1) Executing the following command in Developer Console.cmd.
python -m pip install wmi
python -m pip install pypiwin32
2) Restart Easy Diffusion.

good luck.

**Comment by cmdr2** [comment]
> Error: Could not load the stable-diffusion model! Reason: No module named 'wmi'

Ah sorry, I've updated the instructions to include the WMI installation.

In the developer console:
`python -m pip install --upgrade protobuf==3.20.3 polygraphy==0.47.1 onnx==1.14.0 onnxruntime-directml==1.15.1 WMI==1.5.1 --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com`

**Comment by cmdr2** [comment]
Thanks @ICC68208 ! Does your only have an integrated graphics card (RX Vega 10), or does it also have a separate dedicated graphics card?

@JeLuF also noticed that the integrated graphics card wasn't much faster than the CPU-based rendering.

You can open Task Manager in Windows, to see if your integrated graphics card is showing any activity while an image is generating.

**Comment by ICC68208** [comment]
@cmdr2 Only integrated graphics, no additional graphics cards.
Sorry I do not know how to identify the processes running on my graphics card. If you know the name of the process that would be running on the graphics card, please let me know. I will check it.

However, I beleave that supporting integrated graphics is not high priority; supporting AMD independent graphics cards is more effective.

thanks.

**Comment by OStogden** [comment]
I get this error when I try and generate anything using the steps above:

![image](https://github.com/easydiffusion/easydiffusion/assets/88672117/b5439f67-b690-4de4-b00b-251b395645a6)

GPU is a RX 6600 XT

**Comment by OStogden** [comment]
Hi, here's the output:

`11:36:29.289 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:376
11:36:30.398 INFO AnyIO worker thread Scanned 8 models. Nothing infected                            model_manager.py:386
11:36:31.991 INFO cpu loading on diffusers                                                               __init__.py:133
11:36:31.992 INFO cpu using config:                                                                      __init__.py:135
F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\models_db\configs\v1-inferenc
e.yaml
11:36:32.017 INFO cpu using attn_precision: fp32                                                         __init__.py:141
F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
11:38:18.832 INFO cpu Converting UNet to ONNX to run on AMD on Windows..                                 __init__.py:176
11:38:19.163 ERROR cpu Error while loading stable-diffusion model:                                   model_manager.py:77
F:\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt
11:38:19.165 ERROR cpu export() got an unexpected keyword argument 'use_external_data_format'        model_manager.py:83
Traceback (most recent call last):
  File "F:\stable-diffusion-ui\ui\easydiffusion\model_manager.py", line 68, in load_default_models
    load_model(
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\__init__.py
", line 33, in load_model
    context.models = _get_module(model_type).load_model(context, **kwargs)
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\stable_diff
usion\__init__.py", line 53, in load_model
    return load_diffusers_model(context, model_path, config_file_path, convert_to_tensorrt)
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\stable_diff
usion\__init__.py", line 177, in load_diffusers_model
    convert_pipeline_unet_to_onnx(default_pipe, unet_onnx_path, fp16=False)  # on cpu, so fp32
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\utils\convert_model_utils.py",
line 44, in convert_pipeline_unet_to_onnx
    onnx_export(
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\utils\convert_model_utils.py",
line 108, in onnx_export
    torch.onnx.export(model, model_args, output_path, **kwargs)
TypeError: export() got an unexpected keyword argument 'use_external_data_format'
11:38:19.482 INFO cpu Session 1689244588415 starting task 2215133128928 on AMD64 Family 23 Model 8   task_manager.py:314
Stepping 2, AuthenticAMD
11:38:19.530 INFO cpu loading stable-diffusion model from                                                 __init__.py:31
F:\stable-diffusion-ui\models\stable-diffusion\sd-v1-4.ckpt to device: cpu
11:38:19.535 INFO cpu loading on diffusers                                                               __init__.py:133
11:38:19.537 INFO cpu using config:                                                                      __init__.py:135
F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\models_db\configs\v1-inferenc
e.yaml
11:38:19.561 INFO cpu using attn_precision: fp32                                                         __init__.py:141
F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
11:38:33.087 INFO cpu Converting UNet to ONNX to run on AMD on Windows..                                 __init__.py:176
11:38:33.109 ERROR cpu export() got an unexpected keyword argument 'use_external_data_format'       model_manager.py:173
Traceback (most recent call last):
  File "F:\stable-diffusion-ui\ui\easydiffusion\model_manager.py", line 169, in
reload_models_if_necessary
    action_fn(context, model_type, scan_model=False)  # we've scanned them already
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\__init__.p
y", line 33, in load_model
    context.models = _get_module(model_type).load_model(context, **kwargs)
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\stable_dif
fusion\__init__.py", line 53, in load_model
    return load_diffusers_model(context, model_path, config_file_path, convert_to_tensorrt)
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\stable_dif
fusion\__init__.py", line 177, in load_diffusers_model
    convert_pipeline_unet_to_onnx(default_pipe, unet_onnx_path, fp16=False)  # on cpu, so fp32
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\utils\convert_model_utils.py",
line 44, in convert_pipeline_unet_to_onnx
    onnx_export(
  File
"F:\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\utils\convert_model_utils.py",
line 108, in onnx_export
    torch.onnx.export(model, model_args, output_path, **kwargs)
TypeError: export() got an unexpected keyword argument 'use_external_data_format'
11:38:33.325 ERROR cpu Traceback (most recent call last):                                            task_manager.py:356
  File "F:\stable-diffusion-ui\ui\easydiffusion\task_manager.py", line 339, in thread_render
    model_manager.fail_if_models_did_not_load(renderer.context)
  File "F:\stable-diffusion-ui\ui\easydiffusion\model_manager.py", line 202, in
fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: export() got an unexpected keyword
argument 'use_external_data_format'

11:38:33.442 INFO cpu Session 1689244588415 task 2215133128928 failed!                               task_manager.py:365`

**Comment by dilat1** [comment]
> > Error: Could not load the stable-diffusion model! Reason: No module named 'wmi'
> 
> Ah sorry, I've updated the instructions to include the WMI installation.
> 
> In the developer console: `python -m pip install --upgrade protobuf==3.20.3 polygraphy==0.47.1 onnx==1.14.0 onnxruntime-directml==1.15.1 WMI==1.5.1 --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com`

it is possible to make scaling of images faster? Like on nVidia? Generating is fast, but he struggles at the end for 15-20 seconds because of scaling

"INFO cpu Applying realesrgan... apply_filters.py:33
Tile 1/4
Tile 2/4
Tile 3/4
Tile 4/4"

pretty slow and using CPU. It is possible to using GPU?

**Comment by JarekDerp** [comment]
> @dilat1 It's still being tested, which is why we haven't announced it to everyone.
> 
> If you want to try it, please follow these steps:
> 
> 1. Enable "Beta" in Settings, press Save.
> 2. Refresh the browser.
> 3. Enable "Test Diffusers" in Settings, press Save.
> 4. Close the black-and-white command prompt window.
> 5. Run `Developer Console.bat` by double-clicking on it
> 6. Type this and press enter: `python -m pip install --upgrade protobuf==3.20.3 polygraphy==0.47.1 onnx==1.14.0 onnxruntime-directml==1.15.1 WMI==1.5.1 --extra-index-url=https://pypi.ngc.nvidia.com --trusted-host pypi.ngc.nvidia.com`
> 7. Start Easy Diffusion, and try to generate an image.
> 
> It will take upto 5 minutes for the first image, since it'll convert the Stable Diffusion model to a special format (ONNX). After that, the images should be faster.
> 
> Please let me know if you face any problems. Thanks!

Thanks a lot! It works. It used to take me about 40s per iteration, now it takes about 2-3s per iteration when generating two images! I have 6700XT and I love it, I think I will start playing around with SD again thanks to you. Generating 4 512x512 images (2 paralel) with 40 steps took me only 4 minutes, when before it would take me at least 25-30 minutes.

Some tips for others:
1. Disable "live preview" on the bottom of the page. It uses CPU and slows down image generation a lot. My GPU shows usage of 100% and then for a couple of secs shows 0% and then back to 100% so on, as it takes breaks to update the "live preview".
2. As far as I noticed the upscaling also uses CPU so disable the "Scale up by xx" on the bottom. Fixing faces takes seconds so I would recommend leaving it enabled.

**Comment by fdwr** [comment]
> Generating 4 512x512 images (2 parallel) with 40 steps took me only 4 minutes,

@JarekDerp Hmm, ~60 seconds per image is surprisingly slow, given I'm getting a full image 512x512 pixels at 25 iterations in just 5.5 seconds via ONNX Runtime + DirectML. Now that's on my NVidia RTX 2060 rather than an AMD Radeon 6700XT, but the XT was released 2 years later than my GPU and presumably should be comparable (according to GPUcheck.com, it's up to 47% faster), and additionally I'm just using the base ONNX model without even any multihead attention or GEMM+Softmax optimizations yet, just conversion to float16 and eager shape inference applied. I don't have an AMD card handy to compare, but something seems fishy 🤔.

**Comment by JarekDerp** [comment]
> > Generating 4 512x512 images (2 parallel) with 40 steps took me only 4 minutes,
> 
> @JarekDerp Hmm, ~60 seconds per image is surprisingly slow, given I'm getting a full image 512x512 pixels at 25 iterations in just 5.5 seconds via ONNX Runtime + DirectML. Now that's on my NVidia RTX 2060 rather than an AMD Radeon 6700XT, but the XT was released 2 years later than my GPU and presumably should be comparable (according to GPUcheck.com, it's up to 47% faster), and additionally I'm just using the base ONNX model without even any multihead attention or GEMM+Softmax optimizations yet, just conversion to float16 and eager shape inference applied. I don't have an AMD card handy to compare, but something seems fishy 🤔.

It might be faster in games, but it cannot compare with the cuda cores Nvidia has for productivity, like generating images using SD. I'm guessing that even 1060 would be faster in SD than my 6700xt.
I've found info online that the best people got was 1.5 it/s on my card which would take ~30s per image. I've noticed that my speed depends on the model, on some models it was 2.2s/it (or 0.4it/s) while on other models it was taking 5-6s per each step (for example the 2.1 model), so about 3 minutes for one image. It might have something to do with the size of the model but I didn't really experiment that much.
I read you can improve those numbers when running SD on Linux with AMD card, but I'm not a fun of Linux and don't really have time to play around with it. It's just a little hobby.

**Comment by JarekDerp** [comment]
@fdwr 
Okey, I experimented a bit after all, and you were right. I think I was using some very old trained models. I just downloaded a fresh one from Civitai, added some Loras and Embedding and the images are a lot better and they're generating at 1.5 - 2.2 it/s!
I just noticed a bug, when I cancel a job, it somehow slows down my next jobs so I have to refresh the page after each cancel. Oh well, I'm still satisfied. Thank!

**Comment by Dudeman456** [comment]
When opening the developer console I received the error:

`C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "C:\Users\Dudeman456\AppData\Local\Programs\Python\Python310\\lib\io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)`

**Comment by Dudeman456** [comment]
When opening the developer console I received the error:

`C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "C:\Users\Dudeman456\AppData\Local\Programs\Python\Python310\\lib\io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)`

**Comment by manotroll** [comment]
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by avachon100510** [comment]
Well, there is a similar predicament in my case... but I am using the AMD Radeon Vega Mobile Gfx GPU integrated with the AMD Ryzen 5 3500U CPU... on Windows! And EasyDiffusion only supports AMD GPUs on Linux... how am I even supposed to use the GPU?

**Comment by cmdr2** [comment]
Stale issue, please file a new issue for any further discussions.
