### ISSUE TITLE
Null bytes in Easy Diffusion.

### ISSUE THREAD

**Issue by Jevgeni6067** [easydiffusion/easydiffusion#1462]
**Describe the bug**
When installing Easy Diffusion, such an inscription appeared: ValueError: source code string cannot contain null bytes What to do with it?

**To Reproduce**
4. 
Install dir: D:\EasyDiffusion\
C:\Program Files\Git\cmd\git.exe
git version 2.41.0.windows.3
D:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
D:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at 710208f3 Update README.md
Already on 'main'
Your branch is up to date with 'origin/main'.
remote: Enumerating objects: 240, done.
Receiving objects: 100% (119/119), 20.9
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 119 (delta 84), reused 74 (delta 42), pack-reused 0
Resolving deltas: 100% (84/84), completed with 25 local objects.
From https://github.com/cmdr2/stable-diffusion-ui
   710208f3..851aa7aa  main          -> origin/main
   6a95c602..d47816e7  beta          -> origin/beta
 * [new tag]           v2.5.46.beta1 -> v2.5.46.beta1
 * [new tag]           v2.5.48       -> v2.5.48
Updating 710208f3..851aa7aa
Fast-forward
 CHANGES.md                                        |   30 +-
 CONTRIBUTING.md                                   |    4 +-
 How to install and run.txt                        |    6 +-
 PRIVACY.md                                        |    2 +-
 README BEFORE YOU RUN THIS.txt                    |    2 +-
 README.md                                         |    9 +-
 build.bat                                         |    3 +-
 build.sh                                          |    3 +-
 scripts/Developer Console.cmd                     |    8 +
 scripts/Start Stable Diffusion UI.cmd             |    3 +-
 scripts/bootstrap.bat                             |    2 +-
 scripts/check_modules.py                          |    7 +-
 scripts/config.yaml.sample                        |   24 +
 scripts/functions.sh                              |    4 +-
 scripts/get_config.py                             |   32 +-
 scripts/on_env_start.bat                          |    5 +-
 scripts/on_env_start.sh                           |    3 +-
 scripts/on_sd_start.bat                           |   12 +-
 scripts/on_sd_start.sh                            |    3 +-
 ui/easydiffusion/app.py                           |  141 +-
 ui/easydiffusion/model_manager.py                 |  164 +-
 ui/easydiffusion/package_manager.py               |   98 +
 ui/easydiffusion/renderer.py                      |  279 --
 ui/easydiffusion/runtime.py                       |   53 +
 ui/easydiffusion/server.py                        |  134 +-
 ui/easydiffusion/task_manager.py                  |  150 +-
 ui/easydiffusion/tasks/__init__.py                |    3 +
 ui/easydiffusion/tasks/filter_images.py           |  110 +
 ui/easydiffusion/tasks/render_images.py           |  340 +++
 ui/easydiffusion/tasks/task.py                    |   47 +
 ui/easydiffusion/types.py                         |  183 +-
 ui/easydiffusion/utils/save_utils.py              |   92 +-
 ui/index.html                                     |  421 ++-
 ui/main.py                                        |    6 +-
 ui/media/css/animations.css                       |   68 +
 ui/media/css/auto-save.css                        |    3 +-
 ui/media/css/main.css                             |  502 +++-
 ui/media/css/modifier-thumbnails.css              |  155 +-
 ui/media/css/plugins.css                          |  288 ++
 ui/media/css/themes.css                           |    5 +
 ui/media/js/auto-save.js                          |   17 +-
 ui/media/js/dnd.js                                |   83 +-
 ui/media/js/engine.js                             |   87 +-
 ui/media/js/image-editor.js                       |   21 +-
 ui/media/js/image-modifiers.js                    |  312 ++-
 ui/media/js/main.js                               |  978 ++++++-
 ui/media/js/parameters.js                         |  118 +-
 ui/media/js/plugins.js                            |  950 +++++++
 ui/media/js/searchable-models.js                  |   37 +-
 ui/media/js/utils.js                              |  234 ++
 ui/plugins/ui/image-editor-improvements.plugin.js | 2976 +++++++++++++++++++++
 ui/plugins/ui/lora-prompt-parser.plugin.js        |  114 +
 ui/plugins/ui/release-notes.plugin.js             |    4 +-
 ui/plugins/ui/tiled-image-download.plugin.js      |   33 +-
 54 files changed, 8278 insertions(+), 1090 deletions(-)
 create mode 100644 scripts/config.yaml.sample
 create mode 100644 ui/easydiffusion/package_manager.py
 delete mode 100644 ui/easydiffusion/renderer.py
 create mode 100644 ui/easydiffusion/runtime.py
 create mode 100644 ui/easydiffusion/tasks/__init__.py
 create mode 100644 ui/easydiffusion/tasks/filter_images.py
 create mode 100644 ui/easydiffusion/tasks/render_images.py
 create mode 100644 ui/easydiffusion/tasks/task.py
 create mode 100644 ui/media/css/animations.css
 create mode 100644 ui/media/css/plugins.css
 create mode 100644 ui/plugins/ui/image-editor-improvements.plugin.js
 create mode 100644 ui/plugins/ui/lora-prompt-parser.plugin.js
Скопировано файлов: 508.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Подпапка или файл tmp уже существует.
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
> python -m pip install --upgrade sdkit==1.0.165
Collecting sdkit==1.0.165
  Downloading sdkit-1.0.165-py3-none-any.whl (123 kB)
     ---------------------------------------- 123.1/123.1 kB 603.7 kB/s eta 0:00:00
Collecting invisible-watermark==0.2.0
  Downloading invisible_watermark-0.2.0-py3-none-any.whl (1.6 MB)
     ---------------------------------------- 1.6/1.6 MB 621.8 kB/s eta 0:00:00
Requirement already satisfied: requests in d:\easydiffusion\installer_files\env\lib\site-packages (from sdkit==1.0.165) (2.28.2)
Requirement already satisfied: safetensors in d:\easydiffusion\installer_files\env\lib\site-packages (from sdkit==1.0.165) (0.2.8)
Requirement already satisfied: piexif in d:\easydiffusion\installer_files\env\lib\site-packages (from sdkit==1.0.165) (1.1.3)
Requirement already satisfied: realesrgan in d:\easydiffusion\installer_files\env\lib\site-packages (from sdkit==1.0.165) (0.3.0)
Requirement already satisfied: picklescan in d:\easydiffusion\installer_files\env\lib\site-packages (from sdkit==1.0.165) (0.0.7)
Collecting controlnet-aux==0.0.6
  Downloading controlnet_aux-0.0.6-py3-none-any.whl (261 kB)
     ---------------------------------------- 261.9/261.9 kB 619.9 kB/s eta 0:00:00
Requirement already satisfied: accelerate==0.18.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from sdkit==1.0.165) (0.18.0)
Requirement already satisfied: stable-diffusion-sdkit==2.1.4 in d:\easydiffusion\installer_files\env\lib\site-packages (from sdkit==1.0.165) (2.1.4)
Requirement already satisfied: k-diffusion in d:\easydiffusion\installer_files\env\lib\site-packages (from sdkit==1.0.165) (0.0.14)
Collecting compel==2.0.1
  Downloading compel-2.0.1-py3-none-any.whl (29 kB)
Requirement already satisfied: gfpgan in d:\easydiffusion\installer_files\env\lib\site-packages (from sdkit==1.0.165) (1.3.8)
Collecting diffusers==0.19.2
  Downloading diffusers-0.19.2-py3-none-any.whl (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 595.2 kB/s eta 0:00:00
Requirement already satisfied: torch>=1.4.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from accelerate==0.18.0->sdkit==1.0.165) (1.13.1+cu116)
Requirement already satisfied: psutil in d:\easydiffusion\installer_files\env\lib\site-packages (from accelerate==0.18.0->sdkit==1.0.165) (5.9.4)
Requirement already satisfied: packaging>=20.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from accelerate==0.18.0->sdkit==1.0.165) (23.0)
Requirement already satisfied: numpy>=1.17 in d:\easydiffusion\installer_files\env\lib\site-packages (from accelerate==0.18.0->sdkit==1.0.165) (1.23.5)
Requirement already satisfied: pyyaml in d:\easydiffusion\installer_files\env\lib\site-packages (from accelerate==0.18.0->sdkit==1.0.165) (6.0)
Requirement already satisfied: pyparsing~=3.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from compel==2.0.1->sdkit==1.0.165) (3.0.9)
Requirement already satisfied: transformers~=4.25 in d:\easydiffusion\installer_files\env\lib\site-packages (from compel==2.0.1->sdkit==1.0.165) (4.26.1)
Requirement already satisfied: torchvision in d:\easydiffusion\installer_files\env\lib\site-packages (from controlnet-aux==0.0.6->sdkit==1.0.165) (0.14.1+cu116)
Requirement already satisfied: opencv-python in d:\easydiffusion\installer_files\env\lib\site-packages (from controlnet-aux==0.0.6->sdkit==1.0.165) (4.6.0.66)
Requirement already satisfied: huggingface-hub in d:\easydiffusion\installer_files\env\lib\site-packages (from controlnet-aux==0.0.6->sdkit==1.0.165) (0.16.4)
Collecting timm
  Downloading timm-0.9.2-py3-none-any.whl (2.2 MB)
     ---------------------------------------- 2.2/2.2 MB 638.1 kB/s eta 0:00:00
Requirement already satisfied: importlib-metadata in d:\easydiffusion\installer_files\env\lib\site-packages (from controlnet-aux==0.0.6->sdkit==1.0.165) (6.0.0)
Requirement already satisfied: Pillow in d:\easydiffusion\installer_files\env\lib\site-packages (from controlnet-aux==0.0.6->sdkit==1.0.165) (9.4.0)
Requirement already satisfied: einops in d:\easydiffusion\installer_files\env\lib\site-packages (from controlnet-aux==0.0.6->sdkit==1.0.165) (0.3.0)
Requirement already satisfied: scikit-image in d:\easydiffusion\installer_files\env\lib\site-packages (from controlnet-aux==0.0.6->sdkit==1.0.165) (0.19.3)
Requirement already satisfied: scipy in d:\easydiffusion\installer_files\env\lib\site-packages (from controlnet-aux==0.0.6->sdkit==1.0.165) (1.10.1)
Requirement already satisfied: filelock in d:\easydiffusion\installer_files\env\lib\site-packages (from controlnet-aux==0.0.6->sdkit==1.0.165) (3.9.0)
Collecting safetensors
  Downloading safetensors-0.3.1-cp38-cp38-win_amd64.whl (263 kB)
     ---------------------------------------- 263.9/263.9 kB 560.0 kB/s eta 0:00:00
Requirement already satisfied: regex!=2019.12.17 in d:\easydiffusion\installer_files\env\lib\site-packages (from diffusers==0.19.2->sdkit==1.0.165) (2022.10.31)
Requirement already satisfied: PyWavelets>=1.1.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from invisible-watermark==0.2.0->sdkit==1.0.165) (1.4.1)
Requirement already satisfied: basicsr>=1.4.2 in d:\easydiffusion\installer_files\env\lib\site-packages (from gfpgan->sdkit==1.0.165) (1.4.2)
Requirement already satisfied: lmdb in d:\easydiffusion\installer_files\env\lib\site-packages (from gfpgan->sdkit==1.0.165) (1.4.0)
Requirement already satisfied: facexlib>=0.2.5 in d:\easydiffusion\installer_files\env\lib\site-packages (from gfpgan->sdkit==1.0.165) (0.2.5)
Requirement already satisfied: yapf in d:\easydiffusion\installer_files\env\lib\site-packages (from gfpgan->sdkit==1.0.165) (0.32.0)
Requirement already satisfied: tqdm in d:\easydiffusion\installer_files\env\lib\site-packages (from gfpgan->sdkit==1.0.165) (4.64.1)
Requirement already satisfied: tb-nightly in d:\easydiffusion\installer_files\env\lib\site-packages (from gfpgan->sdkit==1.0.165) (2.13.0a20230220)
Requirement already satisfied: clip-anytorch in d:\easydiffusion\installer_files\env\lib\site-packages (from k-diffusion->sdkit==1.0.165) (2.5.0)
Requirement already satisfied: jsonmerge in d:\easydiffusion\installer_files\env\lib\site-packages (from k-diffusion->sdkit==1.0.165) (1.9.0)
Requirement already satisfied: kornia in d:\easydiffusion\installer_files\env\lib\site-packages (from k-diffusion->sdkit==1.0.165) (0.6.0)
Requirement already satisfied: resize-right in d:\easydiffusion\installer_files\env\lib\site-packages (from k-diffusion->sdkit==1.0.165) (0.0.2)
Requirement already satisfied: clean-fid in d:\easydiffusion\installer_files\env\lib\site-packages (from k-diffusion->sdkit==1.0.165) (0.1.35)
Requirement already satisfied: torchsde in d:\easydiffusion\installer_files\env\lib\site-packages (from k-diffusion->sdkit==1.0.165) (0.2.5)
Requirement already satisfied: torchdiffeq in d:\easydiffusion\installer_files\env\lib\site-packages (from k-diffusion->sdkit==1.0.165) (0.2.3)
Requirement already satisfied: wandb in d:\easydiffusion\installer_files\env\lib\site-packages (from k-diffusion->sdkit==1.0.165) (0.13.10)
Requirement already satisfied: certifi>=2017.4.17 in d:\easydiffusion\installer_files\env\lib\site-packages (from requests->sdkit==1.0.165) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\easydiffusion\installer_files\env\lib\site-packages (from requests->sdkit==1.0.165) (2.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from requests->sdkit==1.0.165) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in d:\easydiffusion\installer_files\env\lib\site-packages (from requests->sdkit==1.0.165) (3.4)
Requirement already satisfied: future in d:\easydiffusion\installer_files\env\lib\site-packages (from basicsr>=1.4.2->gfpgan->sdkit==1.0.165) (0.18.3)
Requirement already satisfied: addict in d:\easydiffusion\installer_files\env\lib\site-packages (from basicsr>=1.4.2->gfpgan->sdkit==1.0.165) (2.4.0)
Requirement already satisfied: filterpy in d:\easydiffusion\installer_files\env\lib\site-packages (from facexlib>=0.2.5->gfpgan->sdkit==1.0.165) (1.4.5)
Requirement already satisfied: numba in d:\easydiffusion\installer_files\env\lib\site-packages (from facexlib>=0.2.5->gfpgan->sdkit==1.0.165) (0.56.4)
Requirement already satisfied: fsspec in d:\easydiffusion\installer_files\env\lib\site-packages (from huggingface-hub->controlnet-aux==0.0.6->sdkit==1.0.165) (2023.1.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\easydiffusion\installer_files\env\lib\site-packages (from huggingface-hub->controlnet-aux==0.0.6->sdkit==1.0.165) (4.5.0)
Requirement already satisfied: colorama in d:\easydiffusion\installer_files\env\lib\site-packages (from tqdm->gfpgan->sdkit==1.0.165) (0.4.6)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from transformers~=4.25->compel==2.0.1->sdkit==1.0.165) (0.12.1)
Requirement already satisfied: ftfy in d:\easydiffusion\installer_files\env\lib\site-packages (from clip-anytorch->k-diffusion->sdkit==1.0.165) (6.1.1)
Requirement already satisfied: zipp>=0.5 in d:\easydiffusion\installer_files\env\lib\site-packages (from importlib-metadata->controlnet-aux==0.0.6->sdkit==1.0.165) (3.14.0)
Requirement already satisfied: jsonschema>2.4.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from jsonmerge->k-diffusion->sdkit==1.0.165) (4.17.3)
Requirement already satisfied: networkx>=2.2 in d:\easydiffusion\installer_files\env\lib\site-packages (from scikit-image->controlnet-aux==0.0.6->sdkit==1.0.165) (3.0)
Requirement already satisfied: tifffile>=2019.7.26 in d:\easydiffusion\installer_files\env\lib\site-packages (from scikit-image->controlnet-aux==0.0.6->sdkit==1.0.165) (2023.2.3)
Requirement already satisfied: imageio>=2.4.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from scikit-image->controlnet-aux==0.0.6->sdkit==1.0.165) (2.25.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (0.4.6)
Requirement already satisfied: google-auth<3,>=1.6.3 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (2.16.1)
Requirement already satisfied: werkzeug>=1.0.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (2.2.3)
Requirement already satisfied: grpcio>=1.48.2 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (1.51.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (1.8.1)
Requirement already satisfied: protobuf>=3.19.6 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (4.22.0)
Requirement already satisfied: absl-py>=0.4 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (1.4.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (0.7.0)
Requirement already satisfied: wheel>=0.26 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (0.38.4)
Requirement already satisfied: setuptools>=41.0.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (67.3.2)
Requirement already satisfied: markdown>=2.6.8 in d:\easydiffusion\installer_files\env\lib\site-packages (from tb-nightly->gfpgan->sdkit==1.0.165) (3.4.1)
Requirement already satisfied: boltons>=20.2.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from torchsde->k-diffusion->sdkit==1.0.165) (23.0.0)
Requirement already satisfied: trampoline>=0.1.2 in d:\easydiffusion\installer_files\env\lib\site-packages (from torchsde->k-diffusion->sdkit==1.0.165) (0.1.2)
Requirement already satisfied: pathtools in d:\easydiffusion\installer_files\env\lib\site-packages (from wandb->k-diffusion->sdkit==1.0.165) (0.1.2)
Requirement already satisfied: Click!=8.0.0,>=7.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from wandb->k-diffusion->sdkit==1.0.165) (8.1.3)
Requirement already satisfied: docker-pycreds>=0.4.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from wandb->k-diffusion->sdkit==1.0.165) (0.4.0)
Requirement already satisfied: setproctitle in d:\easydiffusion\installer_files\env\lib\site-packages (from wandb->k-diffusion->sdkit==1.0.165) (1.3.2)
Requirement already satisfied: appdirs>=1.4.3 in d:\easydiffusion\installer_files\env\lib\site-packages (from wandb->k-diffusion->sdkit==1.0.165) (1.4.4)
Requirement already satisfied: GitPython>=1.0.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from wandb->k-diffusion->sdkit==1.0.165) (3.1.31)
Requirement already satisfied: sentry-sdk>=1.0.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from wandb->k-diffusion->sdkit==1.0.165) (1.15.0)
Requirement already satisfied: six>=1.4.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from docker-pycreds>=0.4.0->wandb->k-diffusion->sdkit==1.0.165) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from GitPython>=1.0.0->wandb->k-diffusion->sdkit==1.0.165) (4.0.10)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->gfpgan->sdkit==1.0.165) (5.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in d:\easydiffusion\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->gfpgan->sdkit==1.0.165) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from google-auth<3,>=1.6.3->tb-nightly->gfpgan->sdkit==1.0.165) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tb-nightly->gfpgan->sdkit==1.0.165) (1.3.1)
Requirement already satisfied: attrs>=17.4.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from jsonschema>2.4.0->jsonmerge->k-diffusion->sdkit==1.0.165) (22.2.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in d:\easydiffusion\installer_files\env\lib\site-packages (from jsonschema>2.4.0->jsonmerge->k-diffusion->sdkit==1.0.165) (1.3.10)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from jsonschema>2.4.0->jsonmerge->k-diffusion->sdkit==1.0.165) (0.19.3)
Requirement already satisfied: importlib-resources>=1.4.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from jsonschema>2.4.0->jsonmerge->k-diffusion->sdkit==1.0.165) (5.12.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from werkzeug>=1.0.1->tb-nightly->gfpgan->sdkit==1.0.165) (2.1.2)
Requirement already satisfied: matplotlib in d:\easydiffusion\installer_files\env\lib\site-packages (from filterpy->facexlib>=0.2.5->gfpgan->sdkit==1.0.165) (3.7.0)
Requirement already satisfied: wcwidth>=0.2.5 in d:\easydiffusion\installer_files\env\lib\site-packages (from ftfy->clip-anytorch->k-diffusion->sdkit==1.0.165) (0.2.6)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in d:\easydiffusion\installer_files\env\lib\site-packages (from numba->facexlib>=0.2.5->gfpgan->sdkit==1.0.165) (0.39.1)
Requirement already satisfied: smmap<6,>=3.0.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb->k-diffusion->sdkit==1.0.165) (5.0.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in d:\easydiffusion\installer_files\env\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tb-nightly->gfpgan->sdkit==1.0.165) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tb-nightly->gfpgan->sdkit==1.0.165) (3.2.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from matplotlib->filterpy->facexlib>=0.2.5->gfpgan->sdkit==1.0.165) (1.0.7)
Requirement already satisfied: python-dateutil>=2.7 in d:\easydiffusion\installer_files\env\lib\site-packages (from matplotlib->filterpy->facexlib>=0.2.5->gfpgan->sdkit==1.0.165) (2.8.2)
Requirement already satisfied: cycler>=0.10 in d:\easydiffusion\installer_files\env\lib\site-packages (from matplotlib->filterpy->facexlib>=0.2.5->gfpgan->sdkit==1.0.165) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\easydiffusion\installer_files\env\lib\site-packages (from matplotlib->filterpy->facexlib>=0.2.5->gfpgan->sdkit==1.0.165) (1.4.4)
Requirement already satisfied: fonttools>=4.22.0 in d:\easydiffusion\installer_files\env\lib\site-packages (from matplotlib->filterpy->facexlib>=0.2.5->gfpgan->sdkit==1.0.165) (4.38.0)
Installing collected packages: safetensors, invisible-watermark, timm, diffusers, controlnet-aux, compel, sdkit
  Attempting uninstall: safetensors
    Found existing installation: safetensors 0.2.8
    Uninstalling safetensors-0.2.8:
      Successfully uninstalled safetensors-0.2.8
  Attempting uninstall: diffusers
    Found existing installation: diffusers 0.15.1
    Uninstalling diffusers-0.15.1:
      Successfully uninstalled diffusers-0.15.1
  Attempting uninstall: compel
    Found existing installation: compel 1.1.5
    Uninstalling compel-1.1.5:
      Successfully uninstalled compel-1.1.5
  Attempting uninstall: sdkit
    Found existing installation: sdkit 1.0.112
    Uninstalling sdkit-1.0.112:
      Successfully uninstalled sdkit-1.0.112
Successfully installed compel-2.0.1 controlnet-aux-0.0.6 diffusers-0.19.2 invisible-watermark-0.2.0 safetensors-0.3.1 sdkit-1.0.165 timm-0.9.2
sdkit: 1.0.165
> python -m pip install --upgrade stable-diffusion-sdkit==2.1.4
Requirement already satisfied: stable-diffusion-sdkit==2.1.4 in d:\easydiffusion\installer_files\env\lib\site-packages (2.1.4)
stable-diffusion-sdkit: None
> python -m pip install --upgrade rich==12.6.0
Requirement already satisfied: rich==12.6.0 in d:\easydiffusion\installer_files\env\lib\site-packages (12.6.0)
> python -m pip install --upgrade uvicorn==0.19.0
Requirement already satisfied: uvicorn==0.19.0 in d:\easydiffusion\installer_files\env\lib\site-packages (0.19.0)
> python -m pip install --upgrade fastapi==0.85.1
Requirement already satisfied: fastapi==0.85.1 in d:\easydiffusion\installer_files\env\lib\site-packages (0.85.1)
> python -m pip install --upgrade pycloudflared==0.2.0
Requirement already satisfied: pycloudflared==0.2.0 in d:\easydiffusion\installer_files\env\lib\site-packages (0.2.0)

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=D:\EasyDiffusion\installer_files\env\lib\site-packages
D:\EasyDiffusion\installer_files\env\python.exe
C:\Users\Evgeniy\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\Evgeniy\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
Traceback (most recent call last):
  File "D:\EasyDiffusion\installer_files\env\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\EasyDiffusion\installer_files\env\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\EasyDiffusion\installer_files\env\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\__init__.py", line 1, in <module>
    from uvicorn.config import Config
ValueError: source code string cannot contain null bytes

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by cmdr2** [comment]
Hi, sorry for the delay. Can you please restart Easy Diffusion and try again?
