### ISSUE TITLE
Can't run Stable Diffusion at the second try

### ISSUE THREAD

**Issue by Vndtta22a** [easydiffusion/easydiffusion#1517]
I used stable diffusion all OK last night now i tried to initiate it and it won't do
this is the prompt:

Install dir: C:\EasyDiffusion\
C:\EasyDiffusion\installer_files\env\Library\bin\git.exe
git version 2.42.0.windows.1
C:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
C:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1
.
COMSPEC=C:\WINDOWS\system32\cmd.exe

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from main.."
HEAD is now at ab8f10ae Update FUNDING.yml
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
508 archivo(s) copiado(s)
        1 archivo(s) copiado(s).
        1 archivo(s) copiado(s).
        1 archivo(s) copiado(s).
        1 archivo(s) copiado(s).
        1 archivo(s) copiado(s).
        1 archivo(s) copiado(s).
        1 archivo(s) copiado(s).
        1 archivo(s) copiado(s).
        1 archivo(s) copiado(s).
        1 archivo(s) copiado(s).
Ya existe el subdirectorio o el archivo tmp.
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
> python -m pip install --upgrade sdkit==1.0.165 -q
  error: subprocess-exited-with-error

  × Building wheel for safetensors (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\safetensors
      copying py_src\safetensors\flax.py -> build\lib.win-amd64-cpython-38\safetensors
      copying py_src\safetensors\numpy.py -> build\lib.win-amd64-cpython-38\safetensors
      copying py_src\safetensors\paddle.py -> build\lib.win-amd64-cpython-38\safetensors
      copying py_src\safetensors\tensorflow.py -> build\lib.win-amd64-cpython-38\safetensors
      copying py_src\safetensors\torch.py -> build\lib.win-amd64-cpython-38\safetensors
      copying py_src\safetensors\__init__.py -> build\lib.win-amd64-cpython-38\safetensors
      running build_ext
      running build_rust
      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for safetensors
ERROR: Could not build wheels for safetensors, which is required to install pyproject.toml-based projects
sdkit: 1.0.43
stable-diffusion-sdkit: 2.1.4

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
C:\EasyDiffusion\installer_files\env\python.exe
C:\Users\Adriel\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Program Files\Inkscape\bin\python.exe
Python 3.8.5
Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\EasyDiffusion\installer_files\env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\__main__.py", line 4, in <module>
    uvicorn.main()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\config.py", line 474, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\EasyDiffusion\installer_files\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\EasyDiffusion\ui\main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 7, in <module>
    from easydiffusion import app
  File "C:\EasyDiffusion\ui\easydiffusion\app.py", line 14, in <module>
    from easydiffusion import task_manager
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 20, in <module>
    from easydiffusion.tasks import Task
  File "C:\EasyDiffusion\ui\easydiffusion\tasks\__init__.py", line 2, in <module>
    from .render_images import RenderTask
  File "C:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 12, in <module>
    from sdkit.utils import (
ImportError: cannot import name 'diffusers_latent_samples_to_images' from 'sdkit.utils' (C:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\__init__.py)
Presione una tecla para continuar . . .

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 22H2
 - Browser: Google Chrome

**Comment by JeLuF** [comment]
The wheel files for the new safetensors release aren't available (yet?).
Not sure why exactly pip wants to upgrade safetensors. The installer should already come with a version of it.

**Comment by JeLuF** [comment]
@Vndtta22a Thank you for reporting this issue!

cmdr2 just pushed a hotfix for this. Can you please restart the `Start Stable Diffusion UI.cmd` script?

**Comment by cmdr2** [comment]
Thanks for reporting, this was fixed last week. Please try again and feel free to reopen if this continues to be a problem.
