### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by dreamsxin** [easydiffusion/easydiffusion#1590]
**Describe the bug**

Clicking the `+ Embedding` button above the prompt box, when happen error:
```log
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\EasyDiffusion\ui\easydiffusion\bucket_manager.py", line 63, in bucket_get_object
    return Response(content=bucketfile.data, media_type=MIME_TYPES.get(suffix, "application/octet-stream"))
AttributeError: 'NoneType' object has no attribute 'data'
```

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome

**Comment by cmdr2** [comment]
Hi, this has been fixed in the latest beta. Please restart Easy Diffusion and try again. Thanks for reporting!
