### ISSUE TITLE
IndexError: index 1 is out of bounds for dimension 0 with size 1

### ISSUE THREAD

**Issue by dreamsxin** [easydiffusion/easydiffusion#1594]
**Describe the bug**

IMG2IMG, 
Inpainting, 
mask file,
```txt
Seed: 3885573451, 
Dimensions: 512x768, 
Sampler: dpmpp_sde, 
Inference Steps: 30, 
Guidance Scale: 7, 
Model: sd-v1-5, 
Clip Skip: yes, 
Negative Prompt: [:EasyNegative:0.25], extra fingers,fewer fingers,
Prompt Strength: 0.8, 
Preserve Color Profile: false, 
Strict Mask Border: false
```
```log
19:15:54.723 ERROR cuda:0 Traceback (most recent call last):                                                                                                                                task_manager.py:292
  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "D:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 92, in run
    self.response = make_images(
  File "D:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 152, in make_images
    images, seeds = make_images_internal(
  File "D:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 197, in make_images_internal
    images, user_stopped = generate_images_internal(
  File "D:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 281, in generate_images_internal
    images = generate_images(context, callback=callback, **req.dict())
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py", line 71, in generate_images
    return make_with_diffusers(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\generate\image_generator.py", line 457, in make_with_diffusers
    images = operation_to_apply(**cmd).images
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion_inpaint_legacy.py", line 711, in __call__
    init_latents_proper = self.scheduler.add_noise(init_latents_orig, noise, torch.tensor())
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\diffusers\schedulers\scheduling_dpmsolver_sde.py", line 513, in add_noise
    step_indices =
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\diffusers\schedulers\scheduling_dpmsolver_sde.py", line 513, in <listcomp>
    step_indices =
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\diffusers\schedulers\scheduling_dpmsolver_sde.py", line 220, in index_for_timestep
    return indices.item()
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome
 - GPU Memory: 2G

切换成 A模式 之后，一切正常
After switch to `Euler a` Sampler, everything is normal.

**Comment by ac2323** [comment]
I had this issue as well. It's likely you don't have enough VRAM. Try lowering your setting or restarting EasyDiffusion.

**Comment by dreamsxin** [comment]
Thks
