### ISSUE TITLE
ERROR cuda:0 'encoder.conv_in.weight'   

### ISSUE THREAD

**Issue by dreamsxin** [easydiffusion/easydiffusion#1610]
**Describe the bug**
Load model `anihelloy2dmwv10` error
```log
07:58:17.904 INFO cuda:0 using config: D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml                                                  __init__.py:176
07:58:17.920 INFO cuda:0 using attn_precision: fp16                                                                                                                                             __init__.py:192
07:58:18.622 ERROR cuda:0 'encoder.conv_in.weight'                                                                                                                                         model_manager.py:185
Traceback (most recent call last):
  File "D:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 181, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line 46, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 86, in load_model
    return load_diffusers_model(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 238, in load_diffusers_model
    default_pipe = download_from_original_stable_diffusion_ckpt(state_dict, **model_load_params)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\diffusers_bugfixes.py", line 411, in download_from_original_stable_diffusion_ckpt
    converted_vae_checkpoint = convert_ldm_vae_checkpoint(checkpoint, vae_config)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 632, in convert_ldm_vae_checkpoint
    new_checkpoint["encoder.conv_in.weight"] = vae_state_dict["encoder.conv_in.weight"]
KeyError: 'encoder.conv_in.weight'
07:58:18.937 ERROR cuda:0 Traceback (most recent call last):                                                                                                                                task_manager.py:292
  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "D:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 89, in run
    model_manager.fail_if_models_did_not_load(context)
  File "D:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 212, in fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: 'encoder.conv_in.weight'

07:58:19.040 INFO cuda:0 Session 1695858600685 task 1818750298000 failed!                                                                                                                   task_manager.py:302
```

**Comment by cmdr2** [comment]
Thanks for reporting this. Interesting, we'd fixed this bug in the past, but I think the fix got removed recently.

The root cause (if I recall) is that some models don't include a VAE, which is why it fails to find a key (that's present in the VAE).

The fix that was used previously was to skip missing keys, but I think that fix got reverted somehow recently. Will check.

**Comment by Kyr4l** [comment]
is there a way  to apply the fix manually again ?

**Comment by jagan607** [comment]
Hi, was this fixed?
