### ISSUE TITLE
Error: Could not load the stable-diffusion model! Reason: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by dreamsxin** [easydiffusion/easydiffusion#1612]
**Describe the bug**
Model type SDXL
```log
08:26:10.854 INFO cuda:0 using config: D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\sd-xl-base-1.0.yaml                                                __init__.py:176
08:26:10.879 INFO cuda:0 using attn_precision: fp16                                                                                                                                             __init__.py:192
08:26:42.548 ERROR cuda:0 Expecting value: line 1 column 1 (char 0)                                                                                                                        model_manager.py:185
Traceback (most recent call last):
  File "D:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 181, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line 46, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 86, in load_model
    return load_diffusers_model(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 238, in load_diffusers_model
    default_pipe = download_from_original_stable_diffusion_ckpt(state_dict, **model_load_params)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\diffusers_bugfixes.py", line 594, in download_from_original_stable_diffusion_ckpt
    tokenizer_2 = CLIPTokenizer.from_pretrained(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 1975, in _from_pretrained
    special_tokens_map = json.load(special_tokens_map_handle)
  File "D:\EasyDiffusion\installer_files\env\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\EasyDiffusion\installer_files\env\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\EasyDiffusion\installer_files\env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\EasyDiffusion\installer_files\env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
08:26:45.508 ERROR cuda:0 Traceback (most recent call last):                                                                                                                                task_manager.py:292
  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "D:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 89, in run
    model_manager.fail_if_models_did_not_load(context)
  File "D:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 212, in fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: Expecting value: line 1 column 1 (char 0)

08:26:46.410 INFO cuda:0 Session 1695946976718 task 2453325910416 failed!                                                                                                                   task_manager.py:302
```

**Comment by dreamsxin** [comment]
It's likely don't have enough VRAM.

**Comment by cmdr2** [comment]
Hi @dreamsxin That doesn't look like a VRAM issue. I see a JSON parsing error for the CLIP Tokenizer, so probably the CLIPTokenizer model hasn't downloaded properly.

Can you please try starting Easy Diffusion again, and use the SDXL Base model and try again? Does it fail? Thanks

**Comment by dreamsxin** [comment]
@cmdr2 Same error
```log
__init__.py:48D:\EasyDiffusion\models\stable-diffusion\majicmixSombre_v20.safetensors to device: cuda:0
14:47:41.881 INFO cuda:0 Session 1695970036113 starting task 2454774252640 on NVIDIA GeForce GTX 950 task_manager.py:28014:47:42.180 INFO cuda:0 unloaded stable-diffusion model from device: cuda:0                              __init__.py:7914:47:42.182 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:44D:\EasyDiffusion\models\stable-diffusion\dynavisionXLAllInOneStylized_release0534bakedvae.safetensors to
device: cuda:0
14:47:43.480 INFO cuda:0 loading on diffusers                                                            __init__.py:17414:47:43.481 INFO cuda:0 using config:                                                                   __init__.py:176D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\sd-xl-base-1.0.yam
l
14:47:43.505 INFO cuda:0 using attn_precision: fp16                                                      __init__.py:192
14:48:13.858 ERROR cuda:0 Expecting value: line 1 column 1 (char 0)                                                                                                                        model_manager.py:185
Traceback (most recent call last):
  File "D:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 181, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line 46, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 86, in load_model
    return load_diffusers_model(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 238, in load_diffusers_model
    default_pipe = download_from_original_stable_diffusion_ckpt(state_dict, **model_load_params)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\diffusers_bugfixes.py", line 594, in download_from_original_stable_diffusion_ckpt
    tokenizer_2 = CLIPTokenizer.from_pretrained(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 1804, in from_pretrained
    return cls._from_pretrained(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 1975, in _from_pretrained
    special_tokens_map = json.load(special_tokens_map_handle)
  File "D:\EasyDiffusion\installer_files\env\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\EasyDiffusion\installer_files\env\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\EasyDiffusion\installer_files\env\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\EasyDiffusion\installer_files\env\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
14:48:24.033 ERROR cuda:0 Traceback (most recent call last):                                                                                                                                task_manager.py:292
  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "D:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 89, in run
    model_manager.fail_if_models_did_not_load(context)
  File "D:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 212, in fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: Expecting value: line 1 column 1 (char 0)

14:48:24.706 INFO cuda:0 Session 1695970036113 task 2454774252640 failed!                                                                                                                   task_manager.py:302
```
