### ISSUE TITLE
Error: Could not load the stable-diffusion model! Reason: 'Attention' object has no attribute 'to_to_k'

### ISSUE THREAD

**Issue by dreamsxin** [easydiffusion/easydiffusion#1618]
**Describe the bug**
```log
20:23:03.770 INFO cuda:0 loading stable-diffusion model from D:\EasyDiffusion\models\stable-diffusion\weakenedUnity_v20.safetensors to device: cuda:0                                            __init__.py:44
20:23:03.983 INFO cuda:0 loading on diffusers                                                                                                                                                   __init__.py:174
20:23:03.983 INFO cuda:0 using config: D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\models_db\configs\v1-inference.yaml                                                  __init__.py:176
20:23:04.000 INFO cuda:0 using attn_precision: fp16                                                                                                                                             __init__.py:192
20:23:04.820 ERROR cuda:0 'Attention' object has no attribute 'to_to_k'                                                                                                                    model_manager.py:185
Traceback (most recent call last):
  File "D:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 181, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line 46, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 86, in load_model
    return load_diffusers_model(
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init__.py", line 238, in load_diffusers_model
    default_pipe = download_from_original_stable_diffusion_ckpt(state_dict, **model_load_params)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\diffusers_bugfixes.py", line 430, in download_from_original_stable_diffusion_ckpt
    set_module_tensor_to_device(vae, param_name, "cpu", value=param)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 124, in set_module_tensor_to_device
    new_module = getattr(module, split)
  File "D:\EasyDiffusion\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Attention' object has no attribute 'to_to_k'
20:23:05.207 ERROR cuda:0 Traceback (most recent call last):                                                                                                                                task_manager.py:292
  File "D:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "D:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 89, in run
    model_manager.fail_if_models_did_not_load(context)
  File "D:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 212, in fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: 'Attention' object has no attribute 'to_to_k'

20:23:05.318 INFO cuda:0 Session 1696249338437 task 1586069113344 failed!                                                                                                                   task_manager.py:302
```

**Comment by dreamsxin** [comment]
https://github.com/huggingface/diffusers/issues/4790
