### ISSUE TITLE
Fails to run after installing

### ISSUE THREAD

**Issue by Chadt54** [easydiffusion/easydiffusion#1632]
**Describe the bug**
I ran the installer, and get this error on Windows 11

**To Reproduce**
1. Install this: https://github.com/easydiffusion/easydiffusion/releases/download/v3.0.2/Easy-Diffusion-Windows.exe
2. Get this:
`Easy Diffusion installation complete, starting the server!

PYTHONPATH=C:\EasyDiffusion\installer_files\env\lib\site-packages
Python:  C:\EasyDiffusion\installer_files\env\python.EXE
Version: 3.8.5
Checking network settings
Set listen port to  9000
Set bind_ip to  0.0.0.0

Launching uvicorn

Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\EasyDiffusion\installer_files\env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\__main__.py", line 4, in <module>
    uvicorn.main()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 404, in main
    run(
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\EasyDiffusion\installer_files\env\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\config.py", line 474, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\EasyDiffusion\installer_files\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\EasyDiffusion\ui\main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server, bucket_manager
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 7, in <module>
    from easydiffusion import app
  File "C:\EasyDiffusion\ui\easydiffusion\app.py", line 14, in <module>
    from easydiffusion import task_manager
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 18, in <module>
    import torch
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\EasyDiffusion\installer_files\env\lib\site-packages\torch\lib\torch_cuda_cpp.dll" or one of its dependencies.
Press any key to continue . . .`
**Expected behavior**

**Screenshots**
![image](https://github.com/easydiffusion/easydiffusion/assets/1322965/2c24bd4f-9cdf-47c3-adfc-ec54f15794ba)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by cmdrgrunt** [comment]
Are you still experiencing this issue?

**Comment by Chadt54** [comment]
I don't know, cause I switched over to installing it in a docker container instead and it worked there so I just moved on.
