### ISSUE TITLE
MAJOR BUG - Erasing 50Go with all my MODELS and other embeddings ..etc at start

### ISSUE THREAD

**Issue by AkoZ** [easydiffusion/easydiffusion#1660]
EDIT : strangely and chance too ! .. my drives have been inversed .. also my X: becomes Y:
and where i pointed was not the right dir !!
but even i have so much chance , the BUG can be fairly reproduced
- i try once more NOW 16:28 with a fake dir .. to confirm

**My Models placed in a shared directory ARE ERASED !**
When i start i indicate my models and other things as lora or embeddings etc ..
in the config.yaml file and it erased the shared directory with all its content ! ??

**To Reproduce**
1. create a test directory as D:\fastmodels1
2. put any .safetensors or may be near any file inside
3. modify the config.yaml file at its last line "models_dir: D:\fastmodels1" - which for me was the way to point to my shared directory ...
4. Start Stable Diffusion UI.cmd
5. HERE all in D:\fastmodels1 **has been erased**

**Expected behavior**
To just use my shared dir and really .. an don't want to lose my files  !

**Screenshots**
no use .. problem from starter and this config.yaml which in fact ERASE all what's inside

**Desktop (please complete the following information):**
 - OS: windows11
 - Browser: last bing ..edge

here about versions and what happened:
`git version 2.38.1.windows.1
c:\SD15B\EZsd\installer_files\env\Library\bin\conda.bat
c:\SD15B\EZsd\installer_files\env\Scripts\conda.exe
conda 23.1.0
.
COMSPEC=C:\WINDOWS\system32\cmd.exe
'wmic' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

"Easy Diffusion - v3"

"Easy Diffusion's git repository was already installed. Updating from main.."
No local changes to save
HEAD is now at bedf176e Merge pull request #1630 from easydiffusion/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
519 fichier(s) copié(s)
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
        1 fichier(s) copié(s).
Un sous-répertoire ou un fichier tmp existe déjà.
PYTHONPATH=c:\SD15B\EZsd\installer_files\env\lib\site-packages
c:\SD15B\EZsd\installer_files\env\python.exe
C:\Users\ONE\AppData\Local\Programs\Python\Python310\python.exe
Python 3.8.5
torch: 1.13.1+cu116
torchvision: 0.14.1+cu116
sdkit: 2.0.15
stable-diffusion-sdkit: 2.1.5
{'model': {'stable-diffusion': 'woopwoopPhoto_12st',
           'vae': 'vae-ft-mse-840000-ema-pruned'},
 'models_dir': 'L:\\SD15b\\_FastStartMODels2TSTErase',
 'net': {'listen_port': 9000, 'listen_to_network': True},
 'render_devices': 'auto',
 'test_diffusers': False,
 'ui': {'open_browser_on_start': False},
 'update_branch': 'main',
 'use_v3_engine': True,
 'vram_usage_level': 'high'}

Easy Diffusion installation complete, starting the server!

PYTHONPATH=c:\SD15B\EZsd\installer_files\env\lib\site-packages
Python:  c:\SD15B\EZsd\installer_files\env\python.EXE
Version: 3.8.5
Checking network settings
Set listen port to  9000
Set bind_ip to  0.0.0.0

Launching uvicorn

Cancelling an overlapped future failed
future: <_OverlappedFuture pending overlapped=<pending, 0x227795ac820> cb=[BaseProactorEventLoop._loop_self_reading()]>
Traceback (most recent call last):
  File "c:\SD15B\EZsd\installer_files\env\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\SD15B\EZsd\installer_files\env\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\SD15B\EZsd\installer_files\env\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\SD15B\EZsd\installer_files\env\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\SD15B\EZsd\installer_files\env\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\SD15B\EZsd\installer_files\env\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\SD15B\EZsd\installer_files\env\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "c:\SD15B\EZsd\installer_files\env\lib\site-packages\uvicorn\config.py", line 474, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\SD15B\EZsd\installer_files\env\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\SD15B\EZsd\installer_files\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\SD15B\EZsd\ui\main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server, bucket_manager
  File "c:\SD15B\EZsd\ui\easydiffusion\model_manager.py", line 7, in <module>
    from easydiffusion import app
  File "c:\SD15B\EZsd\ui\easydiffusion\app.py", line 14, in <module>
    from easydiffusion import task_manager
  File "c:\SD15B\EZsd\ui\easydiffusion\task_manager.py", line 18, in <module>
    import torch
  File "c:\SD15B\EZsd\installer_files\env\lib\site-packages\torch\__init__.py", line 123, in <module>
    res = kernel32.LoadLibraryExW(dll, None, 0x00001100)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\SD15B\EZsd\installer_files\env\lib\asyncio\windows_events.py", line 66, in _cancel_overlapped
    self._ov.cancel()
OSError: [WinError 6] Descripteur non valide

Aborted!
Traceback (most recent call last):
`

**Comment by AkoZ** [comment]
what to say ? .. i really don't understand why goog  added letter W: may have pushed my shared drive as X: became its Y: ??
