### ISSUE TITLE
Error: Could not load the stable-diffusion model! Reason: Error while deserializing header: HeaderTooSmall

### ISSUE THREAD

**Issue by CK-Cheung-CK** [easydiffusion/easydiffusion#1663]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by 1623275623** [comment]
When I open the application first time and click make image button. the error was output in console screen. 
 
Desktop: 
* OS: Windows 10 Pro N
* Browser: Edge
* Processor: AMD Ryzen 5 3600 6-Core

Console Messages:
```
Install dir: H:\EasyDiffusion\
H:\EasyDiffusion\installer_files\env\Library\bin\git.exe
E:\Software\Git\Git\cmd\git.exe
git version 2.42.0.windows.1
H:\EasyDiffusion\installer_files\env\Library\bin\conda.bat
H:\EasyDiffusion\installer_files\env\Scripts\conda.exe
conda 23.7.3
.
COMSPEC=C:\WINDOWS\system32\cmd.exe
AdapterRAM  DriverDate                 DriverVersion  Name
4293918720  20230608000000.000000-000  31.0.15.3623   NVIDIA GeForce GTX 1660 Ti


"Easy Diffusion - v3"

"Easy Diffusion's git repository was already installed. Updating from main.."
No local changes to save
HEAD is now at dfb26ed7 Merge pull request #1702 from easydiffusion/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
519 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.
PYTHONPATH=H:\EasyDiffusion\installer_files\env\lib\site-packages
H:\EasyDiffusion\installer_files\env\python.exe
C:\Users\58\AppData\Local\Microsoft\WindowsApps\python.exe
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\python.exe
Python 3.8.5
torch: 2.0.1+cu117
torchvision: 0.15.2+cu117
> python -m pip install --upgrade sdkit==2.0.15 -q
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/sdkit/
ERROR: Could not find a version that satisfies the requirement sdkit==2.0.15 (from versions: none)
ERROR: No matching distribution found for sdkit==2.0.15
WARNING! Tried to install sdkit==2.0.15, but the version is still 2.0.4!
sdkit: 2.0.4
> python -m pip install --upgrade stable-diffusion-sdkit==2.1.5
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))': /simple/stable-diffusion-sdkit/
ERROR: Could not find a version that satisfies the requirement stable-diffusion-sdkit==2.1.5 (from versions: none)
ERROR: No matching distribution found for stable-diffusion-sdkit==2.1.5
WARNING! Tried to install stable-diffusion-sdkit==2.1.5, but the version is still 2.1.4!
stable-diffusion-sdkit: 2.1.4
{'model': {'stable-diffusion': 'sd-v1-5'},
 'net': {'listen_port': 9000, 'listen_to_network': False},
 'render_devices': 'auto',
 'test_diffusers': True,
 'ui': {'open_browser_on_start': True},
 'update_branch': 'main',
 'vram_usage_level': 'high'}


Easy Diffusion installation complete, starting the server!


PYTHONPATH=H:\EasyDiffusion\installer_files\env\lib\site-packages
Python:  H:\EasyDiffusion\installer_files\env\python.EXE
Version: 3.8.5
Checking network settings
Set listen port to  9000

Launching uvicorn

19:12:52.028 INFO MainThread started in H:\EasyDiffusion\stable-diffusion                                   server.py:31
19:12:52.033 INFO MainThread started at 12/30/23 19:12:52                                                   server.py:32
> download stable-diffusion 1.5-pruned-emaonly-fp16
19:12:52.372 ERROR MainThread HTTPSConnectionPool(host='github.com', port=443): Max retries       model_downloader.py:70
exceeded with url: /easydiffusion/sdkit-test-data/releases/download/assets/sd-v1-5.safetensors
(Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
711, in urlopen
    self._prepare_proxy(conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
1007, in _prepare_proxy
    conn.connect()
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 369,
in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 504,
in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 453,
in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 495,
in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 486,
in send
    resp = conn.urlopen(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
798, in urlopen
    retries = retries.increment(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 592,
in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries
exceeded with url: /easydiffusion/sdkit-test-data/releases/download/assets/sd-v1-5.safetensors
(Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_downloader.py",
line 64, in download_model
    download_file(model_url, out_path)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\http_utils.py", line
19, in download_file
    res = requests.get(url, stream=True)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 59, in
request
    return session.request(method=method, url=url, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 589,
in request
    resp = self.send(prep, **send_kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 703,
in send
    r = adapter.send(request, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 513,
in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='github.com', port=443): Max retries
exceeded with url: /easydiffusion/sdkit-test-data/releases/download/assets/sd-v1-5.safetensors
(Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
stable-diffusion model(s) found.
> download gfpgan 1.4
19:12:52.430 ERROR MainThread HTTPSConnectionPool(host='github.com', port=443): Max retries       model_downloader.py:70
exceeded with url: /TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
711, in urlopen
    self._prepare_proxy(conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
1007, in _prepare_proxy
    conn.connect()
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 369,
in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 504,
in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 453,
in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 495,
in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 486,
in send
    resp = conn.urlopen(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
798, in urlopen
    retries = retries.increment(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 592,
in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries
exceeded with url: /TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_downloader.py",
line 64, in download_model
    download_file(model_url, out_path)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\http_utils.py", line
19, in download_file
    res = requests.get(url, stream=True)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 59, in
request
    return session.request(method=method, url=url, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 589,
in request
    resp = self.send(prep, **send_kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 703,
in send
    r = adapter.send(request, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 513,
in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='github.com', port=443): Max retries
exceeded with url: /TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
gfpgan model(s) found.
> download realesrgan x4plus
19:12:52.482 ERROR MainThread HTTPSConnectionPool(host='github.com', port=443): Max retries       model_downloader.py:70
exceeded with url: /xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
711, in urlopen
    self._prepare_proxy(conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
1007, in _prepare_proxy
    conn.connect()
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 369,
in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 504,
in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 453,
in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 495,
in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 486,
in send
    resp = conn.urlopen(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
798, in urlopen
    retries = retries.increment(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 592,
in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries
exceeded with url: /xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_downloader.py",
line 64, in download_model
    download_file(model_url, out_path)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\http_utils.py", line
19, in download_file
    res = requests.get(url, stream=True)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 59, in
request
    return session.request(method=method, url=url, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 589,
in request
    resp = self.send(prep, **send_kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 703,
in send
    r = adapter.send(request, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 513,
in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='github.com', port=443): Max retries
exceeded with url: /xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
> download realesrgan x4plus_anime_6
19:12:52.532 ERROR MainThread HTTPSConnectionPool(host='github.com', port=443): Max retries       model_downloader.py:70
exceeded with url: /xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth
(Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
711, in urlopen
    self._prepare_proxy(conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
1007, in _prepare_proxy
    conn.connect()
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 369,
in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 504,
in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 453,
in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 495,
in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 486,
in send
    resp = conn.urlopen(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
798, in urlopen
    retries = retries.increment(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 592,
in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries
exceeded with url: /xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth
(Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_downloader.py",
line 64, in download_model
    download_file(model_url, out_path)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\http_utils.py", line
19, in download_file
    res = requests.get(url, stream=True)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 59, in
request
    return session.request(method=method, url=url, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 589,
in request
    resp = self.send(prep, **send_kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 703,
in send
    r = adapter.send(request, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 513,
in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='github.com', port=443): Max retries
exceeded with url: /xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_6B.pth
(Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
realesrgan model(s) found.
> download vae vae-ft-mse-840000-ema-pruned
19:12:52.582 ERROR MainThread HTTPSConnectionPool(host='huggingface.co', port=443): Max retries   model_downloader.py:70
exceeded with url:
/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
711, in urlopen
    self._prepare_proxy(conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
1007, in _prepare_proxy
    conn.connect()
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 369,
in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connection.py", line 504,
in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 453,
in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\ssl_.py", line 495,
in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "H:\EasyDiffusion\installer_files\env\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 486,
in send
    resp = conn.urlopen(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\connectionpool.py", line
798, in urlopen
    retries = retries.increment(
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\urllib3\util\retry.py", line 592,
in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max
retries exceeded with url:
/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_downloader.py",
line 64, in download_model
    download_file(model_url, out_path)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\http_utils.py", line
19, in download_file
    res = requests.get(url, stream=True)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\api.py", line 59, in
request
    return session.request(method=method, url=url, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 589,
in request
    resp = self.send(prep, **send_kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\sessions.py", line 703,
in send
    r = adapter.send(request, **kwargs)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\requests\adapters.py", line 513,
in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries
exceeded with url:
/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.ckpt (Caused by
ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
vae model(s) found.
19:12:52.794 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:408
19:12:52.802 INFO cuda:0 Device usage during initialization:                                               runtime.py:35
19:12:52.816 INFO cuda:0 CPU utilization: 12.1%, System RAM used: 14.5 of 15.9 GiB, GPU RAM used      memory_utils.py:47
(cuda:0): 1.0 of 6.0 GiB (peak: 0.0 GiB)
19:12:52.819 WARNING cuda:0 forcing full precision on this GPU, to avoid green images. GPU         device_manager.py:150
detected: NVIDIA GeForce GTX 1660 Ti
19:12:52.821 INFO cuda:0 Setting cuda:0 as active, with precision: full                            device_manager.py:154
19:12:53.348 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:44
H:\EasyDiffusion\models\stable-diffusion\sd-v1-5.safetensors to device: cuda:0
No module 'xformers'. Proceeding without it.
19:12:53.355 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:82
H:\EasyDiffusion\models\stable-diffusion\sd-v1-5.safetensors
19:12:53.357 ERROR cuda:0 Error while deserializing header: HeaderTooSmall                           model_manager.py:88
Traceback (most recent call last):
  File "H:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 73, in load_default_models
    load_model(
  File
"H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py", line
46, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File
"H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\_
_init__.py", line 55, in load_model
    sd = load_tensor_file(model_path)
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\file_utils.py", line 13,
in load_tensor_file
    return safetensors.torch.load_file(path, device="cpu")
  File "H:\EasyDiffusion\installer_files\env\lib\site-packages\safetensors\torch.py", line 308, in
load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall
19:12:53.811 INFO MainThread Opening browser..                                                                app.py:318
╭────────────────────────────────────────────── Easy Diffusion is ready ───────────────────────────────────────────────╮
│                                                                                                                      │
│ Easy Diffusion is ready to serve requests.                                                                           │
│                                                                                                                      │
│ A new browser tab should have been opened by now.                                                                    │
│ If not, please open your web browser and navigate to http://localhost:9000/                                          │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ERROR:    [Errno 10048] error while attempting to bind on address ('127.0.0.1', 9000): only one usage of each socket address (protocol/network address/port) is normally permitted
Press any key to continue . . .

```

When I turn off vpn the pip can't install sdkit. when i turn on error appear. can any one help me solve this problem.

**Comment by DingBangBang** [comment]
<img width="1082" alt="issue_image" src="https://github.com/easydiffusion/easydiffusion/assets/76546222/469ec7e2-b958-4fe9-9b0a-b31ea0a36864">
Yes we met this issue as well. It shows like this  as long as it opened this webpage.

Error: Could not load the stable-diffusion model! Reason: Error while deserializing header: HeaderTooSmall

Help me with this, plz. :-) Thank you so much!
