### ISSUE TITLE
Error: Could not load the stable-diffusion model! Reason: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14 is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

### ISSUE THREAD

**Issue by ffudeccej60724** [easydiffusion/easydiffusion#1699]
**Describe the bug**
Error: Could not load the stable-diffusion model! Reason: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14 is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

Prompt:
a photograph of an astronaut riding a horse
Model:
anime-pencil-diffusion-v1

Log:
Install dir: D:\SD\stable-diffusion-ui\
D:\SD\stable-diffusion-ui\installer_files\env\Library\bin\git.exe
D:\Program Files\Git\bin\git.exe
git version 2.39.0.windows.1
D:\SD\stable-diffusion-ui\installer_files\env\Library\bin\conda.bat
D:\SD\stable-diffusion-ui\installer_files\env\Scripts\conda.exe
conda 22.11.1
.
COMSPEC=C:\Windows\system32\cmd.exe

"Easy Diffusion - v2"

"Easy Diffusion's git repository was already installed. Updating from beta.."
HEAD is now at 8538a684 sdkit 1.0.153 - use TensorRT only if enabled in the UI
Already on 'beta'
Your branch is up to date with 'origin/beta'.
fatal: unable to access 'https://kgithub.com/cmdr2/stable-diffusion-ui.git/': Failed to connect to kgithub.com port 443 after 21078 ms: Couldn't connect to server
507 files were copied
1 file has been copied.
1 file has been copied.
1 file has been copied.
1 file has been copied.
1 file has been copied.
1 file has been copied.
1 file has been copied.
1 file has been copied.
1 file has been copied.
1 file has been copied.
The subdirectory or file tmp already exists.
torch: 1.11.0
torchvision: 0.12.0
sdkit: 1.0.153
stable-diffusion-sdkit: 2.1.4

"Easy Diffusion installation complete! Starting the server!"

PYTHONPATH=D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages
D:\SD\stable-diffusion-ui\stable-diffusion\env\python.exe
D:\SD\stable-diffusion-ui\installer_files\env\python.exe
D:\Program Files\Python\Python310\python.exe
Python 3.8.5
14:06:26.217 INFO MainThread started in D:\SD\stable-diffusion-ui\stable-diffusion                          server.py:29
14:06:26.220 INFO MainThread started at 12/12/23 14:06:26                                                   server.py:30
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.
14:06:26.611 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:408
14:06:26.617 INFO cuda:0 Device usage during initialization:                                               runtime.py:37
14:06:26.630 INFO cuda:0 CPU utilization: 8.9%, System RAM used: 30.3 of 63.7 GiB, GPU RAM used       memory_utils.py:47
(cuda:0): 1.0 of 6.0 GiB (peak: 0.0 GiB)
14:06:26.632 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:154
14:06:27.112 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:42
D:\SD\stable-diffusion-ui\models\stable-diffusion\chilled_re_generic_v2_f16 to device: cuda:0
No module 'xformers'. Proceeding without it.
14:06:27.118 ERROR cuda:0 Error while loading stable-diffusion model:                                model_manager.py:80
D:\SD\stable-diffusion-ui\models\stable-diffusion\chilled_re_generic_v2_f16
14:06:27.120 ERROR cuda:0 [Errno 13] Permission denied:                                              model_manager.py:86
'D:\\SD\\stable-diffusion-ui\\models\\stable-diffusion\\chilled_re_generic_v2_f16'
Traceback (most recent call last):
  File "D:\SD\stable-diffusion-ui\ui\easydiffusion\model_manager.py", line 71, in
load_default_models
    load_model(
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\__init__
.py", line 44, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\stable_d
iffusion\__init__.py", line 43, in load_model
    config_file_path = get_model_config_file(context, check_for_config_with_same_name)
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\stable_d
iffusion\__init__.py", line 412, in get_model_config_file
    quick_hash = hash_file_quick(model_path)
  File "D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\utils\hash_utils.py",
line 45, in hash_file_quick
    return compute_quick_hash(
  File "D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\utils\hash_utils.py",
line 64, in compute_quick_hash
    all_bytes = read_bytes_fn(offset=0, count=total_size)
  File "D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\utils\hash_utils.py",
line 39, in read_bytes
    with open(file_path, "rb") as f:
PermissionError: [Errno 13] Permission denied:
'D:\\SD\\stable-diffusion-ui\\models\\stable-diffusion\\chilled_re_generic_v2_f16'
╭────────────────────────────────────────────── Easy Diffusion is ready ───────────────────────────────────────────────╮
│                                                                                                                      │
│ Easy Diffusion is ready to serve requests.                                                                           │
│                                                                                                                      │
│ A new browser tab should have been opened by now.                                                                    │
│ If not, please open your web browser and navigate to http://localhost:9000/                                          │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
14:06:36.391 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:345
14:06:37.021 INFO AnyIO worker thread Scanned 301 models. Nothing infected                          model_manager.py:355
14:06:42.725 INFO cuda:0 Session 1702361193987 starting task 2170307649008 on NVIDIA GeForce RTX     task_manager.py:280
3060 Laptop GPU
14:06:42.756 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:42
D:\SD\stable-diffusion-ui\models\stable-diffusion\anime-pencil-diffusion-v1.ckpt to device: cuda:0
14:06:42.764 INFO cuda:0 loading on diffusers                                                            __init__.py:140
14:06:42.765 INFO cuda:0 using config:                                                                   __init__.py:142
D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\models_db\configs\v1-infer
ence.yaml
14:06:42.778 INFO cuda:0 using attn_precision: fp16                                                      __init__.py:151
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F95D9A8040>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/config.json
14:06:55.102 WARNING cuda:0 'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded     _http.py:225
with url: /openai/clip-vit-large-patch14/resolve/main/config.json (Caused by
ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F95D9A8040>, 'Connection to
huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD
https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/config.json
14:06:55.204 ERROR cuda:0 We couldn't connect to 'https://huggingface.co' to load this file,        model_manager.py:172
couldn't find it in the cached files and it looks like openai/clip-vit-large-patch14 is not the
path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at
'https://huggingface.co/docs/transformers/installation#offline-mode'.
Traceback (most recent call last):
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\utils\hub.py", line
409, in cached_file
    resolved_file = hf_hub_download(
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\huggingface_hub\utils\_validators
.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\huggingface_hub\file_download.py"
, line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the
requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\stable-diffusion-ui\ui\easydiffusion\model_manager.py", line 168, in
reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\__init_
_.py", line 44, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\stable_
diffusion\__init__.py", line 58, in load_model
    return load_diffusers_model(context, model_path, config_file_path, clip_skip,
convert_to_tensorrt)
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\sdkit\models\model_loader\stable_
diffusion\__init__.py", line 171, in load_diffusers_model
    default_pipe = download_from_original_stable_diffusion_ckpt(model_path, **model_load_params)
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\diffusers\pipelines\stable_diffus
ion\convert_from_ckpt.py", line 1501, in download_from_original_stable_diffusion_ckpt
    text_model = convert_ldm_clip_checkpoint(
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\diffusers\pipelines\stable_diffus
ion\convert_from_ckpt.py", line 781, in convert_ldm_clip_checkpoint
    config = CLIPTextConfig.from_pretrained(config_name)
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\models\clip\configur
ation_clip.py", line 134, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.
py", line 565, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\configuration_utils.
py", line 620, in _get_config_dict
    resolved_config_file = cached_file(
  File
"D:\SD\stable-diffusion-ui\stable-diffusion\env\lib\site-packages\transformers\utils\hub.py", line
443, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the
cached files and it looks like openai/clip-vit-large-patch14 is not the path to a directory
containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at
'https://huggingface.co/docs/transformers/installation#offline-mode'.
14:06:55.231 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:292
  File "D:\SD\stable-diffusion-ui\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "D:\SD\stable-diffusion-ui\ui\easydiffusion\tasks\render_images.py", line 71, in run
    model_manager.fail_if_models_did_not_load(context)
  File "D:\SD\stable-diffusion-ui\ui\easydiffusion\model_manager.py", line 192, in
fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: We couldn't connect to
'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like
openai/clip-vit-large-patch14 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at
'https://huggingface.co/docs/transformers/installation#offline-mode'.

14:06:55.558 INFO cuda:0 Session 1702361193987 task 2170307649008 failed!                            task_manager.py:302

**Comment by ffudeccej60724** [comment]
Again, the version is 3.0

**Comment by cmdr2** [comment]
Hi, the main error is: `Connection to
 [huggingface.co](http://huggingface.co/) timed out.`

That indicates a network problem on your PC preventing it from talking to the address (since that address is working). Can you please check the Firewall/VPN/Proxy/Antivirus settings on your PC? Thanks

**Comment by ffudeccej60724** [comment]
I have no problem accessing the following URL in my browser:
huggingface.co/openai/clip-vit-large-patch14/resolve/main/config.json

> Hi, the main error is: `Connection to [huggingface.co](http://huggingface.co/) timed out.`
> 
> That indicates a network problem on your PC preventing it from talking to the address (since that address is working). Can you please check the Firewall/VPN/Proxy/Antivirus settings on your PC? Thanks

**Comment by ffudeccej60724** [comment]
Ping huggingface.co [23.234.30.58] with 32 bytes of data:
Reply from 23.234.30.58: Bytes =32 Time <1ms TTL=64
Reply from 23.234.30.58: Bytes =32 Time =1ms TTL=64
Reply from 23.234.30.58: Bytes =32 Time <1ms TTL=64
Reply from 23.234.30.58: Bytes =32 Time <1ms TTL=64

**Comment by ffudeccej60724** [comment]
The problem is resolved because the proxy of IE is set

**Comment by nickyi1990** [comment]
I also encounter this problem, i can download this file by hand, which folder should i put it in

**Comment by Yan0613** [comment]
In the Chinese region
add 
```
import os
os.environ['HF_ENDPOINT'] = 'https://hf-mirror.com'
```
at the head of your code may solve this problem.

**Comment by Menno5** [comment]
AFAIK it's **only** trying to connect when _clip-vit-large-patch14_ is not present, corrupted or not in the right place.
I did test this by deleting the **..\EasyDiffusion\profile\.cache\..** directory (after making a back-up of course) which contains that Huggingface part..
I then did disconnect my PC from the internet and did run EasyDiffusion. Result was the same error as the OP.
Did connect to internet again and did run EasyDiffusion and everything was downloaded automatically, with a fresh  **..\EasyDiffusion\profile\.cache** as result and a working EasyDiffusion.
Then disconnected from internet again, and running and generating with EasyDiffusion works just fine. So no connection needed.
All this with txt2img.

So this seems indeed to indicate that the error is not the result from a EasyDiffusion problem but somewhere else in the system. Be it a firewall, an edited _hosts_ file, anti-virus, etc.

**Comment by Menno5** [comment]
I'm only using SD 1.5.
To test, I downloaded a SDXL model and SDXL Lora from Civitai and used that while offline and that too runs just fine. No connection needed.
Which version of EasyDiffusion are you using? I see the OP is on v2.0.
I'm using v3.0.7 (beta)

**Comment by Menno5** [comment]
Maybe an Ubuntu thing? I only use Windows 11 Pro, so don't know anything about that.

**Comment by ATButteaux** [comment]
Same error using v3.0.9 on ubuntu 24.04.1
