### ISSUE TITLE
Error: Could not load the stable-diffusion model! Reason: Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by sc0rp10n-py** [easydiffusion/easydiffusion#1713]
I want to add my own model to stable-diffusion and not use the current one. I did it, but I get error mentioned in title.

I want to use this one instead [model link](https://civitai.com/models/4201/realistic-vision-v60-b1)

I changed the nsis script where I removed sd current one model and replaced it with the one I wanted. Then after installation I am able to see that file are present. And the model is also showing up in the dropdown (I had to add it to list in python code). But on using it, I get this error.

```
Error: Could not load the stable-diffusion model! Reason: Error while deserializing header: HeaderTooLarge
```

What can be the issue? The model files are working fine, have tested them already.

**Comment by sc0rp10n-py** [comment]
terminal output
```bat
13:10:47.523 INFO cuda:0 loading stable-diffusion model from                                              __init__.py:52
C:\EasyAI\models\stable-diffusion\realisticVisionV60B1_v60B1VAE.safetensors to device: cuda:0
13:10:47.529 ERROR cuda:0 Error while deserializing header: HeaderTooLarge                          model_manager.py:185
Traceback (most recent call last):
  File "C:\EasyAI\ui\easydiffusion\model_manager.py", line 181, in reload_models_if_necessary
    action_fn(context, model_type, scan_model=False, **extra_params)  # we've scanned them already
  File "C:\EasyAI\installer_files\env\lib\site-packages\sdkit\models\model_loader\__init__.py",
line 54, in load_model
    context.models = get_loader_module(model_type).load_model(context, **kwargs)
  File
"C:\EasyAI\installer_files\env\lib\site-packages\sdkit\models\model_loader\stable_diffusion\__init_
_.py", line 55, in load_model
    sd = load_tensor_file(model_path)
  File "C:\EasyAI\installer_files\env\lib\site-packages\sdkit\utils\file_utils.py", line 13, in
load_tensor_file
    return safetensors.torch.load_file(path, device="cpu")
  File "C:\EasyAI\installer_files\env\lib\site-packages\safetensors\torch.py", line 308, in
load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
13:10:47.547 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:292
  File "C:\EasyAI\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "C:\EasyAI\ui\easydiffusion\tasks\render_images.py", line 89, in run
    model_manager.fail_if_models_did_not_load(context)
  File "C:\EasyAI\ui\easydiffusion\model_manager.py", line 212, in fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: Error while deserializing header:
HeaderTooLarge
```

**Comment by sc0rp10n-py** [comment]
ok i just found this in the wiki
https://github.com/easydiffusion/easydiffusion/wiki/Custom-Models

so according to this, only models with type checkpoint be used, the one that I want to use has type as Checkpoint Merge
so does that mean it can't be used?

**Comment by glenn-pickett** [comment]
> I want to add my own model to stable-diffusion and not use the current one. I did it, but I get error mentioned in title.
> 
> I want to use this one instead [model link](https://civitai.com/models/4201/realistic-vision-v60-b1)
> 
> I changed the nsis script where I removed sd current one model and replaced it with the one I wanted. Then after installation I am able to see that file are present. And the model is also showing up in the dropdown (I had to add it to list in python code). But on using it, I get this error.
> 
> ```
> Error: Could not load the stable-diffusion model! Reason: Error while deserializing header: HeaderTooLarge
> ```
> 
> What can be the issue? The model files are working fine, have tested them already.

Here you said you changed some scripts to add the model. You don't have to change any scripts. All you have to do is add the downloaded model to the folder where your models are located, then press the spinner next to the model dropdown in ED and you should then see all your models, you don't even have to refresh the page. I have that same model and it works, so I think your editing could be a problem or you don't know where to place the model, maybe both.

The folder where the models are usually stored looks something like this, F:\EasyDiffusion\models\ although you can change the path where ED looks for models on the Settings tab

**Comment by sc0rp10n-py** [comment]
yeah i found the link to wiki where it was mentioned, thanks @glenn-pickett
