### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by maxdjx** [easydiffusion/easydiffusion#1736]
help...

Error: Stable Diffusion had an error. Please check the logs in the command-line window.

Error: Connection with server lost.
Error: Connection with server lost.
    at waitUntil (http://localhost:9000/media/js/engine.js:324:23)
    at async Task.enqueue (http://localhost:9000/media/js/engine.js:681:13)
    at async RenderTask.enqueue (http://localhost:9000/media/js/engine.js:663:13)

RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below
might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 75, in __call__
    raise exc
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\fastapi\routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\EasyDiffusion\ui\easydiffusion\server.py", line 107, in ping
    return ping_internal(session_id)
  File "E:\EasyDiffusion\ui\easydiffusion\server.py", line 259, in ping_internal
    response["devices"] = task_manager.get_devices()
  File "E:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 372, in get_devices
    devices["active"].update({device: get_device_info(device)})
  File "E:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 336, in get_device_info
    mem_free, mem_total = torch.cuda.mem_get_info(device)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\torch\cuda\memory.py", line 618, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread cuda:0:
Traceback (most recent call last):
  File "E:\EasyDiffusion\installer_files\env\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\EasyDiffusion\installer_files\env\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 294, in thread_render
    gc(runtime.context)
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\sdkit\utils\memory_utils.py", line 18, in gc
    torch.cuda.empty_cache()
  File "E:\EasyDiffusion\installer_files\env\lib\site-packages\torch\cuda\memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by spbsidor1965** [comment]
Таже фигня, но я решил, что просто мало оперативки, если в параметрах вкл.
 Используйте CPU (не GPU)
ВНИМАНИЕ: Это будет *очень* медленно
все работает, но ОЧЕНЬ медленно

**Comment by cmdr2** [comment]
Hi, please update the graphics card drivers, and try a smaller image (e.g. 512x512) with "low" in the VRAM Usage Level (in the Settings tab of Easy Diffusion).

If it's still a problem, please feel free to reopen. And please attach *all* the logs from the command prompt window, after starting Easy Diffusion and generating an image. Thanks
