### ISSUE TITLE
Install failure. 

### ISSUE THREAD

**Issue by jaybeezy79** [easydiffusion/easydiffusion#1742]
I've attempted to install Easy Diffusion a few times and keep running into this error. 
Easy Diffusion - v3

Easy Diffusion's git repository was already installed. Updating from main..
No local changes to save
HEAD is now at dfb26ed7 Merge pull request #1702 from easydiffusion/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 2.2.1
torchvision: 0.17.1
sdkit: 2.0.15
stable-diffusion-sdkit: 2.1.5
{}

Easy Diffusion installation complete, starting the server!

PYTHONPATH=/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages
Python:  /home/justinballard79/easy-diffusion/installer_files/env/bin/python
Version: 3.8.5

Launching uvicorn

Traceback (most recent call last):
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/main.py", line 404, in main
    run(
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/config.py", line 474, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/justinballard79/easy-diffusion/ui/main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server, bucket_manager
  File "/home/justinballard79/easy-diffusion/ui/easydiffusion/model_manager.py", line 7, in <module>
    from easydiffusion import app
  File "/home/justinballard79/easy-diffusion/ui/easydiffusion/app.py", line 14, in <module>
    from easydiffusion import task_manager
  File "/home/justinballard79/easy-diffusion/ui/easydiffusion/task_manager.py", line 20, in <module>
    from easydiffusion.tasks import Task
  File "/home/justinballard79/easy-diffusion/ui/easydiffusion/tasks/__init__.py", line 2, in <module>
    from .render_images import RenderTask
  File "/home/justinballard79/easy-diffusion/ui/easydiffusion/tasks/render_images.py", line 11, in <module>
    from sdkit.generate import generate_images
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/__init__.py", line 1, in <module>
    from .image_generator import generate_images
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/image_generator.py", line 4, in <module>
    from pytorch_lightning import seed_everything
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 16, in <module>
    from torchmetrics import Accuracy as _Accuracy
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pesq import pesq
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pesq import pesq  # noqa: F401
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torchmetrics/functional/audio/pesq.py", line 16, in <module>
    from torchmetrics.utilities.imports import _PESQ_AVAILABLE
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torchmetrics/utilities/__init__.py", line 1, in <module>
    from torchmetrics.utilities.data import apply_to_collection  # noqa: F401
  File "/home/justinballard79/easy-diffusion/installer_files/env/lib/python3.8/site-packages/torchmetrics/utilities/data.py", line 17, in <module>
    from torch import Tensor, tensor
ImportError: cannot import name 'Tensor' from 'torch' (unknown location)
Press any key to continue

**Comment by cmdr2** [comment]
There have been a number of fixes and changes since this post. So if it's still an issue, can you please try this version of the installer - https://github.com/easydiffusion/easydiffusion/releases/latest/download/Easy-Diffusion-Linux.zip

Please feel free to reopen if it's still an issue. Thanks
