### ISSUE TITLE
ImportError: cannot import name 'packaging' from 'pkg_resources'  when starting

### ISSUE THREAD

**Issue by KnowOneWasTaken** [easydiffusion/easydiffusion#1781]
**Describe the bug**
I downloaded the file, extracted it and run start.sh. It installed everything but then I ran into this error. I closed the terminal and ran start.sh again but with the same outcome.

`/usr/bin/curl
/usr/bin/tar
/usr/bin/bzip2
/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/bin/git
git version 2.39.1
/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/bin/conda
conda 23.9.0

Easy Diffusion - v3

Easy Diffusion's git repository was already installed. Updating from main..
No local changes to save
HEAD is now at dfb26ed7 Merge pull request #1702 from easydiffusion/beta
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 2.0.1
torchvision: 0.15.2
sdkit: 2.0.15
stable-diffusion-sdkit: 2.1.5
{}

Easy Diffusion installation complete, starting the server!

PYTHONPATH=/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages
Python:  /home/philipp/Downloads/SD/easy-diffusion/installer_files/env/bin/python
Version: 3.8.5

Launching uvicorn

Traceback (most recent call last):
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/main.py", line 404, in main
    run(
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/config.py", line 474, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/philipp/Downloads/SD/easy-diffusion/ui/main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server, bucket_manager
  File "/home/philipp/Downloads/SD/easy-diffusion/ui/easydiffusion/model_manager.py", line 7, in <module>
    from easydiffusion import app
  File "/home/philipp/Downloads/SD/easy-diffusion/ui/easydiffusion/app.py", line 14, in <module>
    from easydiffusion import task_manager
  File "/home/philipp/Downloads/SD/easy-diffusion/ui/easydiffusion/task_manager.py", line 20, in <module>
    from easydiffusion.tasks import Task
  File "/home/philipp/Downloads/SD/easy-diffusion/ui/easydiffusion/tasks/__init__.py", line 2, in <module>
    from .render_images import RenderTask
  File "/home/philipp/Downloads/SD/easy-diffusion/ui/easydiffusion/tasks/render_images.py", line 11, in <module>
    from sdkit.generate import generate_images
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/__init__.py", line 1, in <module>
    from .image_generator import generate_images
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/image_generator.py", line 23, in <module>
    from .sampler import make_samples
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/sampler/__init__.py", line 1, in <module>
    from .sampler_main import make_samples
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/sampler/sampler_main.py", line 7, in <module>
    from . import default_samplers, k_samplers, unipc_samplers
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/sampler/k_samplers.py", line 1, in <module>
    import k_diffusion.external
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/k_diffusion/evaluation.py", line 6, in <module>
    import clip
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/clip/clip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/philipp/Downloads/SD/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pkg_resources/__init__.py)
`

**To Reproduce**
Run start.sh in terminal

**Expected behavior**
Server starting and UI opening

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3 Cinnamon Edge
 - Browser: Firefox
 - Version: 126.0

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**
I have python 3.10.12 installed, maybe this is the cause?

**Comment by jpfox** [comment]
Same error on Archlinux : 

```
PYTHONPATH=/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages                                                                       
Python:  /var/lib/ollama/easy-diffusion/installer_files/env/bin/python                                                                                          
Version: 3.8.5                                                                                                                                                  
                                                                                                                                                                
Launching uvicorn                                                                                                                                               
                                                                                                                                                                
Traceback (most recent call last):                                                                                                                              
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                            
    return _run_code(code, main_globals, None,                                                                                                                  
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/runpy.py", line 87, in _run_code                                                       
    exec(code, run_globals)                                                                                                                                     
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/__main__.py", line 4, in <module>                                
    uvicorn.main()                                                                                                                                              
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 1157, in __call__                                   
    return self.main(*args, **kwargs)                                                                                                                           
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 1078, in main                                       
    rv = self.invoke(ctx)                                                                                                                                       
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 1434, in invoke                                     
    return ctx.invoke(self.callback, **ctx.params)                                                                                                              
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/click/core.py", line 783, in invoke                                      
    return __callback(*args, **kwargs)                                                                                                                          
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/main.py", line 404, in main                                      
    run(                                                                        
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run                                                                     
    server.run()                                                                                                                                                                              
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run                                                                    
    return asyncio.run(self.serve(sockets=sockets))                                            
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/asyncio/runners.py", line 43, in run                                                                                 
    return loop.run_until_complete(main)                                                       
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete                                                             
    return future.result()                     
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve                                                                  
    config.load()                              
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/config.py", line 474, in load                                                                  
    self.loaded_app = import_from_string(self.app)                                             
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string                                                   
    raise exc from None                        
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string                                                   
    module = importlib.import_module(module_str)                                               
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/importlib/__init__.py", line 127, in import_module                                                                   
    return _bootstrap._gcd_import(name[level:], package, level)                                
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                              
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load                            
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                   
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                            
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module                      
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                 
  File "/var/lib/ollama/easy-diffusion/ui/main.py", line 1, in <module>                        
    from easydiffusion import model_manager, app, server, bucket_manager                       
  File "/var/lib/ollama/easy-diffusion/ui/easydiffusion/model_manager.py", line 7, in <module>                                                                                                
    from easydiffusion import app              
  File "/var/lib/ollama/easy-diffusion/ui/easydiffusion/app.py", line 14, in <module>                                                                                                         
    from easydiffusion import task_manager                                                     
  File "/var/lib/ollama/easy-diffusion/ui/easydiffusion/task_manager.py", line 20, in <module>                                                                                                
    from easydiffusion.tasks import Task                                                       
  File "/var/lib/ollama/easy-diffusion/ui/easydiffusion/tasks/__init__.py", line 2, in <module>                                                                                               
    from .render_images import RenderTask                                                      
  File "/var/lib/ollama/easy-diffusion/ui/easydiffusion/tasks/render_images.py", line 11, in <module>                                                                                         
    from sdkit.generate import generate_images                                                 
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/__init__.py", line 1, in <module>                                                       
    from .image_generator import generate_images                                               
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/image_generator.py", line 23, in <module>                                               
    from .sampler import make_samples          
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/sampler/__init__.py", line 1, in <module>                                               
    from .sampler_main import make_samples                                                     
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/sampler/sampler_main.py", line 7, in <module>                                           
    from . import default_samplers, k_samplers, unipc_samplers                                 
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/sdkit/generate/sampler/k_samplers.py", line 1, in <module>                                             
    import k_diffusion.external                
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/k_diffusion/__init__.py", line 1, in <module>                                                          
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils                                                                                            
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/k_diffusion/evaluation.py", line 6, in <module>                                                        
    import clip                                
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/clip/__init__.py", line 1, in <module>                                                                 
    from .clip import *                        
  File "/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/clip/clip.py", line 6, in <module>                                                                     
    from pkg_resources import packaging        
ImportError: cannot import name 'packaging' from 'pkg_resources' (/var/lib/ollama/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pkg_resources/__init__.py)
Press any key to continue                      
```

**Comment by q5sys** [comment]
@cmdr2 
Setup tools needs to be <70.0.0  Currently it's: 
```
+ setuptools                 70.0.0  pyhd8ed1ab_0        conda-forge     483kB
```

Same issue was reported with A1111: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15863#issuecomment-2125026282
As well as vllm: https://github.com/vllm-project/vllm/issues/4961

I'd file a PR to fix this, but you seem to be pulling the config for the conda env from outside this repo.

**Comment by q5sys** [comment]
For anyone that wants a way to hack this to work until it's fixed.  Download the non broken setuptools package here: https://anaconda.org/conda-forge/setuptools/69.5.1/download/noarch/setuptools-69.5.1-pyhd8ed1ab_0.conda

Unzip that somewhere and open up the `pkg-setuptools-69.5.1-pyhd8ed1ab_0.tar.zst` file that's inside. 
![image](https://github.com/easydiffusion/easydiffusion/assets/4654247/19fdd34a-04b0-4e29-855c-066917986842)

Copy the Easy Diffusion setup files to a new path and start the setup.  Watch the terminal, after it downloads conda you will see it pulling a ton of other files, wait for this download to end and the next phase of the startup to continue. Ctrl-C the window and escape, then copy the contents of the file `tar.zst` file into the `./easy-diffusion/installer_files/mamba/pkgs/setuptools-70.0.0-pyhd8ed1ab_0/` folder and allow overwrite.  


Then run the start.sh file again and it will complete the install and setup.

**Comment by SenkiJun** [comment]
@q5sys Thanks, tried on Arch but didn't work for me. Giving the same errors mentioned.

**Comment by SenkiJun** [comment]
@q5sys I couldn't make it work via changing setuptools on Arch. Ends up with same errors.

**Comment by q5sys** [comment]
@SenkiJun Hmmm, wonder why it didn't work for you.
I just did it again in a fresh path on my Rocky box and it worked.  IDK why Arch would be different since we're just talking about a conda env.  Here's the shell of the install and  where I swapped out the files.  Line 170 is where I did the file swap. You need to make sure you break the install before it links the 70.0.0 setuptools package.


[easy-setuptools-hack.txt](https://github.com/easydiffusion/easydiffusion/files/15437134/easy-setuptools-hack.txt)

**Comment by SenkiJun** [comment]
@q5sys I probably swapped out the files too late. Thanks for your time and help.

**Comment by q5sys** [comment]
You can try the patched bootstrap file I have in my fork: https://github.com/q5sys/easydiffusion/blob/main/scripts/bootstrap.sh
Hopefully that will work for you all.

**Comment by Rasenmann** [comment]
on fresh install of easydiffusion on xubuntu 22.04

installer_files/env/bin/python -m pip install "setuptools<70"

worked for me. ED started and continued downloading sd-v1.5 model.

found here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15863#issuecomment-2126171213

**Comment by saladburger** [comment]
> You can try the patched bootstrap file I have in my fork: https://github.com/q5sys/easydiffusion/blob/main/scripts/bootstrap.sh Hopefully that will work for you all.

tried with your fork on xubuntu 24.04. still the same error



> on fresh install of easydiffusion on xubuntu 22.04
> 
> installer_files/env/bin/python -m pip install "setuptools<70"
> 
> worked for me. ED started and continued downloading sd-v1.5 model.
> 
> found here: [AUTOMATIC1111/stable-diffusion-webui#15863 (comment)](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15863#issuecomment-2126171213)

where exactly did you add that argument? the python file is encrypted and I cant open it with a text editor to add the argument. if i want to start that file via commandline it says i should use python3

**Comment by q5sys** [comment]
> ok that bootstrap.sh was not yet included in your fork if the git was cloned.
> 
> To fix it I copied the code from your linked bootstrap.sh into the icluded bootstrap.sh file in easy-diffusion/scripts/ and saved it. (before fresh install)

Glad it worked for you!

**Comment by hariasimov21** [comment]
same problem but in MacOS

**Comment by TheRealBeef** [comment]
Thanks for the interim fix q5sys

**Comment by cmdr2** [comment]
Sorry for the delay, taking a look..

**Comment by cmdr2** [comment]
I've pushed a fix for this. Can you please try removing the temporary workaround (custom bootstrap.sh), and restart Easy Diffusion?

It should update itself automatically, and install the correct version of setuptools. This fix should work on Windows, Linux and Mac.

Thanks @q5sys for the interim workaround and help!

Please let me know if this continues being a problem!
