### ISSUE TITLE
 Exception(f"Could not load the {model_type} model! Reason: " + e)

### ISSUE THREAD

**Issue by kemopup** [easydiffusion/easydiffusion#1863]
**Describe the bug**

**To Reproduce**
Start generating an image with prompts.

**Expected behavior**
See generated images.

I've tried using no LoRAs and simplifying the prompts. What's annoying is it doesn't tell me what model it can't load. I've also tried a variety of checkpoints/models.

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 Pro
 - Browser: Vivaldi 7.0.3495.18 (Stable channel) (64-bit) 
 - Version: 3.0.9

**Additional context**
```17:33:18.243 ERROR cuda:0 Traceback (most recent call last):                                         task_manager.py:292
  File "C:\EasyDiffusion\ui\easydiffusion\task_manager.py", line 284, in thread_render
    task.run()
  File "C:\EasyDiffusion\ui\easydiffusion\tasks\render_images.py", line 89, in run
    model_manager.fail_if_models_did_not_load(context)
  File "C:\EasyDiffusion\ui\easydiffusion\model_manager.py", line 212, in
fail_if_models_did_not_load
    raise Exception(f"Could not load the {model_type} model! Reason: " + e)
Exception: Could not load the stable-diffusion model! Reason: Failed to import
diffusers.models.autoencoder_kl because of the following error (look up to see its traceback):
cannot import name 'DIFFUSERS_SLOW_IMPORT' from 'diffusers.utils'
(C:\EasyDiffusion\installer_files\env\lib\site-packages\diffusers\utils\__init__.py)```

**Comment by cmdr2** [comment]
Hi @chaskayote Sorry for the delay in replying. It looks like the version of `diffusers` is incorrect in your installation, not sure why.

Can you please try these steps:
1. Double-click on `Developer Console.cmd` in your Easy Diffusion folder
2. Type `python -m pip uninstall -y diffusers` and press enter.

And then start Easy Diffusion again. It will try to repair itself.

Please let me know if that doesn't work. In that case, please copy/paste *all* the logs in the command prompt window, otherwise it's hard to tell from the few lines that was pasted in the original issue. Thanks
