### ISSUE TITLE
PydanticUserError

### ISSUE THREAD

**Issue by sudo-meister** [easydiffusion/easydiffusion#1866]
When installing easydiffusion it always stops with the error "pydantic.errors.PydanticUserError". 

1. Download and unzip respective zip-file
2. run ./start.sh
3. everything downloads and installs until following error appears:
```

    class GenerateImageRequest(BaseModel):
  File "/Users/me/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 113, in __new__
    private_attributes = inspect_namespace(
  File "/Users/me/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 506, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `preserve_init_image_color_profile = False`. All model fields require a type annotation; if `preserve_init_image_color_profile` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
```

**Desktop:**

This happens with:
 - Linux Mint
 - MacOS

**Comment by hnico21** [comment]
got the same problem. Tried 2nd last release: same problem. on 2 machines using ubuntu and nobara(fedora).
also this error comes up: 
```
  Attempting uninstall: setuptools
    Found existing installation: setuptools 69.5.1
    Uninstalling setuptools-69.5.1:
      Successfully uninstalled setuptools-69.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sdkit 2.0.20.4 requires setuptools==69.5.1, but you have setuptools 69.0.0 which is incompatible.
Successfully installed setuptools-69.0.0
```

**Comment by Ember187** [comment]
Created an account to also chime in and confirm that this issue occurs on latest EndeavourOS release. 
Here's the cmd log after starting the shell script:
`Easy Diffusion - v3

Easy Diffusion's git repository was already installed. Updating from main..
No local changes to save
HEAD is now at b3a961fc Update check_modules.py
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
Found AMD GPU Navi 31 [Radeon RX 7900 XT/7900 XTX].
--- Applying Navi 3 settings
> python -m pip install --upgrade setuptools==69.0.0
Collecting setuptools==69.0.0
  Using cached setuptools-69.0.0-py3-none-any.whl.metadata (6.3 kB)
Using cached setuptools-69.0.0-py3-none-any.whl (819 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 69.5.1
    Uninstalling setuptools-69.5.1:
      Successfully uninstalled setuptools-69.5.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sdkit 2.0.20.4 requires setuptools==69.5.1, but you have setuptools 69.0.0 which is incompatible.
Successfully installed setuptools-69.0.0
torch: 2.4.1
torchvision: 0.19.1
sdkit: 2.0.20.4
stable-diffusion-sdkit: 2.1.5
diffusers: 0.28.2
{}


Easy Diffusion installation complete, starting the server!


PYTHONPATH=/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/site-packages
Python:  /home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/bin/python
Version: 3.8.5
Found AMD GPU Navi 31 [Radeon RX 7900 XT/7900 XTX].
--- Applying Navi 3 settings

Launching uvicorn

Traceback (most recent call last):
  File "scripts/check_modules.py", line 1236, in <module>
    launch_uvicorn()
  File "scripts/check_modules.py", line 422, in launch_uvicorn
    uvicorn.run(
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/main.py", line 569, in run
    server.run()
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/config.py", line 474, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/ui/main.py", line 1, in <module>
    from easydiffusion import model_manager, app, server, bucket_manager
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/ui/easydiffusion/model_manager.py", line 7, in <module>
    from easydiffusion import app
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/ui/easydiffusion/app.py", line 14, in <module>
    from easydiffusion import task_manager
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/ui/easydiffusion/task_manager.py", line 19, in <module>
    from easydiffusion import device_manager
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/ui/easydiffusion/device_manager.py", line 7, in <module>
    from easydiffusion.utils import log
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/ui/easydiffusion/utils/__init__.py", line 6, in <module>
    from .save_utils import (
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/ui/easydiffusion/utils/save_utils.py", line 10, in <module>
    from easydiffusion.types import (
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/ui/easydiffusion/types.py", line 6, in <module>
    class GenerateImageRequest(BaseModel):
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 113, in __new__
    private_attributes = inspect_namespace(
  File "/home/monarch/Downloads/Easy-Diffusion-Linux/easy-diffusion/installer_files/env/lib/python3.8/site-packages/pydantic/_internal/_model_construction.py", line 506, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `preserve_init_image_color_profile = False`. All model fields require a type annotation; if `preserve_init_image_color_profile` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.10/u/model-field-missing-annotation
Press any key to continue`

**Comment by wojtekkedzior** [comment]
Seeing exactly the same on Ubuntu 24.04.1

```
$ python3 --version
Python 3.12.3

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0
```

From the Easy Diffusion start script:
```
Easy Diffusion's git repository was already installed. Updating from main..
No local changes to save
HEAD is now at b3a961fc Update check_modules.py
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
torch: 2.0.1
torchvision: 0.15.2
sdkit: 2.0.20.4
stable-diffusion-sdkit: 2.1.5
diffusers: 0.28.
```


On previous attempts I ran into:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sdkit 2.0.20.4 requires setuptools==69.5.1, but you have setuptools 69.0.0 which is incompatible.
```

and:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.85.1 requires pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2, but you have pydantic 2.10.3 which is incompatible.
```

I resolved these dependencies errors by doing:
```
$ python3 -m venv ed_env
$ source ed_env/bin/activate
$ pip install pydantic
$ pip install setuptools
$ ./start.sh 

```

Could it be that my python version is too new?

**Comment by cmdr2** [comment]
Thanks @tjcomserv for the fix. I've released the fix to the main version.

@wojtekkedzior @sudo-meister @Ember187 @hnico21 Can you please restart Easy Diffusion and try again?

**Comment by wojtekkedzior** [comment]
@cmdr2 I can confirm it works for me now.  Thank you @tjcomserv
