### ISSUE TITLE
Beta v3.5 on Windows 11 24H2, Application startup failed. Exiting. unless run as cpu only.

### ISSUE THREAD

**Issue by AncientMystic** [easydiffusion/easydiffusion#1869]
**Describe the bug**
version v3.5 on windows 11 24h2, fails to start with gpu, will only start if render device is set to cpu only. 

(also noticed flux and lcm schedulers seem to be missing? they were the best part of v3.5 so i hope those have not been removed. )

**To Reproduce**
on windows 11 24h2, install easydiffusion, update to beta, enable 3,5 and thats it version 3 and below start fine, 3.5 fails. 

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2
 - Browser: Librewolf 131.0.3
 - Version: v3.5 beta 

**Additional context**
terminal output:
ERROR:    Traceback (most recent call last):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 540, in __aenter__
    await self._router.startup()
  File "C:\EasyDiffusion\installer_files\env\lib\site-packages\starlette\routing.py", line 624, in startup
    handler()
  File "C:\EasyDiffusion\ui\easydiffusion\server.py", line 166, in start_event
    open_browser()
  File "C:\EasyDiffusion\ui\easydiffusion\app.py", line 329, in open_browser
    if backend.is_installed():
  File "C:\EasyDiffusion\ui\easydiffusion\backends\webui\__init__.py", line 245, in is_installed
    env.update(get_env())
  File "C:\EasyDiffusion\ui\easydiffusion\backends\webui\__init__.py", line 378, in get_env
    if config.get("render_devices", "auto") == "cpu" or not has_discrete_graphics_card() or not is_cuda_available():
  File "C:\EasyDiffusion\ui\easydiffusion\backends\webui\__init__.py", line 407, in has_discrete_graphics_card
    output = subprocess.check_output(
  File "C:\EasyDiffusion\installer_files\env\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\EasyDiffusion\installer_files\env\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\EasyDiffusion\installer_files\env\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\EasyDiffusion\installer_files\env\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

ERROR:    Application startup failed. Exiting.

EDIT: PS: thank you for all your work and support for this project, it is so far the best way to generate images and i love it. You have done and amazing job here.

**Comment by cmdr2** [comment]
@AncientMystic Sorry about that. It looks like it can't find the windows program that ED uses to determine whether a GPU is available.

Can you please try these steps:
1. Press Win+R on your keyboard, and type `cmd` and press enter
2. Type `wmic path win32_videocontroller get name` and press enter
3. Type `C:\Windows\System32\wbem\wmic.exe  path win32_videocontroller get name` and press enter

What output do you get? Thanks

**Comment by cmdr2** [comment]
I haven't removed any schedulers, is ED 3.5 still set as the engine in the Settings tab?

**Comment by cmdr2** [comment]
Hi @AncientMystic I've pushed a potential fix for this problem. Can you please restart Easy Diffusion and try again? Thanks

**Comment by AncientMystic** [comment]
Thank you very much for your reply, somehow wimc became unbound and had to be reinstalled. 

I am not sure if it was that or the fix but either way, it works now.

**Comment by cmdr2** [comment]
Thanks, glad it works now!
