### ISSUE TITLE
snow but nothing else?

### ISSUE THREAD

**Issue by MikeSavad** [easydiffusion/easydiffusion#1870]
So now it snows? But there are no new updates like:

new samplers
ability to do flux without having to connect a 1000 modules in comfyui
a control net that doesn't slow my entire program down. I can't never use it because of that.
Something that will improve faces.. 

While I know there are other programs, too many actually, I like using this one, I can't find batch entries. 

So can you update this one and not just shelve it?

**Comment by cmdr2** [comment]
Hi Mike,

**Current:**

I really do understand your annoyance, it's justified, but I mean this in the nicest possible way - I'm sorry but not every update has to be something that saves the world. It's the holidays, I can add some Christmas decorations if I want to.

This is a project that I do as a hobby. If I needed the pressure to deliver "value" to customers with every single hour of my life, then this wouldn't be a hobby right? As you know, this is a free project that I do for fun.

I got burned out last year from this project, and took a break. In the meanwhile, the project continues to be useful to a lot of people in its current state. So I continue to provide fixes and support. I now also plan on improvements (see "Future" below).

Yesterday's update also included a [bug fix for Linux users](https://github.com/easydiffusion/easydiffusion/issues/1866) (which was preventing Easy Diffusion from starting).

--

**Future:**

In the past few months, I've started regaining my interest in Easy Diffusion and AI, and I'm actively working on new features and looking at new ideas (including faster controlnets). But it'll be at my pace and based on my interests. I'm not employed by this, nor do I intend to be.

I spent all day yesterday and the day before taking apart every Flux model I could find, and trying to optimize Easy Diffusion's code for that.

So I am working on real things as well. But it'll be at my pace, and based on my interests (taking user feedback into account). I'm just setting the expectations.

Again, I really mean all this in the most polite and matter-of-fact manner. No hard feelings. I understand your frustration, I'm also a user of small open-source projects like this.

--

PS: I've always read every issue you've filed, and your feedback is definitely useful. But I needed space away from this project, so apologies for not replying to those issues. You're entirely justified in asking for improvements.

PPS: I'm not sure if you've tried the new beta (ED 3.5) that I released 2 months ago, which adds Flux and LyCORIS support. It's still got a lot of rough edges, but was quite a bit of work.

**Comment by cmdr2** [comment]
Incase you haven't tried the new beta, my apologies for not publicizing it more.

You can enable the new "ED 3.5 engine" from the Settings tab in the UI, assuming you've got "Beta channel" enabled. Please make sure you restart ED after changing the engine.

**Comment by MikeSavad** [comment]
Honestly, I hate snow, I hate the holidays. I think as far as programs go, while its a nice gesture, if it takes up space on the drive and doesn't do anything, then its not something I want. I understand its a hobby, and I make AI as a hobby. I simply like the interface on this and like to see new things. I tried out comfy, and while its "neat" it reminds me of those electronic kits with the wires and springs. But you can only play if you have the manual. 

I always like new features. I always ignored the beta of things, but i'll give this a try. Thanks.  What does it do by the way?

**Comment by MikeSavad** [comment]
Oh wait I just saw the ps about what it does

**Comment by MikeSavad** [comment]
I'm not sure where bugs go, as it was loading it gave me errors at the end, as it loaded up:

Install dir: B:\AIEasyDiffusion\
C:\Program Files\Git\cmd\git.exe
git version 2.40.0.windows.1
B:\AIEasyDiffusion\installer_files\env\Library\bin\conda.bat
B:\AIEasyDiffusion\installer_files\env\Scripts\conda.exe
conda 22.11.1
.
COMSPEC=C:\WINDOWS\system32\cmd.exe
AdapterRAM  DriverDate                 DriverVersion    Name
4293918720  20231004000000.000000-000  31.0.15.3758     NVIDIA GeForce RTX 4070
4293918720  20240827000000.000000-000  32.0.11027.1003  AMD Radeon RX 6800 XT


"Easy Diffusion - v3"

"Easy Diffusion's git repository was already installed. Updating from beta.."
No local changes to save
HEAD is now at fe2443ec Annual
Already on 'beta'
Your branch is up to date with 'origin/beta'.
Already up to date.
527 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.
PYTHONPATH=B:\AIEasyDiffusion\installer_files\env\lib\site-packages
B:\AIEasyDiffusion\installer_files\env\python.exe
C:\Users\mikes\AppData\Local\Programs\Python\Python310\python.exe
C:\Users\mikes\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
torch: 2.0.1+cu118
torchvision: 0.15.2+cu118
sdkit: 2.0.15.7
stable-diffusion-sdkit: 2.1.5
diffusers: 0.21.4
{'backend': 'webui',
 'model': {'stable-diffusion': 'deliciousangerous_v10'},
 'models_dir': 'B:\\AIEasyDiffusion\\models',
 'net': {'listen_port': 9000, 'listen_to_network': False},
 'render_devices': 'auto',
 'ui': {'open_browser_on_start': True},
 'update_branch': 'beta',
 'use_v3_engine': False,
 'vram_usage_level': 'high'}


Easy Diffusion installation complete, starting the server!


PYTHONPATH=B:\AIEasyDiffusion\installer_files\env\lib\site-packages
Python:  B:\AIEasyDiffusion\installer_files\env\python.EXE
Version: 3.8.5
Checking network settings
Set listen port to  9000

Launching uvicorn

07:16:00.000 INFO MainThread started in B:\AIEasyDiffusion\stable-diffusion                                 server.py:33
07:16:00.002 INFO MainThread started at 12/13/24 07:16:00                                                   server.py:34
07:16:00.203 INFO MainThread Loading backend: webui                                                backend_manager.py:99
conda:  B:\AIEasyDiffusion\installer_files\env\Library\bin\conda.bat
conda:  B:\AIEasyDiffusion\installer_files\env\Library\bin\conda.bat
07:16:00.396 INFO MainThread Loaded backend: <module 'webui' from                                  backend_manager.py:69
'B:\\AIEasyDiffusion\\ui\\easydiffusion\\backends\\webui\\__init__.py'>
Installing the WebUI backend..
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: B:\AIEasyDiffusion\webui\system



Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate B:\AIEasyDiffusion\webui\system
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Installing packages..
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 22.11.1
  latest version: 24.11.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.11.0



## Package Plan ##

  environment location: B:\AIEasyDiffusion\webui\system

  added / updated specs:
    - git
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h2466b09_7          54 KB  conda-forge
    ca-certificates-2024.8.30  |       h56e8100_0         155 KB  conda-forge
    git-2.47.1                 |       h57928b3_0       116.4 MB  conda-forge
    libffi-3.4.2               |       h8ffe710_5          41 KB  conda-forge
    liblzma-5.6.3              |       h2466b09_1         102 KB  conda-forge
    libsqlite-3.47.2           |       h67fdade_0         870 KB  conda-forge
    libzlib-1.3.1              |       h2466b09_2          54 KB  conda-forge
    openssl-3.4.0              |       h2466b09_0         8.1 MB  conda-forge
    pip-24.3.1                 |     pyh8b19718_0         1.2 MB  conda-forge
    python-3.10.16             |h37870fc_1_cpython        15.3 MB  conda-forge
    setuptools-75.6.0          |     pyhff2d567_1         756 KB  conda-forge
    tk-8.6.13                  |       h5226925_1         3.3 MB  conda-forge
    tzdata-2024b               |       hc8b5060_0         119 KB  conda-forge
    ucrt-10.0.22621.0          |       h57928b3_1         547 KB  conda-forge
    vc-14.3                    |      ha32ba9b_23          17 KB  conda-forge
    vc14_runtime-14.42.34433   |      he29a5d6_23         737 KB  conda-forge
    vs2015_runtime-14.42.34433 |      hdffcdeb_23          17 KB  conda-forge
    wheel-0.45.1               |     pyhd8ed1ab_1          61 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       147.8 MB

The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h2466b09_7
  ca-certificates    conda-forge/win-64::ca-certificates-2024.8.30-h56e8100_0
  git                conda-forge/win-64::git-2.47.1-h57928b3_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  liblzma            conda-forge/win-64::liblzma-5.6.3-h2466b09_1
  libsqlite          conda-forge/win-64::libsqlite-3.47.2-h67fdade_0
  libzlib            conda-forge/win-64::libzlib-1.3.1-h2466b09_2
  openssl            conda-forge/win-64::openssl-3.4.0-h2466b09_0
  pip                conda-forge/noarch::pip-24.3.1-pyh8b19718_0
  python             conda-forge/win-64::python-3.10.16-h37870fc_1_cpython
  setuptools         conda-forge/noarch::setuptools-75.6.0-pyhff2d567_1
  tk                 conda-forge/win-64::tk-8.6.13-h5226925_1
  tzdata             conda-forge/noarch::tzdata-2024b-hc8b5060_0
  ucrt               conda-forge/win-64::ucrt-10.0.22621.0-h57928b3_1
  vc                 conda-forge/win-64::vc-14.3-ha32ba9b_23
  vc14_runtime       conda-forge/win-64::vc14_runtime-14.42.34433-he29a5d6_23
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.42.34433-hdffcdeb_23
  wheel              conda-forge/noarch::wheel-0.45.1-pyhd8ed1ab_1



Downloading and Extracting Packages

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
git version 2.47.1.windows.1
Python 3.10.16
Cloning into 'B:\AIEasyDiffusion\webui\webui'...
Updating files: 100% (1495/1495), done.
No local changes to save
HEAD is now at e073e4ec add batch captioning (directory based) (#2420)
HEAD is now at b592142f fix multidiffusion integrated with controlnet (#2199)
starting webui.bat B:\AIEasyDiffusion\webui\webui
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.
07:16:57.399 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:418
07:16:57.401 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:154
╭──────────────────────────────────────────── Backend engine is installing ────────────────────────────────────────────╮
│                                                                                                                      │
│ Backend: webui is still installing..                                                                                 │
│                                                                                                                      │
│ A new browser tab will open automatically after it finishes.                                                         │
│ If it does not, please open your web browser and navigate to http://localhost:9000/                                  │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[WebUI] Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
[WebUI] Collecting torch==2.3.1
[WebUI]   Downloading https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-win_amd64.whl (2423.5 MB)
[WebUI]      ---------------------------------------- 2.4/2.4 GB 63.0 MB/s eta 0:00:00
[WebUI] Collecting torchvision==0.18.1
[WebUI]   Downloading https://download.pytorch.org/whl/cu121/torchvision-0.18.1%2Bcu121-cp310-cp310-win_amd64.whl (5.7 MB)
[WebUI]      ---------------------------------------- 5.7/5.7 MB 115.2 MB/s eta 0:00:00
[WebUI] Collecting filelock (from torch==2.3.1)
[WebUI]   Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
[WebUI] Collecting typing-extensions>=4.8.0 (from torch==2.3.1)
[WebUI]   Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
[WebUI] Collecting sympy (from torch==2.3.1)
[WebUI]   Downloading sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
[WebUI] Collecting networkx (from torch==2.3.1)
[WebUI]   Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
[WebUI] Collecting jinja2 (from torch==2.3.1)
[WebUI]   Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
[WebUI] Collecting fsspec (from torch==2.3.1)
[WebUI]   Downloading fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)
[WebUI] Collecting mkl<=2021.4.0,>=2021.1.1 (from torch==2.3.1)
[WebUI]   Downloading https://download.pytorch.org/whl/mkl-2021.4.0-py2.py3-none-win_amd64.whl (228.5 MB)
[WebUI]      ------------------------------------- 228.5/228.5 MB 82.5 MB/s eta 0:00:00
[WebUI] Collecting numpy (from torchvision==0.18.1)
[WebUI]   Downloading numpy-2.2.0-cp310-cp310-win_amd64.whl.metadata (60 kB)
[WebUI] Collecting pillow!=8.3.*,>=5.3.0 (from torchvision==0.18.1)
[WebUI]   Downloading pillow-11.0.0-cp310-cp310-win_amd64.whl.metadata (9.3 kB)
[WebUI] Collecting intel-openmp==2021.* (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1)
[WebUI]   Downloading https://download.pytorch.org/whl/intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl (3.5 MB)
[WebUI]      ---------------------------------------- 3.5/3.5 MB 105.0 MB/s eta 0:00:00
[WebUI] Collecting tbb==2021.* (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1)
[WebUI]   Downloading tbb-2021.13.1-py3-none-win_amd64.whl.metadata (1.1 kB)
[WebUI] Collecting MarkupSafe>=2.0 (from jinja2->torch==2.3.1)
[WebUI]   Downloading MarkupSafe-3.0.2-cp310-cp310-win_amd64.whl.metadata (4.1 kB)
[WebUI] Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.3.1)
[WebUI]   Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
[WebUI] Downloading tbb-2021.13.1-py3-none-win_amd64.whl (286 kB)
[WebUI] Downloading pillow-11.0.0-cp310-cp310-win_amd64.whl (2.6 MB)
[WebUI]    ---------------------------------------- 2.6/2.6 MB 37.2 MB/s eta 0:00:00
[WebUI] Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
[WebUI] Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
[WebUI] Downloading fsspec-2024.10.0-py3-none-any.whl (179 kB)
[WebUI] Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
[WebUI] Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
[WebUI]    ---------------------------------------- 1.7/1.7 MB 91.3 MB/s eta 0:00:00
[WebUI] Downloading numpy-2.2.0-cp310-cp310-win_amd64.whl (12.9 MB)
[WebUI]    ---------------------------------------- 12.9/12.9 MB 101.2 MB/s eta 0:00:00
[WebUI] Downloading sympy-1.13.3-py3-none-any.whl (6.2 MB)
[WebUI]    ---------------------------------------- 6.2/6.2 MB 95.6 MB/s eta 0:00:00
[WebUI] Downloading MarkupSafe-3.0.2-cp310-cp310-win_amd64.whl (15 kB)
[WebUI] Installing collected packages: tbb, mpmath, intel-openmp, typing-extensions, sympy, pillow, numpy, networkx, mkl, MarkupSafe, fsspec, filelock, jinja2, torch, torchvision
[WebUI] Successfully installed MarkupSafe-3.0.2 filelock-3.16.1 fsspec-2024.10.0 intel-openmp-2021.4.0 jinja2-3.1.4 mkl-2021.4.0 mpmath-1.3.0 networkx-3.4.2 numpy-2.2.0 pillow-11.0.0 sympy-1.13.3 tbb-2021.13.1 torch-2.3.1+cu121 torchvision-0.18.1+cu121 typing-extensions-4.12.2
[WebUI] Cloning into 'B:\AIEasyDiffusion\webui\webui\repositories\stable-diffusion-webui-assets'...
[WebUI] Cloning into 'B:\AIEasyDiffusion\webui\webui\repositories\huggingface_guess'...
[WebUI] Cloning into 'B:\AIEasyDiffusion\webui\webui\repositories\google_blockly_prototypes'...
[WebUI] Cloning into 'B:\AIEasyDiffusion\webui\webui\repositories\BLIP'...
[WebUI] B:\AIEasyDiffusion\webui\system\lib\site-packages\transformers\utils\hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
[WebUI]   warnings.warn(
[WebUI] *** Error loading embedding **ManyEyedHorrorAI-000011.safetensors**
[WebUI]     Traceback (most recent call last):
[WebUI]       File "B:\AIEasyDiffusion\webui\webui\modules\textual_inversion\textual_inversion.py", line 200, in load_from_dir
[WebUI]         self.load_from_file(fullfn, fn)
[WebUI]       File "B:\AIEasyDiffusion\webui\webui\modules\textual_inversion\textual_inversion.py", line 182, in load_from_file
[WebUI]         embedding = create_embedding_from_data(data, name, filename=filename, filepath=path)
[WebUI]       File "B:\AIEasyDiffusion\webui\webui\modules\textual_inversion\textual_inversion.py", line 296, in create_embedding_from_data
[WebUI]         assert len(data.keys()) == 1, 'embedding file has multiple terms in it'
[WebUI]     AssertionError: embedding file has multiple terms in it
[WebUI]
[WebUI] ---
[WebUI] Python 3.10.16 | packaged by conda-forge | (main, Dec  5 2024, 14:07:43) [MSC v.1942 64 bit (AMD64)]
[WebUI] Version: f2.0.1v1.10.1-previous-591-gb592142f
[WebUI] Commit hash: b592142f3b46852263747a4efd0d244ad17b5bb3
[WebUI] Installing torch and torchvision
[WebUI] Installing clip
[WebUI] Installing open_clip
[WebUI] Cloning assets into B:\AIEasyDiffusion\webui\webui\repositories\stable-diffusion-webui-assets...
[WebUI] Cloning huggingface_guess into B:\AIEasyDiffusion\webui\webui\repositories\huggingface_guess...
[WebUI] Cloning google_blockly into B:\AIEasyDiffusion\webui\webui\repositories\google_blockly_prototypes...
[WebUI] Cloning BLIP into B:\AIEasyDiffusion\webui\webui\repositories\BLIP...
[WebUI] Installing requirements
[WebUI] Installing forge_legacy_preprocessor requirement: fvcore
[WebUI] Installing forge_legacy_preprocessor requirement: mediapipe
[WebUI] Installing forge_legacy_preprocessor requirement: onnxruntime
[WebUI] Installing forge_legacy_preprocessor requirement: svglib
[WebUI] Installing forge_legacy_preprocessor requirement: insightface
[WebUI] Installing forge_legacy_preprocessor requirement: handrefinerportable
[WebUI] Installing forge_legacy_preprocessor requirement: depth_anything
[WebUI] Installing forge_legacy_preprocessor requirement: depth_anything_v2
[WebUI] Launching Web UI with arguments: --api --models-dir 'B:\AIEasyDiffusion\models' --ckpt-dir 'B:\AIEasyDiffusion\models\stable-diffusion' --vae-dir 'B:\AIEasyDiffusion\models\vae' --hypernetwork-dir 'B:\AIEasyDiffusion\models\hypernetwork' --gfpgan-models-path 'B:\AIEasyDiffusion\models\gfpgan' --realesrgan-models-path 'B:\AIEasyDiffusion\models\realesrgan' --lora-dir 'B:\AIEasyDiffusion\models\lora' --codeformer-models-path 'B:\AIEasyDiffusion\models\codeformer' --embeddings-dir 'B:\AIEasyDiffusion\models\embeddings' --controlnet-dir 'B:\AIEasyDiffusion\models\controlnet' --skip-torch-cuda-test --always-high-vram
[WebUI] Total VRAM 12282 MB, total RAM 65399 MB
[WebUI] pytorch version: 2.3.1+cu121
[WebUI] Set vram state to: HIGH_VRAM
[WebUI] Device: cuda:0 NVIDIA GeForce RTX 4070 : native
[WebUI] Hint: your device supports --cuda-malloc for potential speed improvements.
[WebUI] VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
[WebUI] Installing bitsandbytes==0.43.3
[WebUI] CUDA Using Stream: False
[WebUI] Using pytorch cross attention
[WebUI] Using pytorch attention for VAE
[WebUI] ControlNet preprocessor location: B:\AIEasyDiffusion\models\ControlNetPreprocessor
[WebUI] Calculating sha256 for B:\AIEasyDiffusion\models\embeddings\pmantis.pt: 1f097ef233c118304bb5472288dcb2786eeceb76772492b9f9aa2df9c6eb00c5
[WebUI] Loading additional modules ... done.
[WebUI] 2024-12-13 07:23:04,511 - ControlNet - INFO - ControlNet UI callback registered.
[WebUI] Model selected: {'checkpoint_info': {'filename': 'B:\\AIEasyDiffusion\\models\\Stable-diffusion\\001 - ARTISTIC PHOTOGRAPHIC CFG5Creative7 Concept6 Fant4 Steam5 Gear3 Naut4 Anim6 Pharm5Doc4 Port4 Hand3 Face4 Arch7 Oil5 Food4 Rock0 Car5 Train5 House6 X12Anth3Mon5Sci7Ab2 VERY SHARP redSea2_.safetensors', 'hash': '523fa05a'}, 'additional_modules': [], 'unet_storage_dtype': None}
[WebUI] Using online LoRAs in FP16: False
setting sd model: deliciousangerous_v10
07:23:13.403 INFO Thread-15 Opening browser..                                                            __init__.py:142
07:23:15.036 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:456
07:23:15.215 INFO AnyIO worker thread Scanned 464 models. Nothing infected


like I don't know what ManyEyedHorrorAI-000011.safetensors  is

**Comment by MikeSavad** [comment]
I guess the timing was 40seconds at first then out of no where, 3min again. I guess that's what makes it beta. I wonder why it was so fast then slow again... Anyway at least I have new settings and such I can play with. Thanks again.

**Comment by tjcomserv** [comment]
@MikeSavad, I had the same issue a while back and found the slow down had nothing to do with Easy Diffusion, but rather other apps on the device utilising the GPU. I found the best way to use EasyDiffusion on Windows was to stop any non required background processes.

**Comment by MikeSavad** [comment]
I was using photoshop at the time, but its using a different graphics card.  I think flux is just too demanding, I tried another version and nothing came out. I can only assume I had the settings wrong, but I tried all sorts of things.  

Flux aside, I'm wondering if pony models, dmd?  And all these other sort of models, can I use those with this program?  Hard to keep up with the models.
