### ISSUE TITLE
Stable Diffusion is loading... infinetely

### ISSUE THREAD

**Issue by psychohero111** [easydiffusion/easydiffusion#1876]
**Describe the bug**
Using beta and  3.5.1 version, after start webpage opens, but status keeps being Stable Diffusion is loading..

**To Reproduce**
1. just click on launch

**Expected behavior**
1. STATUS BECOME GREEN AND READY

**Screenshots**
![Снимок экрана 2024-12-27 000225](https://github.com/user-attachments/assets/b3338873-e4db-49c6-b472-22a02718d0ff)

**Desktop (please complete the following information):**
 - OS: win11 24H2
 - Browser: Chrome 
 - Version:131.0.6778.205

**Additional context**
Install dir: E:\flux\
E:\flux\installer_files\env\Library\bin\git.exe
git version 2.46.0.windows.1
E:\flux\installer_files\env\Library\bin\conda.bat
E:\flux\installer_files\env\Scripts\conda.exe
conda 23.9.0
.
COMSPEC=C:\WINDOWS\system32\cmd.exe
AdapterRAM  DriverDate                 DriverVersion  Name
4293918720  20241106000000.000000-000  32.0.15.6614   NVIDIA GeForce RTX 3070 Ti

"Easy Diffusion - v3"

"Easy Diffusion's git repository was already installed. Updating from beta.."
No local changes to save
HEAD is now at 49488ded v3.5.1
Already on 'beta'
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> beta

Скопировано файлов: 527.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Скопировано файлов:         1.
Подпапка или файл tmp уже существует.
PYTHONPATH=E:\flux\installer_files\env\lib\site-packages
E:\flux\installer_files\env\python.exe
C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\python.exe
Python 3.8.5
torch: 2.0.1+cu117
torchvision: 0.15.2+cu117
sdkit: 2.0.20.4
stable-diffusion-sdkit: 2.1.5
diffusers: 0.28.2
{'backend': 'webui',
 'models_dir': 'E:\\flux\\models',
 'net': {'listen_port': 9000, 'listen_to_network': True},
 'render_devices': 'auto',
 'ui': {'open_browser_on_start': True},
 'update_branch': 'beta',
 'use_v3_engine': False,
 'vram_usage_level': 'high'}

Easy Diffusion installation complete, starting the server!

PYTHONPATH=E:\flux\installer_files\env\lib\site-packages
Python:  E:\flux\installer_files\env\python.EXE
Version: 3.8.5
Checking network settings
Set listen port to  9000
Set bind_ip to  0.0.0.0

Launching uvicorn

23:57:47.120 INFO MainThread started in E:\flux\stable-diffusion                                            server.py:33
23:57:47.124 INFO MainThread started at 12/26/24 23:57:47                                                   server.py:34
23:57:47.357 INFO MainThread Loading backend: webui                                                backend_manager.py:99
conda:  E:\flux\installer_files\env\Library\bin\conda.bat
conda:  E:\flux\installer_files\env\Library\bin\conda.bat
23:57:47.457 INFO MainThread Loaded backend: <module 'webui' from                                  backend_manager.py:69
'E:\\flux\\ui\\easydiffusion\\backends\\webui\\__init__.py'>
23:57:47.469 ERROR MainThread Traceback (most recent call last):                                  backend_manager.py:105
  File "E:\flux\ui\easydiffusion\backend_manager.py", line 103, in start_backend
    backend.start_backend()
  File "E:\flux\ui\easydiffusion\backends\webui\__init__.py", line 107, in start_backend
    run_in_conda(["git", "add", "-A", "."], cwd=WEBUI_DIR)
  File "E:\flux\ui\easydiffusion\backends\webui\__init__.py", line 279, in run_in_conda
    return run(cmds, *args, **kwargs)
  File "E:\flux\ui\easydiffusion\backends\webui\__init__.py", line 266, in run
    p = subprocess.Popen(cmds, cwd=cwd, env=env, stdout=subprocess.PIPE,
stderr=subprocess.STDOUT)
  File "E:\flux\installer_files\env\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\flux\installer_files\env\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] Неверно задано имя папки
Traceback (most recent call last):
  File "E:\flux\ui\easydiffusion\backend_manager.py", line 103, in start_backend
    backend.start_backend()
  File "E:\flux\ui\easydiffusion\backends\webui\__init__.py", line 107, in start_backend
    run_in_conda(["git", "add", "-A", "."], cwd=WEBUI_DIR)
  File "E:\flux\ui\easydiffusion\backends\webui\__init__.py", line 279, in run_in_conda
    return run(cmds, *args, **kwargs)
  File "E:\flux\ui\easydiffusion\backends\webui\__init__.py", line 266, in run
    p = subprocess.Popen(cmds, cwd=cwd, env=env, stdout=subprocess.PIPE,
stderr=subprocess.STDOUT)
  File "E:\flux\installer_files\env\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\flux\installer_files\env\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] Неверно задано имя папки
stable-diffusion model(s) found.
gfpgan model(s) found.
realesrgan model(s) found.
vae model(s) found.
23:57:47.633 INFO MainThread Start new Rendering Thread on device: cuda:0                            task_manager.py:418
23:57:47.633 INFO cuda:0 Setting cuda:0 as active, with precision: half                            device_manager.py:154
23:57:48.633 INFO MainThread Opening browser..                                                                app.py:333
╭────────────────────────────────────────────── Easy Diffusion is ready ───────────────────────────────────────────────╮
│                                                                                                                      │
│ Easy Diffusion is ready to serve requests.                                                                           │
│                                                                                                                      │
│ A new browser tab should have been opened by now.                                                                    │
│ If not, please open your web browser and navigate to http://localhost:9000/                                          │
│                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
23:57:49.671 INFO AnyIO worker thread Scanning all model folders for models...                      model_manager.py:456
23:57:49.900 INFO AnyIO worker thread Scanned 52 models. Nothing infected

**Comment by nijahplays** [comment]
+1

**Comment by cmdr2** [comment]
Hi @nijahplays Can you please paste the logs from your command prompt window as well? Thanks

**Comment by nijahplays** [comment]
> Hi @nijahplays Can you please paste the logs from your command prompt window as well? Thanks

[output.txt](https://github.com/user-attachments/files/18319915/output.txt)

It gets stuck at loading stable diffusion.

**Comment by cmdr2** [comment]
@nijahplays Thanks. Can you please try this:

1. In a terminal, run `./developer_console.sh` inside the Easy Diffusion folder
2. Then run: `python -m pip install --upgrade torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm6.2`
3. Then open a new terminal tab, and run Easy Diffusion.

**Comment by psychohero111** [comment]
did not help 

![image](https://github.com/user-attachments/assets/bdb41ae7-d733-447a-8fed-b179428010b5)

may be conda should be updated?

**Comment by nijahplays** [comment]
> @nijahplays Can you please try this command (in the developer console):
> 
> ```
> python -m pip uninstall torch torchvision
> python -m pip install --upgrade torch torchvision --index-url https://download.pytorch.org/whl/rocm6.2
> ```
> 
> @psychohero111 Yours is a different issue, please edit `config.yaml` in notepad and add these lines to the end of the file, save and restart Easy Diffusion:
> 
> ```
> backend_config:
>   auto_update: false
> ```
> 
> Please let me know if that doesn't fix the problem, thanks

ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

**Comment by cmdr2** [comment]
@nijahplays Thanks, can you please try this command (in the developer console):

`python -m pip install --upgrade torch==2.4.1+rocm6.1 torchvision==0.20.0+rocm6.1 --index-url https://download.pytorch.org/whl`

@psychohero111 Thanks, you can remove the two lines that you added in `config.yaml`. Does the full path to the Easy Diffusion folder contain any Cyrillic characters? I've seen that some commands occasionally fail to work due to that.

If the folder path for Easy Diffusion contains any Cyrillic characters, can you please try to move the Easy Diffusion folder to a different location? Thanks

**Comment by psychohero111** [comment]
> @nijahplays Thanks, can you please try this command (in the developer console):
> 
> `python -m pip install --upgrade torch==2.4.1+rocm6.1 torchvision==0.20.0+rocm6.1 --index-url https://download.pytorch.org/whl`
> 
> @psychohero111 Thanks, you can remove the two lines that you added in `config.yaml`. Does the full path to the Easy Diffusion folder contain any Cyrillic characters? I've seen that some commands occasionally fail to work due to that.
> 
> If the folder path for Easy Diffusion contains any Cyrillic characters, can you please try to move the Easy Diffusion folder to a different location? Thanks

@cmdr2 Hi, I have already thought about that and had ED re-installed in another folder, so there are no any Cyrillic symbols in folder name or in config file. Did not help....Maybe there is way  to make 'clean' installation? Maybe i should delete smth from appdata?

**Comment by cmdr2** [comment]
@psychohero111 Researching this a bit more, it looks like it's actually a permission error. Python 3.8 used to mask a PermissionError incorrectly with a NotADirectoryError - https://github.com/python/cpython/pull/29940/files

Did you install Easy Diffusion as administrator by any chance (it should NOT run as administrator)?

If not, can you please check whether the 'webui' folder (and the rest of Easy Diffusion) is owned by your user, and has permissions to read, write and execute? Thanks

**Comment by psychohero111** [comment]
> @psychohero111 Researching this a bit more, it might actually be a permission error. Python 3.8 used to mask a PermissionError incorrectly with a NotADirectoryError (for temp directories), so I wonder if this is a similar problem - https://github.com/python/cpython/pull/29940/files
> 
> Did you install Easy Diffusion as administrator by any chance (it should NOT run as administrator)?
> 
> If it's not admin, can you please check whether the 'webui' folder (and the rest of Easy Diffusion) is owned by your user, and has permissions to read, write and execute? Thanks


@cmdr2  I am not sure, that I've understood you right....It should be installed with admin rights or not?
In my case I have only one user on this PC, of cause it has admin rights....

**Comment by cmdr2** [comment]
@psychohero111 Sorry I wasn't clear. Easy Diffusion should NOT be installed as administrator.

In your case, that seems okay. Even if your user has admin rights, by default files are not installed as admin, unless you right-click and say "Run as administrator".

Maybe you can try a fresh install of Easy Diffusion?

**Comment by psychohero111** [comment]
@cmdr2 I did not use "Run as administrator" thing, 

sure I will make fresh installation...one more, one less =)

Do you need log before I'll switch on to 3.5.1 and beta (ED works fine)
or only just after switching on when infinite loading appears?

**Comment by psychohero111** [comment]
First start with beta and 3.5.1 on -

[log.txt](https://github.com/user-attachments/files/18331240/log.txt)

**Comment by nijahplays** [comment]
> @nijahplays Thanks, can you please try this command (in the developer console):
> 
> `python -m pip install --upgrade torch==2.4.1+rocm6.1 torchvision==0.20.0+rocm6.1 --index-url https://download.pytorch.org/whl`


This worked! It's now running as expected.

**Comment by cmdr2** [comment]
Thanks @psychohero111 , I'm looking into this. https://github.com/easydiffusion/easydiffusion/issues/1883 also seems related

**Comment by fire** [comment]
Can the developers revert to a previous version of 3.5 that worked?

**Comment by cmdr2** [comment]
@fire 3.5 works plenty of users, so it's not clear why it's failing for a few users. And from my end, I haven't pushed any code changes to 3.5 in more than a month, so I'm not sure what's changed.

I'm continuing to investigate the problem, but 3.5 is extremely beta, so please don't rely on it. It's totally possible that 3.5 may change a lot before it becomes stable.

You can always switch back to 3.0 (from the Settings tab).

**Comment by fire** [comment]
While we wait, I'll look around for another flux.1 backend. I love the work done in Easy Diffusion so much, but as far as I know, 3.0 doesn't work with flux.1.

https://github.com/replicate/cog-flux

**Comment by cmdr2** [comment]
@fire Sure, I'll ping back here when 3.5 and Flux is more stable. I'm working on that actively as we speak.

**Comment by fire** [comment]
Since I like easy diffusion's uiux design, the idea I had with `cog-flux` was that I lock in the parameters I like with easy diffusion and tell replicate.com to scale and get me a thousand images using the easy diffusion parameters, but this is going slightly off-topic.

@cmdr2 is there anything I can do to help?

**Comment by cmdr2** [comment]
@fire Can you please share the logs in the command prompt window? I want to see if you're also facing the same "NotADirectoryError" problem, or if it's something else. Thanks!

**Comment by fire** [comment]
1. On a Windows 10 install with Nvidia GPU drivers on a 4090 GPU.
2. Install easy diffusion
3. start easy diffusion
4. enable beta
5. restart easy diffusion
6. enable 3.5
7. restart easy diffusion
8. First-time launch of easy diffusion works with flux, etc.
9. restart easy diffusion
10. Failure

![Image](https://github.com/user-attachments/assets/31867112-8bee-4245-96ef-3c9cbc78a038)

**Comment by cmdr2** [comment]
@fire  Please try these steps:
1. Double-click `Developer Console.sh` (for other users on Linux, please run `./developer_console.sh`)
2. Run: `python scripts/webui_console.py`
3. Run: `python -m pip install --upgrade urllib3==2.2.3`

Please let me know if this doesn't fix the problem, thanks!

**Comment by fire** [comment]
It progresses further and isn't still stuck on the generate image test.

Thanks!

![Image](https://github.com/user-attachments/assets/e88d1a4e-9ccb-4880-805d-c544446042d8)

**Comment by dctrjons** [comment]
Just as a second, worked for me too

**Comment by cmdr2** [comment]
I've pushed a fix for the `type is not subscriptable` error in the latest beta.

I still don't have a fix for the `NotADirectoryError` (the original error in this github issue). Looking into it.
