### ISSUE TITLE
Unable to start processing an image - urllib.error.URLError: <urlopen error [WinError 10061]

### ISSUE THREAD

**Issue by theory6** [easydiffusion/easydiffusion#604]
Downloaded and installed the Stable Diffusion UI, once I got everything running and opened the "Start Stable Diffusion UI" cmd file, it opens into google Chrome and displays the UI.  If I hit "Make Image" it Error and in the upper right, Stable Diffusion has stopped.

The following code is what is in the command prompt, I'm not sure what I need to fix.

INFO:     127.0.0.1:61403 - "GET /get/app_config HTTP/1.1" 200 OK
{"render_devices": "auto", "update_branch": "main", "ui": {"open_browser_on_start": true}, "model": {"stable-diffusion": ""}, "net": {"listen_port": 9000, "listen_to_network": true}}
Could not find the configured custom model .ckpt. Using the default one: D:\SD\stable-diffusion\sd-v1-4.ckpt
INFO:     127.0.0.1:61403 - "POST /render HTTP/1.1" 200 OK
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to D:\SD\profile/.cache\torch\hub\checkpoints\checkpoint_liberty_with_aug.pth
Traceback (most recent call last):
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\SD\stable-diffusion\env\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\SD\stable-diffusion\env\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\SD\stable-diffusion\env\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\SD\stable-diffusion\env\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "D:\SD\stable-diffusion\env\lib\http\client.py", line 950, in send
    self.connect()
  File "D:\SD\stable-diffusion\env\lib\http\client.py", line 1417, in connect
    super().connect()
  File "D:\SD\stable-diffusion\env\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "D:\SD\stable-diffusion\env\lib\socket.py", line 808, in create_connection
    raise err
  File "D:\SD\stable-diffusion\env\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\ui\sd_internal\task_manager.py", line 197, in preload_model
    runtime.load_model_ckpt()
  File "D:\SD\ui\sd_internal\runtime.py", line 117, in load_model_ckpt
    load_model_ckpt_sd1()
  File "D:\SD\ui\sd_internal\runtime.py", line 153, in load_model_ckpt_sd1
    modelCS = instantiate_from_config(config.modelCondStage)
  File "D:\SD\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\SD\stable-diffusion\optimizedSD\ddpm.py", line 262, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "D:\SD\stable-diffusion\optimizedSD\ddpm.py", line 282, in instantiate_cond_stage
    model = instantiate_from_config(config)
  File "D:\SD\stable-diffusion\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\SD\stable-diffusion\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
  File "D:\SD\stable-diffusion\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\SD\stable-diffusion\ldm\modules\encoders\modules.py", line 7, in <module>
    import kornia
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\__init__.py", line 10, in <module>
    from . import (
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\augmentation\__init__.py", line 43, in <module>
    from .container import AugmentationSequential, ImageSequential, PatchSequential, VideoSequential
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\augmentation\container\__init__.py", line 1, in <module>
    from .augment import AugmentationSequential
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\augmentation\container\augment.py", line 17, in <module>
    from .patch import PatchSequential
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\augmentation\container\patch.py", line 9, in <module>
    from kornia.contrib.extract_patches import extract_tensor_patches
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\contrib\__init__.py", line 4, in <module>
    from .image_stitching import ImageStitcher
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\contrib\image_stitching.py", line 7, in <module>
    from kornia.feature import LocalFeatureMatcher, LoFTR
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\feature\__init__.py", line 4, in <module>
    from .integrated import (
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\feature\integrated.py", line 52, in <module>
    class LAFDescriptor(nn.Module):
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\feature\integrated.py", line 65, in LAFDescriptor
    patch_descriptor_module: nn.Module = HardNet(True),
  File "D:\SD\stable-diffusion\env\lib\site-packages\kornia\feature\hardnet.py", line 66, in __init__
    pretrained_dict = torch.hub.load_state_dict_from_url(
  File "D:\SD\stable-diffusion\env\lib\site-packages\torch\hub.py", line 591, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "D:\SD\stable-diffusion\env\lib\site-packages\torch\hub.py", line 457, in download_url_to_file
    u = urlopen(req)
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\SD\stable-diffusion\env\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

**Comment by JeLuF** [comment]
You can try to do the download manually:
Save the file https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth to `D:\SD\profile\.cache\torch\hub\checkpoints\checkpoint_liberty_with_aug.pth`

**Comment by rohansinghwow** [comment]
You have to download the entire repo as zip file . The direct download is not working.
- [](https://github.com/DagnyT/hardnet/archive/refs/heads/master.zip)
- After downloading and extracting the above, follow this path - _hardNet-master\pretrained\train_liberty_with_aug_
- Then _D:\SD\profile\.cache\torch\hub\checkpoints\checkpoint_liberty_with_aug.pth_ as mentioned by @JeLuF

**Comment by rohansinghwow** [comment]
My .bat file is still downloading the URL (not responding) by default. How can I make it skip the URL and fetch the local file?

**Comment by aqiulin** [comment]
During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\sd-webui-aki\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 827, in process
        detected_map, is_image = preprocessor(
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\utils.py", line 79, in decorated_func
        return cached_func(*args, **kwargs)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\utils.py", line 67, in cached_func
        return func(*args, **kwargs)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\processor.py", line 489, in lama_inpaint
        prd_color = model_lama(img_res)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 43, in __call__
        self.load_model()
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 27, in load_model
        load_file_from_url(remote_model_path, model_dir=self.model_dir)
      File "F:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\basicsr\utils\download_util.py", line 98, in load_file_from_url
        download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
      File "F:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
        u = urlopen(req)
      File "urllib\request.py", line 216, in urlopen
      File "urllib\request.py", line 519, in open
      File "urllib\request.py", line 536, in _open
      File "urllib\request.py", line 496, in _call_chain
      File "urllib\request.py", line 1391, in https_open
      File "urllib\request.py", line 1351, in do_open
    urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

**Comment by aqiulin** [comment]
During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\sd-webui-aki\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 827, in process
        detected_map, is_image = preprocessor(
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\utils.py", line 79, in decorated_func
        return cached_func(*args, **kwargs)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\utils.py", line 67, in cached_func
        return func(*args, **kwargs)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\processor.py", line 489, in lama_inpaint
        prd_color = model_lama(img_res)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 43, in __call__
        self.load_model()
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 27, in load_model
        load_file_from_url(remote_model_path, model_dir=self.model_dir)
      File "F:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\basicsr\utils\download_util.py", line 98, in load_file_from_url
        download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
      File "F:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
        u = urlopen(req)
      File "urllib\request.py", line 216, in urlopen
      File "urllib\request.py", line 519, in open
      File "urllib\request.py", line 536, in _open
      File "urllib\request.py", line 496, in _call_chain
      File "urllib\request.py", line 1391, in https_open
      File "urllib\request.py", line 1351, in do_open
    urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>

有没有解决方案，大佬们？

**Comment by aqiulin** [comment]
During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "F:\sd-webui-aki\sd-webui-aki-v4\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\controlnet.py", line 827, in process
        detected_map, is_image = preprocessor(
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\utils.py", line 79, in decorated_func
        return cached_func(*args, **kwargs)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\utils.py", line 67, in cached_func
        return func(*args, **kwargs)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\global_state.py", line 35, in unified_preprocessor
        return preprocessor_modules[preprocessor_name](*args, **kwargs)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\scripts\processor.py", line 489, in lama_inpaint
        prd_color = model_lama(img_res)
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 43, in __call__
        self.load_model()
      File "F:\sd-webui-aki\sd-webui-aki-v4\extensions\sd-webui-controlnet\annotator\lama\__init__.py", line 27, in load_model
        load_file_from_url(remote_model_path, model_dir=self.model_dir)
      File "F:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\basicsr\utils\download_util.py", line 98, in load_file_from_url
        download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
      File "F:\sd-webui-aki\sd-webui-aki-v4\py310\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
        u = urlopen(req)
      File "urllib\request.py", line 216, in urlopen
      File "urllib\request.py", line 519, in open
      File "urllib\request.py", line 536, in _open
      File "urllib\request.py", line 496, in _call_chain
      File "urllib\request.py", line 1391, in https_open
      File "urllib\request.py", line 1351, in do_open
    urllib.error.URLError: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>
     
有没有大佬指导下怎么解决！

**Comment by JeLuF** [comment]
> 有没有大佬指导下怎么解决！

Windows Error 10054 usually indicates that some firewall or anti-malware has blocked the network connection. Please make sure that your firewall settings are correct, that your anti-malware doesn't interfere and that your internet provider is not blocking the access.

**Comment by aqiulin** [comment]
> 

Thank you，Is this not a web UI error?

**Comment by JeLuF** [comment]
The Web UI runs in your web browser. The console window contains the server's output, so this is a server message.
