### ISSUE TITLE
Can't intsall Stable Diffusion

### ISSUE THREAD

**Issue by Liza2105** [easydiffusion/easydiffusion#841]
**Describe the bug**
Hi! I am total noob in tech, sorry if I am explaining the problem not very good. I just can't install Stable Diffusion on my computer. The red text is following. Please help. 
ERROR: Exception:
Traceback (most recent call last):
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in _fp_read
    data = self._fp.read(chunk_amt)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "D:\stable-diffusion-ui\installer_files\env\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "D:\stable-diffusion-ui\installer_files\env\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "D:\stable-diffusion-ui\installer_files\env\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\stable-diffusion-ui\installer_files\env\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "D:\stable-diffusion-ui\installer_files\env\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\commands\install.py", line 415, in run
    requirement_set = resolver.resolve(
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "D:\stable-diffusion-ui\installer_files\env\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 449, in _error_catcher
    raise SSLError(e)
pip._vendor.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2622)
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser:
 - Version:

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by JeLuF** [comment]
Are you running any VPN, anti-malware or proxy software that messes around with TLS certificates? Are you on a corporate or campus network that uses proxies intercepting HTTPS connections?

**Comment by Liza2105** [comment]
As far as I know no. But I am from Russia and to this https://download.pytorch.org/ access is denied

**Comment by PlatinumSphere** [comment]
I'm also getting the same exact error. I'm using a brand new Windows 10 Aero 17 XD laptop and PC with similiar specs, no proxy, standard firewall settings, home use. This is happening when the program is downloading torch-1.13.1%2Bcu116-cp38-cp38-win_amd64.whl. I'm able to download the file manually, but that's because I'm able to keep retrying to download the file in my browser and it keeps the MB downloaded (so I'm not starting from 0MB all the time). I have no issues downloading large GB files from other sites. 

C:\stable-diffusion-ui\installer_files\env\Library\bin\git.exe
git version 2.39.2.windows.1
C:\stable-diffusion-ui\installer_files\env\Library\bin\conda.bat
C:\stable-diffusion-ui\installer_files\env\Scripts\conda.exe
conda 22.11.1

"Stable Diffusion UI - v2"

"Stable Diffusion UI's git repository was already installed. Updating from main.."
HEAD is now at 51b6a2f Pin the version of stable-diffusion-sdkit used, to avoid untested releases from getting used
Already on 'main'
Your branch is up to date with 'origin/main'.
Already up to date.
491 File(s) copied
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
        1 file(s) copied.
A subdirectory or file tmp already exists.

Hotfixed broken JSON file from OpenAI
module torch not found
"Installing torch and torchvision.."
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting torch
  Downloading https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp38-cp38-win_amd64.whl (2434.2 MB)
     --------- ------------------------------ 0.6/2.4 GB 26.2 MB/s eta 0:01:11
ERROR: Exception:
Traceback (most recent call last):
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "C:\stable-diffusion-ui\installer_files\env\lib\http\client.py", line 458, in read
    n = self.readinto(b)
  File "C:\stable-diffusion-ui\installer_files\env\lib\http\client.py", line 502, in readinto
    n = self.fp.readinto(b)
  File "C:\stable-diffusion-ui\installer_files\env\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\stable-diffusion-ui\installer_files\env\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\stable-diffusion-ui\installer_files\env\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\commands\install.py", line 419, in run
    requirement_set = resolver.resolve(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 587, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\stable-diffusion-ui\installer_files\env\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 455, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
"Error installing torch. Sorry about that, please try to:"
"  1. Run this installer again."
"  2. If that doesn't fix it, please try the common troubleshooting steps at https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting"
"  3. If those steps don't help, please copy *all* the error messages in this window, and ask the community at https://discord.com/invite/u9yhsFmEkB"
"  4. If that doesn't solve the problem, please file an issue at https://github.com/cmdr2/stable-diffusion-ui/issues"
"Thanks!"
Press any key to continue . . .

**Comment by Ebriopes** [comment]
Hi, I also had the same problem, I didn't find any problem by VPN, proxy or antivirus so I couldn't install Stable Diffusion.
I didn't find a solution on the internet. So I downloaded the file to installing manually.

To be able to install the module "torch" first I had to download the file, than in my case was [https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp38-cp38-win_amd64.whl), move the file to some place inner of `C:\stable-diffusion-ui\` to do the things easier.  
After that I had to find the Python binare in `C:\stable-diffusion-ui\installer_files\env`. Now in a terminal go to this directory (`cd C:\stable-diffusion-ui\installer_files\env`), whit this I can execute the local Python. 
Now it's time to try install the module, to do that use `./python -m pip install YOUR_FILE`, in my case was `./python -m pip install ..\..\tmp\torch-1.13.1+cu116-cp38-cp38-win_amd64.whl`  

This works to me, I only had to execute the installer script again and worked.

**Comment by PlatinumSphere** [comment]
Thanks @Ebriopes I actually managed to get the files downloaded during installation a few days ago. It took roughly two hours, as the downloads kept failing. Hopefully this will help others who are having similar issues.

**Comment by JeLuF** [comment]
Please use the new installer: https://github.com/cmdr2/stable-diffusion-ui/releases/download/v2.5.24/Easy-Diffusion-Windows.exe
It already contains a running python environment with torch.

**Comment by JeLuF** [comment]
closed due to inactivity

**Comment by GJeevan7** [comment]
> Are you running any VPN, anti-malware or proxy software that messes around with TLS certificates? Are you on a corporate or campus network that uses proxies intercepting HTTPS connections?

Hi In my case yes.So do you think it PIP install's are getting blocked due to corporate VPN?
