### ISSUE TITLE
Bug during stable diffusion install

### ISSUE THREAD

**Issue by andrepassoscomposer** [easydiffusion/easydiffusion#937]
**Describe the bug**
I tried to install Stable Diffusion following the steps here
https://github.com/cmdr2/stable-diffusion-ui

I got a bug during installation

`"Installing torch and torchvision.."
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting torch
  Using cached https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp38-cp38-win_amd64.whl (2434.2 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu116/torchvision-0.14.1%2Bcu116-cp38-cp38-win_amd64.whl (4.8 MB)
Requirement already satisfied: typing-extensions in c:\stable-diffusion-ui\installer_files\env\lib\site-packages (from torch) (4.5.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\stable-diffusion-ui\installer_files\env\lib\site-packages (from torchvision) (9.4.0)
Requirement already satisfied: requests in c:\stable-diffusion-ui\installer_files\env\lib\site-packages (from torchvision) (2.28.2)
Requirement already satisfied: numpy in c:\stable-diffusion-ui\installer_files\env\lib\site-packages (from torchvision) (1.24.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\stable-diffusion-ui\installer_files\env\lib\site-packages (from requests->torchvision) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\stable-diffusion-ui\installer_files\env\lib\site-packages (from requests->torchvision) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in c:\stable-diffusion-ui\installer_files\env\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\stable-diffusion-ui\installer_files\env\lib\site-packages (from requests->torchvision) (1.26.14)
Installing collected packages: torch, torchvision`

`ERROR: Exception:
Traceback (most recent call last):
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\commands\install.py", line 507, in run
    installed = install_given_reqs(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\req\__init__.py", line 73, in install_given_reqs
    requirement.install(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\req\req_install.py", line 796, in install
    install_wheel(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\install\wheel.py", line 729, in install_wheel
    _install_wheel(
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\install\wheel.py", line 589, in _install_wheel
    file.save()
  File "C:\stable-diffusion-ui\installer_files\env\lib\site-packages\pip\_internal\operations\install\wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "C:\stable-diffusion-ui\installer_files\env\lib\shutil.py", line 202, in copyfileobj
    buf = fsrc_read(length)
  File "C:\stable-diffusion-ui\installer_files\env\lib\zipfile.py", line 940, in read
    data = self._read1(n)
  File "C:\stable-diffusion-ui\installer_files\env\lib\zipfile.py", line 1016, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid literal/lengths set`

**To Reproduce**
I followed the steps here
https://github.com/cmdr2/stable-diffusion-ui

**Expected behavior**
Stable Diffusion Installed

**Screenshots**

![Screenshot 2023-02-25 082253](https://user-images.githubusercontent.com/126349221/221371517-976ba5ee-55d9-482f-82b0-605fde659d4f.png)

**Desktop (please complete the following information):**
 - OS: WIndows
 - Version: 11

**Additional context**
I already research my issue here
https://github.com/cmdr2/stable-diffusion-ui/wiki/Troubleshooting
And already ask help on community like installation assistant suggests

**Comment by andrepassoscomposer** [comment]
Can anyboby help me with this bug?

**Comment by JeLuF** [comment]
This problem occurs for some users, and we haven't been able to find a fix for it.

We have developed a new (still experimental) installer to circumvent this problem: https://github.com/cmdr2/stable-diffusion-ui/releases/download/pack-test/Install.Easy.Diffusion.exe

If it works - it will install all the dependencies, and the default models. The main thing with this installer is that it packages all the dependencies into a single downloadable .exe file, which avoids the common issues people face with the current installer (firewall issues, conda errors, SSL errors, slow network/disconnections, etc). 

Please note: this is a very early version, it's possible it'll fail completely. Interested to hear the feedback! Thanks

**Comment by JeLuF** [comment]
closed due to inactivity
